// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  memberSignInRecordCreateSchema,
  memberSignInRecordPageQuerySchema,
  memberSignInRecordUpdateSchema,
} from "../backend/validators/member-sign-in-record.validator"

export const memberSignInRecordActionSchemas = {
  "ruoyi.cmd.member.memberSignInRecord.page": memberSignInRecordPageQuerySchema,
  "ruoyi.cmd.member.memberSignInRecord.get": z.object({ id: z.string() }),
  "ruoyi.cmd.member.memberSignInRecord.create": memberSignInRecordCreateSchema,
  "ruoyi.cmd.member.memberSignInRecord.update": memberSignInRecordUpdateSchema,
  "ruoyi.cmd.member.memberSignInRecord.delete": z.object({ id: z.string() }),
  "member.pageMemberSignInRecord": memberSignInRecordPageQuerySchema,
  "member.getMemberSignInRecord": z.object({ id: z.string() }),
  "member.createMemberSignInRecord": memberSignInRecordCreateSchema,
  "member.updateMemberSignInRecord": memberSignInRecordUpdateSchema,
  "member.deleteMemberSignInRecord": z.object({ id: z.string() }),
} as const

export const MEMBER_SIGN_IN_RECORD_ACTION_SCHEMAS = memberSignInRecordActionSchemas

export function registerActionSchemas() {
  return memberSignInRecordActionSchemas
}
