// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MemberConfigRepository } from "../repositories/member-config.repository"
import type {
  MemberConfigCreateDTO,
  MemberConfigPageQuery,
  MemberConfigUpdateDTO,
} from "../types/member-config.types"

export class MemberConfigService {
  static async page(query: MemberConfigPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MemberConfigRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MemberConfigRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MemberConfigCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MemberConfigRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("member.memberConfig.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MemberConfigUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MemberConfigRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("member.memberConfig.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MemberConfigRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("member.memberConfig.deleted", { id, actorId })
    }
    return ok
  }
}

export const memberConfigService = MemberConfigService
