// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MemberLevelRepository } from "../repositories/member-level.repository"
import type {
  MemberLevelCreateDTO,
  MemberLevelPageQuery,
  MemberLevelUpdateDTO,
} from "../types/member-level.types"

export class MemberLevelService {
  static async page(query: MemberLevelPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MemberLevelRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MemberLevelRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MemberLevelCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MemberLevelRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("member.memberLevel.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MemberLevelUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MemberLevelRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("member.memberLevel.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MemberLevelRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("member.memberLevel.deleted", { id, actorId })
    }
    return ok
  }
}

export const memberLevelService = MemberLevelService
