// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { MemberGroupService } from "./member-group.service"
import { registerActionSchemas } from "../contract/member-group.actions"
import type {
  MemberGroupCreateDTO,
  MemberGroupPageQuery,
  MemberGroupUpdateDTO,
} from "../types/member-group.types"

export class MemberGroupRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.member.memberGroup.page", async (req) => {
      const query = req.data as MemberGroupPageQuery
      return MemberGroupService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberGroup.get", async (req) => {
      const { id } = req.data as { id: string }
      return MemberGroupService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberGroup.create", async (req) => {
      const data = req.data as MemberGroupCreateDTO
      return MemberGroupService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberGroup.update", async (req) => {
      const { id, ...rest } = req.data as MemberGroupUpdateDTO
      return MemberGroupService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberGroup.delete", async (req) => {
      const { id } = req.data as { id: string }
      return MemberGroupService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const memberGroupRpc = MemberGroupRpc

export const memberGroupDomainFacade = createDomainFacade({
  domain: "member",
  serviceBus,
})
