// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { MemberLevelRecordService } from "./member-level-record.service"
import { registerActionSchemas } from "../contract/member-level-record.actions"
import type {
  MemberLevelRecordCreateDTO,
  MemberLevelRecordPageQuery,
  MemberLevelRecordUpdateDTO,
} from "../types/member-level-record.types"

export class MemberLevelRecordRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.member.memberLevelRecord.page", async (req) => {
      const query = req.data as MemberLevelRecordPageQuery
      return MemberLevelRecordService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberLevelRecord.get", async (req) => {
      const { id } = req.data as { id: string }
      return MemberLevelRecordService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberLevelRecord.create", async (req) => {
      const data = req.data as MemberLevelRecordCreateDTO
      return MemberLevelRecordService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberLevelRecord.update", async (req) => {
      const { id, ...rest } = req.data as MemberLevelRecordUpdateDTO
      return MemberLevelRecordService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.member.memberLevelRecord.delete", async (req) => {
      const { id } = req.data as { id: string }
      return MemberLevelRecordService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const memberLevelRecordRpc = MemberLevelRecordRpc

export const memberLevelRecordDomainFacade = createDomainFacade({
  domain: "member",
  serviceBus,
})
