// Auto-generated by Codegen Engine (App Router Page)
import { WmsItemBrandListPage } from "@/modules/wms/frontend/pages/wms-item-brand-list.page"

export default function Page() {
  return <WmsItemBrandListPage />
}
