// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  IotDeviceCreateDTO,
  IotDevicePageQuery,
  IotDeviceUpdateDTO,
  IotDeviceVO,
} from "@/modules/iot/backend/types/iot-device.types"

const BASE_URL = "/api/v1/admin/iot/iot-device"

export const IotDeviceApi = {
  async page(params?: IotDevicePageQuery) {
    return request.get<{ items: IotDeviceVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<IotDeviceVO>(`${BASE_URL}/${id}`)
  },

  async create(data: IotDeviceCreateDTO) {
    return request.post<IotDeviceVO>(BASE_URL, data)
  },

  async update(data: IotDeviceUpdateDTO) {
    return request.put<IotDeviceVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: IotDevicePageQuery) {
    return request.post<IotDeviceVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
