// Auto-generated by Codegen Engine
import { z } from "zod"



export const bpmOALeavePageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const bpmOALeaveCreateSchema = z.object({
  user_id: z.coerce.number().finite().optional(),
  type: z.coerce.number().finite().optional(),
  reason: z.string().trim().optional(),
  start_time: z.string().trim().optional(),
  end_time: z.string().trim().optional(),
  day: z.coerce.number().finite().optional(),
  status: z.coerce.number().finite().optional(),
  process_instance_id: z.string().trim().optional(),

}).strict()

export const bpmOALeaveUpdateSchema = bpmOALeaveCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type BpmOALeavePageQueryInput = z.infer<typeof bpmOALeavePageQuerySchema>
export type BpmOALeaveCreateInput = z.infer<typeof bpmOALeaveCreateSchema>
export type BpmOALeaveUpdateInput = z.infer<typeof bpmOALeaveUpdateSchema>
