// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { PayWalletRechargeRepository } from "../repositories/pay-wallet-recharge.repository"
import type {
  PayWalletRechargeCreateDTO,
  PayWalletRechargePageQuery,
  PayWalletRechargeUpdateDTO,
} from "../types/pay-wallet-recharge.types"

export class PayWalletRechargeService {
  static async page(query: PayWalletRechargePageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return PayWalletRechargeRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return PayWalletRechargeRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: PayWalletRechargeCreateDTO, actorId?: string, tenantId?: string) {
    const row = await PayWalletRechargeRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("pay.payWalletRecharge.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: PayWalletRechargeUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await PayWalletRechargeRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("pay.payWalletRecharge.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await PayWalletRechargeRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("pay.payWalletRecharge.deleted", { id, actorId })
    }
    return ok
  }
}

export const payWalletRechargeService = PayWalletRechargeService
