// Auto-generated by Codegen Engine (App Router Page)
import { ProductStatisticsListPage } from "@/modules/mall/frontend/pages/product-statistics-list.page"

export default function Page() {
  return <ProductStatisticsListPage />
}
