// Auto-generated by Codegen Engine
"use client"

import React, { useState, useEffect, useCallback } from "react"
import { MesWmReturnVendorDetailApi } from "../api/mes-wm-return-vendor-detail.api"
import { MesWmReturnVendorDetailForm } from "../components/MesWmReturnVendorDetailForm"
import { Pagination } from "@/modules/shared/frontend/components/pagination"
import type { MesWmReturnVendorDetailVO, MesWmReturnVendorDetailPageQuery } from "@/modules/mes/backend/types/mes-wm-return-vendor-detail.types"

export function MesWmReturnVendorDetailListPage() {
    const [data, setData] = useState<MesWmReturnVendorDetailVO[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [loading, setLoading] = useState(false)
  const [searchForm, setSearchForm] = useState<Record<string, any>>({})
  const [formOpen, setFormOpen] = useState(false)
  const [editItem, setEditItem] = useState<MesWmReturnVendorDetailVO | null>(null)

  const fetchData = useCallback(async () => {
    setLoading(true)
    try {
      const res = await MesWmReturnVendorDetailApi.page({ page, pageSize, ...searchForm })
      setData(res.items || [])
      setTotal(res.total || 0)
    } catch (err) {
      console.error("加载数据失败:", err)
    } finally {
      setLoading(false)
    }
  }, [page, pageSize, searchForm])

  useEffect(() => {
    fetchData()
  }, [fetchData])

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    setPage(1)
    fetchData()
  }

  const handleReset = () => {
    setSearchForm({})
    setPage(1)
  }

  const handleAdd = () => {
    setEditItem(null)
    setFormOpen(true)
  }

  const handleEdit = (item: MesWmReturnVendorDetailVO) => {
    setEditItem(item)
    setFormOpen(true)
  }

  const handleDelete = async (id: string) => {
    if (!window.confirm("确定要删除该记录吗？")) return
    try {
      await MesWmReturnVendorDetailApi.delete(id)
      fetchData()
    } catch (err: any) {
      alert(err?.message || "删除失败")
    }
  }

  // Agent-Native: 根节点暴露就绪信号；弹窗打开时基底打 inert，让无障碍树只留弹窗一层
  const agentState = loading ? "loading" : formOpen ? "modal-open" : total === 0 ? "empty" : "ready"

  return (
    <div
      data-agent-scope="mes-wm-return-vendor-detail"
      data-agent-state={agentState}
      data-agent-page-ready={String(!loading)}
      className="p-6 space-y-4"
    >
      {/* 弹窗打开时基底内容 inert —— Agent 不会误点到被遮挡的元素 */}
      <div inert={formOpen ? true : undefined} className="space-y-4">
      {/* 页面头部 */}
      <div className="flex items-center justify-between">
        <div>
          <h1 data-testid="mes-wm-return-vendor-detail-title" className="text-xl font-bold tracking-tight text-slate-900">MES 供应商退货明细管理</h1>
          <p className="text-xs text-slate-500 mt-0.5">MES 供应商退货明细列表与配置管理</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={fetchData}
            data-testid="mes-wm-return-vendor-detail-refresh"
            data-agent-target="mes-wm-return-vendor-detail:refresh"
            className="px-3 py-1.5 text-xs text-slate-600 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
          >
            刷新
          </button>
          <button
            onClick={handleAdd}
            data-testid="mes-wm-return-vendor-detail-create"
            data-agent-target="mes-wm-return-vendor-detail:create"
            className="px-3.5 py-1.5 text-xs text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors font-medium shadow-xs"
          >
            + 新增MES 供应商退货明细
          </button>
        </div>
      </div>

      {/* 搜索工具栏 */}
      <form
        onSubmit={handleSearch}
        data-testid="mes-wm-return-vendor-detail-search"
        data-agent-scope="mes-wm-return-vendor-detail:search"
        aria-label="MES 供应商退货明细搜索"
        className="p-3.5 bg-white rounded-xl border border-slate-200 shadow-xs flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-1.5">
          <label htmlFor="mes-wm-return-vendor-detail-search-return_id" className="text-xs text-slate-500 whitespace-nowrap">退货单 ID:</label>
          <input
            type="text"
            id="mes-wm-return-vendor-detail-search-return_id"
            data-testid="search-return_id"
            data-agent-target="mes-wm-return-vendor-detail:field:return_id"
            data-agent-state={searchForm.return_id ? "filled" : "empty"}
            aria-label="退货单 ID"
            value={searchForm.return_id ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, return_id: e.target.value }))}
            placeholder="搜索退货单 ID"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
        <div className="flex items-center gap-1.5">
          <label htmlFor="mes-wm-return-vendor-detail-search-line_id" className="text-xs text-slate-500 whitespace-nowrap">行 ID:</label>
          <input
            type="text"
            id="mes-wm-return-vendor-detail-search-line_id"
            data-testid="search-line_id"
            data-agent-target="mes-wm-return-vendor-detail:field:line_id"
            data-agent-state={searchForm.line_id ? "filled" : "empty"}
            aria-label="行 ID"
            value={searchForm.line_id ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, line_id: e.target.value }))}
            placeholder="搜索行 ID"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
        <div className="flex items-center gap-1.5">
          <label htmlFor="mes-wm-return-vendor-detail-search-material_stock_id" className="text-xs text-slate-500 whitespace-nowrap">库存记录 ID:</label>
          <input
            type="text"
            id="mes-wm-return-vendor-detail-search-material_stock_id"
            data-testid="search-material_stock_id"
            data-agent-target="mes-wm-return-vendor-detail:field:material_stock_id"
            data-agent-state={searchForm.material_stock_id ? "filled" : "empty"}
            aria-label="库存记录 ID"
            value={searchForm.material_stock_id ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, material_stock_id: e.target.value }))}
            placeholder="搜索库存记录 ID"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
        <div className="flex items-center gap-1.5">
          <label htmlFor="mes-wm-return-vendor-detail-search-item_id" className="text-xs text-slate-500 whitespace-nowrap">物料 ID:</label>
          <input
            type="text"
            id="mes-wm-return-vendor-detail-search-item_id"
            data-testid="search-item_id"
            data-agent-target="mes-wm-return-vendor-detail:field:item_id"
            data-agent-state={searchForm.item_id ? "filled" : "empty"}
            aria-label="物料 ID"
            value={searchForm.item_id ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, item_id: e.target.value }))}
            placeholder="搜索物料 ID"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
        <div className="flex items-center gap-1.5">
          <label htmlFor="mes-wm-return-vendor-detail-search-batch_id" className="text-xs text-slate-500 whitespace-nowrap">批次 ID:</label>
          <input
            type="text"
            id="mes-wm-return-vendor-detail-search-batch_id"
            data-testid="search-batch_id"
            data-agent-target="mes-wm-return-vendor-detail:field:batch_id"
            data-agent-state={searchForm.batch_id ? "filled" : "empty"}
            aria-label="批次 ID"
            value={searchForm.batch_id ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, batch_id: e.target.value }))}
            placeholder="搜索批次 ID"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
          <button type="submit" data-testid="mes-wm-return-vendor-detail-search-submit" data-agent-target="mes-wm-return-vendor-detail:search" className="px-3 py-1 text-xs text-white bg-slate-900 rounded-lg hover:bg-slate-800 transition-colors">查询</button>
          <button type="button" onClick={handleReset} data-testid="mes-wm-return-vendor-detail-search-reset" data-agent-target="mes-wm-return-vendor-detail:reset" className="px-3 py-1 text-xs text-slate-600 bg-slate-100 rounded-lg hover:bg-slate-200 transition-colors">重置</button>
        </div>
        <div className="text-xs text-slate-500">共 <span data-testid="mes-wm-return-vendor-detail-total" className="font-semibold text-slate-700">{total}</span> 条记录</div>
      </form>

      {/* 数据表格 */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table data-testid="mes-wm-return-vendor-detail-table" aria-label="MES 供应商退货明细列表" className="min-w-full divide-y divide-slate-200">
            <thead className="bg-slate-50/80">
              <tr>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">退货单 ID</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">行 ID</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">库存记录 ID</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">物料 ID</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">退货数量</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">批次 ID</th>
                <th className="px-4 py-2.5 text-right text-[11px] font-semibold text-slate-500 uppercase tracking-wider min-w-[140px]">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 bg-white">
              {loading ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center text-xs text-slate-400">加载中...</td>
                </tr>
              ) : data.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center text-xs text-slate-400">暂无数据</td>
                </tr>
              ) : (
                data.map((item) => (
                  <tr
                    key={item.id}
                    data-testid="mes-wm-return-vendor-detail-row"
                    data-agent-target="mes-wm-return-vendor-detail:row"
                    data-agent-state={editItem?.id === item.id ? "editing" : "idle"}
                    data-agent-id={item.id}
                    className="hover:bg-slate-50/60 transition-colors"
                  >
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.return_id ?? "-")}>{String(item.return_id ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.line_id ?? "-")}>{String(item.line_id ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.material_stock_id ?? "-")}>{String(item.material_stock_id ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.item_id ?? "-")}>{String(item.item_id ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.quantity ?? "-")}>{String(item.quantity ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.batch_id ?? "-")}>{String(item.batch_id ?? "-")}</td>
                    <td className="px-4 py-2.5 text-xs text-right whitespace-nowrap space-x-2">
                      <button onClick={() => handleEdit(item)} data-testid="mes-wm-return-vendor-detail-edit" data-agent-target="mes-wm-return-vendor-detail:edit" data-agent-id={item.id} aria-label={"编辑 " + item.id} className="text-blue-600 hover:text-blue-800 font-medium">编辑</button>
                      <button onClick={() => handleDelete(item.id)} data-testid="mes-wm-return-vendor-detail-delete" data-agent-target="mes-wm-return-vendor-detail:delete" data-agent-id={item.id} aria-label={"删除 " + item.id} className="text-rose-600 hover:text-rose-800 font-medium">删除</button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* 分页组件 */}
        <div data-agent-target="mes-wm-return-vendor-detail:pagination" className="p-3 border-t border-slate-200">
          <Pagination
            total={total}
            page={page}
            pageSize={pageSize}
            onPageChange={(p) => setPage(p)}
            onPageSizeChange={(ps) => setPageSize(ps)}
          />
        </div>
      </div>

      </div>

      {/* 弹窗表单 */}
      <MesWmReturnVendorDetailForm
        open={formOpen}
        initialData={editItem}
        onClose={() => setFormOpen(false)}
        onSuccess={fetchData}
      />
    </div>
  )
}
