// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { ErpStockOutItemService } from "./erp-stock-out-item.service"
import { registerActionSchemas } from "../contract/erp-stock-out-item.actions"
import type {
  ErpStockOutItemCreateDTO,
  ErpStockOutItemPageQuery,
  ErpStockOutItemUpdateDTO,
} from "../types/erp-stock-out-item.types"

export class ErpStockOutItemRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.erp.erpStockOutItem.page", async (req) => {
      const query = req.data as ErpStockOutItemPageQuery
      return ErpStockOutItemService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.erp.erpStockOutItem.get", async (req) => {
      const { id } = req.data as { id: string }
      return ErpStockOutItemService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.erp.erpStockOutItem.create", async (req) => {
      const data = req.data as ErpStockOutItemCreateDTO
      return ErpStockOutItemService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.erp.erpStockOutItem.update", async (req) => {
      const { id, ...rest } = req.data as ErpStockOutItemUpdateDTO
      return ErpStockOutItemService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.erp.erpStockOutItem.delete", async (req) => {
      const { id } = req.data as { id: string }
      return ErpStockOutItemService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const erpStockOutItemRpc = ErpStockOutItemRpc

export const erpStockOutItemDomainFacade = createDomainFacade({
  domain: "erp",
  serviceBus,
})
