// Auto-generated by Codegen Engine
import { z } from "zod"



export const erpAccountPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const erpAccountCreateSchema = z.object({
  name: z.string().trim().optional(),
  no: z.string().trim().optional(),
  remark: z.string().trim().optional(),
  status: z.coerce.number().finite().optional(),
  sort: z.coerce.number().finite().optional(),
  default_status: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),

}).strict()

export const erpAccountUpdateSchema = erpAccountCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type ErpAccountPageQueryInput = z.infer<typeof erpAccountPageQuerySchema>
export type ErpAccountCreateInput = z.infer<typeof erpAccountCreateSchema>
export type ErpAccountUpdateInput = z.infer<typeof erpAccountUpdateSchema>
