import type { InfraTemplateRecord } from "./template-engine.service"
import {
  nextReactAdminRouteTemplate,
  nextReactAdminServiceTemplate,
  nextReactAdminValidatorTemplate,
  nextReactAdminPageTemplate,
  nextReactAdminClientTemplate,
  nextReactAdminTypesTemplate,
  nextReactAdminTreePageTemplate,
  nextReactAdminTreeServiceTemplate,
  nextReactAdminTreeRouteTemplate,
  nextReactAdminTreeValidatorTemplate,
  nextReactAdminTreeClientTemplate,
  nextReactAdminTreeTypesTemplate,
  nextReactAdminWorkflowPageTemplate,
  nextReactAdminWorkflowRouteTemplate,
  nextReactAdminWorkflowServiceTemplate,
  nextReactAdminWorkflowValidatorTemplate,
  nextReactAdminWorkflowClientTemplate,
  nextReactAdminWorkflowTypesTemplate,
  nextReactAdminDomainPageTemplate,
  nextReactAdminDomainClientTemplate,
  nextReactAdminDomainTypesIndexTemplate,
  nextReactAdminRouteIndexTemplate,
  nextReactAdminFormComponentTemplate,
  nextReactAdminDetailDrawerTemplate,
  nextReactAdminFilterBarTemplate,
  nextReactAdminTableColumnsTemplate,
  nextReactAdminStoreSliceTemplate,
  nextReactAdminHookTemplate,
  nextReactAdminPermissionConstTemplate,
  nextReactAdminLocaleTemplate,
  nextReactAdminLoginPageTemplate,
  nextReactAdminHomePageTemplate,
  nextReactAdminProfilePageTemplate,
  nextReactAdminErrorPageTemplate,
  nextReactAdminIframePageTemplate,
  nextReactAdminRedirectPageTemplate,
  nextReactAdminRouterAccessTemplate,
  nextReactAdminToolbarComponentTemplate,
  nextReactAdminReportPageTemplate,
  nextReactAdminWmsPageTemplate,
  nextReactAdminMesPageTemplate,
  nextReactAdminImPageTemplate,
  nextReactAdminLayoutShellTemplate,
  nextReactAdminPluginRegistryTemplate,
  nextReactAdminAppConfigTemplate,
  nextReactAdminThemeStylesTemplate,
  nextReactAdminUtilsFormatTemplate,
  nextReactAdminAssetsManifestTemplate,
  nextReactAdminDomainListPageTemplate,
  nextReactAdminDomainDetailPageTemplate,
  nextReactAdminDomainApiIndexTemplate,
  nextReactAdminDomainViewIndexTemplate,
  nextReactAdminServiceFacadeTemplate,
  nextReactAdminServiceStrategyTemplate,
  nextReactAdminServiceGuardTemplate,
  nextReactAdminServiceTestTemplate,
  nextReactAdminServicePatternPackTemplate,
  nextReactMerchantPageTemplate,
  nextReactMerchantClientTemplate,
  nextReactCEndPageTemplate,
  nextReactCEndClientTemplate,
} from "./template-presets"

type TemplateOptions = {
  stack: "next-react"
  filePath: string
  layer: "api" | "service" | "validator" | "page" | "client" | "types"
  bundleTemplateCodes?: string[]
}

function presetTemplate(record: Omit<InfraTemplateRecord, "id" | "updatedAt" | "options"> & { options: TemplateOptions }): InfraTemplateRecord {
  return {
    ...record,
    id: `preset-${record.code}`,
    updatedAt: new Date("2026-08-03T00:00:00.000Z").toISOString(),
    options: record.options,
  }
}

/**
 * yudao `src/main/resources/codegen` 在 Next/React 侧的基础模板包。
 *
 * 这些模板故意保持“单文件、低魔法、强约束”的风格：
 * - API Route 保留薄层模式
 * - Service/Validator 分离
 * - 页面、客户端 API、共享类型三件套对齐 App Router
 */
export const DEFAULT_NEXT_REACT_TEMPLATE_PRESETS: InfraTemplateRecord[] = [
  presetTemplate({
    code: "next-react-admin-route",
    name: "Next React 管理 API 路由",
    category: "CRUD",
    templateType: "API",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 App Router 下的管理后台 API Route，保持薄层模式。",
    content: nextReactAdminRouteTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/api/admin/{{modulePath}}/route.ts",
      layer: "api",
    },
  }),
  presetTemplate({
    code: "next-react-admin-service",
    name: "Next React 管理 Service",
    category: "CRUD",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成服务层骨架，承接业务编排与数据库操作。",
    content: nextReactAdminServiceTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/services/{{modulePath}}/{{serviceFile}}",
      layer: "service",
    },
  }),
  presetTemplate({
    code: "next-react-admin-validator",
    name: "Next React 管理 Validator",
    category: "CRUD",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 Zod 验证器，兼容 App Router 请求体与查询参数。",
    content: nextReactAdminValidatorTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/validators/{{modulePath}}/{{validatorFile}}",
      layer: "validator",
    },
  }),
  presetTemplate({
    code: "next-react-admin-page",
    name: "Next React 管理页面",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 App Router 管理页骨架，适合列表 + 编辑抽屉/弹窗。",
    content: nextReactAdminPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/{{modulePath}}/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-client",
    name: "Next React 管理 API Client",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成前端请求封装，统一解包 success/data 结构。",
    content: nextReactAdminClientTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/services/{{modulePath}}.ts",
      layer: "client",
    },
  }),
  presetTemplate({
    code: "next-react-admin-types",
    name: "Next React 管理共享类型",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成共享类型定义，供页面、请求层与表单复用。",
    content: nextReactAdminTypesTemplate,
    options: {
      stack: "next-react",
      filePath: "src/shared/types/{{modulePath}}.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-tree-page",
    name: "Next React 管理树页面",
    category: "TREE",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成层级数据维护页面骨架，适配组织/菜单/区域树。",
    content: nextReactAdminTreePageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/{{modulePath}}/tree/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-tree-route",
    name: "Next React 管理树 API 路由",
    category: "TREE",
    templateType: "API",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成树管理 API 路由骨架，支持读取与节点移动。",
    content: nextReactAdminTreeRouteTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/api/admin/{{modulePath}}/tree/route.ts",
      layer: "api",
    },
  }),
  presetTemplate({
    code: "next-react-admin-tree-service",
    name: "Next React 管理树 Service",
    category: "TREE",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成树形结构服务层骨架，含读取与拖拽移动能力。",
    content: nextReactAdminTreeServiceTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/services/{{modulePath}}/tree.service.ts",
      layer: "service",
    },
  }),
  presetTemplate({
    code: "next-react-admin-tree-validator",
    name: "Next React 管理树 Validator",
    category: "TREE",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成树管理请求校验器。",
    content: nextReactAdminTreeValidatorTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/validators/{{modulePath}}/tree.validator.ts",
      layer: "validator",
    },
  }),
  presetTemplate({
    code: "next-react-admin-tree-client",
    name: "Next React 管理树 API Client",
    category: "TREE",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成树管理前端请求封装。",
    content: nextReactAdminTreeClientTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/services/{{modulePath}}/tree.ts",
      layer: "client",
    },
  }),
  presetTemplate({
    code: "next-react-admin-tree-types",
    name: "Next React 管理树类型定义",
    category: "TREE",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成树管理共享类型。",
    content: nextReactAdminTreeTypesTemplate,
    options: {
      stack: "next-react",
      filePath: "src/shared/types/{{modulePath}}/tree.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-workflow-service",
    name: "Next React 管理工作流 Service",
    category: "WORKFLOW",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成审批流程服务层骨架。",
    content: nextReactAdminWorkflowServiceTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/services/{{modulePath}}/workflow.service.ts",
      layer: "service",
    },
  }),
  presetTemplate({
    code: "next-react-admin-workflow-validator",
    name: "Next React 管理工作流 Validator",
    category: "WORKFLOW",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成审批流程请求校验器。",
    content: nextReactAdminWorkflowValidatorTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/validators/{{modulePath}}/workflow.validator.ts",
      layer: "validator",
    },
  }),
  presetTemplate({
    code: "next-react-admin-workflow-page",
    name: "Next React 管理工作流页面",
    category: "WORKFLOW",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成流程审批列表页面骨架，预置待审状态统计。",
    content: nextReactAdminWorkflowPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/{{modulePath}}/workflow/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-workflow-route",
    name: "Next React 管理工作流 API 路由",
    category: "WORKFLOW",
    templateType: "API",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成流程审批 API 路由骨架，包含审批 PATCH 动作。",
    content: nextReactAdminWorkflowRouteTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/api/admin/{{modulePath}}/workflow/route.ts",
      layer: "api",
    },
  }),
  presetTemplate({
    code: "next-react-admin-workflow-client",
    name: "Next React 管理工作流 API Client",
    category: "WORKFLOW",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成审批流程前端请求封装。",
    content: nextReactAdminWorkflowClientTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/services/{{modulePath}}/workflow.ts",
      layer: "client",
    },
  }),
  presetTemplate({
    code: "next-react-admin-workflow-types",
    name: "Next React 管理工作流类型定义",
    category: "WORKFLOW",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成审批流程共享类型。",
    content: nextReactAdminWorkflowTypesTemplate,
    options: {
      stack: "next-react",
      filePath: "src/shared/types/{{modulePath}}/workflow.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-domain-page",
    name: "Next React 管理域导航页面",
    category: "DOMAIN",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域聚合导航页骨架，承接列表/树/流程入口。",
    content: nextReactAdminDomainPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/{{modulePath}}/domain/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-domain-client",
    name: "Next React 管理域 API Client",
    category: "DOMAIN",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域聚合 API 请求封装。",
    content: nextReactAdminDomainClientTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/services/{{modulePath}}/domain.ts",
      layer: "client",
    },
  }),
  presetTemplate({
    code: "next-react-admin-domain-types-index",
    name: "Next React 管理域类型索引",
    category: "DOMAIN",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域聚合页面与统计类型定义。",
    content: nextReactAdminDomainTypesIndexTemplate,
    options: {
      stack: "next-react",
      filePath: "src/shared/types/{{modulePath}}/domain.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-route-index",
    name: "Next React 管理路由索引",
    category: "DOMAIN",
    templateType: "API",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域 API 路径索引常量，供前后端统一引用。",
    content: nextReactAdminRouteIndexTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/api/admin/{{modulePath}}/index.ts",
      layer: "api",
    },
  }),
  presetTemplate({
    code: "next-react-admin-form-component",
    name: "Next React 管理表单组件",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 React Hook Form + Zod 的管理表单组件骨架。",
    content: nextReactAdminFormComponentTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/components/admin/{{modulePath}}/{{entityName}}-form.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-detail-drawer",
    name: "Next React 管理详情抽屉",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理详情抽屉组件骨架。",
    content: nextReactAdminDetailDrawerTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/components/admin/{{modulePath}}/{{entityName}}-detail-drawer.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-filter-bar",
    name: "Next React 管理筛选条",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理列表筛选条组件骨架。",
    content: nextReactAdminFilterBarTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/components/admin/{{modulePath}}/{{entityName}}-filter-bar.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-table-columns",
    name: "Next React 管理列表列配置",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 TanStack Table 列定义骨架。",
    content: nextReactAdminTableColumnsTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/components/admin/{{modulePath}}/{{entityName}}-table-columns.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-store-slice",
    name: "Next React 管理状态切片",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理页本地 UI 状态的 Zustand 切片。",
    content: nextReactAdminStoreSliceTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/stores/{{modulePath}}-store.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-hook",
    name: "Next React 管理查询 Hook",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域列表查询 Hook（TanStack Query）。",
    content: nextReactAdminHookTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/hooks/use-{{modulePath}}.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-permission-const",
    name: "Next React 管理权限常量",
    category: "FOUNDATION",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域权限常量定义。",
    content: nextReactAdminPermissionConstTemplate,
    options: {
      stack: "next-react",
      filePath: "src/shared/constants/{{modulePath}}-permissions.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-locale",
    name: "Next React 管理本地化词条",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域中文词条文件骨架。",
    content: nextReactAdminLocaleTemplate,
    options: {
      stack: "next-react",
      filePath: "src/shared/locales/{{modulePath}}.zh-CN.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-login-page",
    name: "Next React 管理登录页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台登录页骨架。",
    content: nextReactAdminLoginPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/login/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-home-page",
    name: "Next React 管理首页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台首页统计卡片页骨架。",
    content: nextReactAdminHomePageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/home/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-profile-page",
    name: "Next React 管理个人中心页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台个人中心页面骨架。",
    content: nextReactAdminProfilePageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/profile/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-error-page",
    name: "Next React 管理错误页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台错误态页面骨架。",
    content: nextReactAdminErrorPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/error/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-iframe-page",
    name: "Next React 管理 IFrame 页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台 IFrame 承载页骨架。",
    content: nextReactAdminIframePageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/iframe/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-redirect-page",
    name: "Next React 管理跳转页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台路由跳转页骨架。",
    content: nextReactAdminRedirectPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/redirect/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-router-access",
    name: "Next React 管理路由访问规则",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理端静态路由清单与访问工具函数。",
    content: nextReactAdminRouterAccessTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/config/admin-route-access.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-toolbar-component",
    name: "Next React 管理列表工具栏",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成列表页工具栏组件骨架。",
    content: nextReactAdminToolbarComponentTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/components/admin/{{modulePath}}/{{entityName}}-toolbar.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-report-page",
    name: "Next React 管理报表页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台报表中心页面骨架。",
    content: nextReactAdminReportPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/report/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-wms-page",
    name: "Next React 管理 WMS 页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台 WMS 业务入口页骨架。",
    content: nextReactAdminWmsPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/wms/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-mes-page",
    name: "Next React 管理 MES 页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台 MES 业务入口页骨架。",
    content: nextReactAdminMesPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/mes/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-im-page",
    name: "Next React 管理 IM 页",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台 IM 协同入口页骨架。",
    content: nextReactAdminImPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/im/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-layout-shell",
    name: "Next React 管理布局壳组件",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台页面通用头部+内容壳组件。",
    content: nextReactAdminLayoutShellTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/components/layout/admin-layout-shell.tsx",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-plugin-registry",
    name: "Next React 管理插件注册表",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台插件开关注册表。",
    content: nextReactAdminPluginRegistryTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/plugins/admin-plugins.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-app-config",
    name: "Next React 管理配置",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台配置常量骨架。",
    content: nextReactAdminAppConfigTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/config/admin-app-config.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-theme-styles",
    name: "Next React 管理主题样式",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成后台主题样式骨架。",
    content: nextReactAdminThemeStylesTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/styles/admin-theme.css",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-utils-format",
    name: "Next React 管理格式化工具",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域状态与时间格式化工具函数。",
    content: nextReactAdminUtilsFormatTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/utils/{{modulePath}}-format.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-assets-manifest",
    name: "Next React 管理资源清单",
    category: "FOUNDATION",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成管理域静态资源路径清单。",
    content: nextReactAdminAssetsManifestTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/assets/{{modulePath}}-assets.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-domain-list-page",
    name: "Next React 管理域列表页",
    category: "DOMAIN",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成域级模块列表导航页。",
    content: nextReactAdminDomainListPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/{{modulePath}}/domain/list/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-domain-detail-page",
    name: "Next React 管理域详情页",
    category: "DOMAIN",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成域级详情聚合页。",
    content: nextReactAdminDomainDetailPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/admin/{{modulePath}}/domain/detail/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-admin-domain-api-index",
    name: "Next React 管理域 API 索引",
    category: "DOMAIN",
    templateType: "API",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成域级 API 端点索引映射。",
    content: nextReactAdminDomainApiIndexTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/api/admin/{{modulePath}}/domain/index.ts",
      layer: "api",
    },
  }),
  presetTemplate({
    code: "next-react-admin-domain-view-index",
    name: "Next React 管理域视图索引",
    category: "DOMAIN",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成域级页面路由索引映射。",
    content: nextReactAdminDomainViewIndexTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/config/{{modulePath}}-domain-view.ts",
      layer: "types",
    },
  }),
  presetTemplate({
    code: "next-react-admin-service-facade",
    name: "Next React 管理 Service 门面",
    category: "FOUNDATION",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 Service Facade 门面骨架，统一执行管道。",
    content: nextReactAdminServiceFacadeTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/services/{{modulePath}}/{{entityName}}.facade.ts",
      layer: "service",
    },
  }),
  presetTemplate({
    code: "next-react-admin-service-strategy",
    name: "Next React 管理 Service 策略",
    category: "FOUNDATION",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成策略模式骨架与策略解析器。",
    content: nextReactAdminServiceStrategyTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/services/{{modulePath}}/strategies/{{entityName}}.strategy.ts",
      layer: "service",
    },
  }),
  presetTemplate({
    code: "next-react-admin-service-guard",
    name: "Next React 管理 Service 状态守卫",
    category: "FOUNDATION",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成状态迁移守卫骨架。",
    content: nextReactAdminServiceGuardTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/services/{{modulePath}}/guards/{{entityName}}-state.guard.ts",
      layer: "service",
    },
  }),
  presetTemplate({
    code: "next-react-admin-service-test",
    name: "Next React 管理 Service 测试",
    category: "FOUNDATION",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 Service 门面关键路径测试骨架。",
    content: nextReactAdminServiceTestTemplate,
    options: {
      stack: "next-react",
      filePath: "src/backend/services/{{modulePath}}/__tests__/{{entityName}}.facade.test.ts",
      layer: "service",
    },
  }),
  presetTemplate({
    code: "next-react-admin-service-pattern-pack",
    name: "Next React 管理 Service 设计模式组合包",
    category: "FOUNDATION",
    templateType: "BACKEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "一键导出 Service 设计模式四件套（Facade/Strategy/Guard/Test）。",
    content: nextReactAdminServicePatternPackTemplate,
    options: {
      stack: "next-react",
      filePath: "templates/service-pattern-pack.txt",
      layer: "service",
      bundleTemplateCodes: [
        "next-react-admin-service-facade",
        "next-react-admin-service-strategy",
        "next-react-admin-service-guard",
        "next-react-admin-service-test",
      ],
    },
  }),
  presetTemplate({
    code: "next-react-merchant-page",
    name: "Next React 商户工作台页面",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成商户端 PC 工作台页面骨架。",
    content: nextReactMerchantPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(admin)/merchant/{{modulePath}}/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-merchant-client",
    name: "Next React 商户 API Client",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成商户端 API 请求封装，面向 /api/merchant 前缀。",
    content: nextReactMerchantClientTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/services/merchant/{{modulePath}}.ts",
      layer: "client",
    },
  }),
  presetTemplate({
    code: "next-react-c-end-page",
    name: "Next React C 端移动页面",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 C 端移动页面骨架，默认接入 ui-system 组件。",
    content: nextReactCEndPageTemplate,
    options: {
      stack: "next-react",
      filePath: "src/app/(public)/{{modulePath}}/page.tsx",
      layer: "page",
    },
  }),
  presetTemplate({
    code: "next-react-c-end-client",
    name: "Next React C 端 API Client",
    category: "CRUD",
    templateType: "FRONTEND",
    engine: "handlebars",
    status: "ACTIVE",
    description: "生成 C 端 API 请求封装，面向 /api 公共前缀。",
    content: nextReactCEndClientTemplate,
    options: {
      stack: "next-react",
      filePath: "src/frontend/services/public/{{modulePath}}.ts",
      layer: "client",
    },
  }),
]
