// Auto-generated by Codegen Engine (App Router Page)
import { MesWmMiscReceiptDetailListPage } from "@/modules/mes/frontend/pages/mes-wm-misc-receipt-detail-list.page"

export default function Page() {
  return <MesWmMiscReceiptDetailListPage />
}
