// Auto-generated by Codegen Engine
"use client"

import React, { useState, useEffect } from "react"
import { ErpSaleOutApi } from "../api/erp-sale-out.api"
import type { ErpSaleOutCreateDTO, ErpSaleOutVO } from "@/modules/erp/backend/types/erp-sale-out.types"

interface ErpSaleOutFormProps {
  open: boolean
  initialData?: ErpSaleOutVO | null
  onClose: () => void
  onSuccess: () => void
}

export function ErpSaleOutForm({ open, initialData, onClose, onSuccess }: ErpSaleOutFormProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [formData, setFormData] = useState<Record<string, any>>({})

  useEffect(() => {
    if (open) {
      setError(null)
      setFormData({
    no: initialData?.no ?? "",
    status: initialData?.status ?? undefined,
    customer_id: initialData?.customer_id ?? undefined,
    account_id: initialData?.account_id ?? undefined,
    sale_user_id: initialData?.sale_user_id ?? undefined,
    out_time: initialData?.out_time ?? "",
    order_id: initialData?.order_id ?? undefined,
    order_no: initialData?.order_no ?? "",
    total_count: initialData?.total_count ?? undefined,
    total_price: initialData?.total_price ?? undefined,
    receipt_price: initialData?.receipt_price ?? undefined,
    total_product_price: initialData?.total_product_price ?? undefined,
    total_tax_price: initialData?.total_tax_price ?? undefined,
    discount_percent: initialData?.discount_percent ?? undefined,
    discount_price: initialData?.discount_price ?? undefined,
    other_price: initialData?.other_price ?? undefined,
    file_url: initialData?.file_url ?? "",
    remark: initialData?.remark ?? "",
      })
    }
  }, [open, initialData])

  if (!open) return null

  const isEdit = Boolean(initialData?.id)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)
    try {
      if (isEdit && initialData?.id) {
        await ErpSaleOutApi.update({ id: initialData.id, ...formData } as any)
      } else {
        await ErpSaleOutApi.create(formData as ErpSaleOutCreateDTO)
      }
      onSuccess()
      onClose()
    } catch (err: any) {
      setError(err?.message || "操作失败")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div data-testid="erp-sale-out-form-overlay" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs">
      <div
        role="dialog"
        aria-modal="true"
        aria-label={isEdit ? "编辑ERP 销售出库" : "新增ERP 销售出库"}
        data-testid="erp-sale-out-form"
        data-agent-scope="erp-sale-out:form"
        data-agent-state={loading ? "submitting" : error ? "error" : "open"}
        className="bg-white rounded-lg shadow-xl w-full max-w-lg mx-4 overflow-hidden">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h3 className="text-sm font-semibold text-slate-800">
            {isEdit ? "编辑ERP 销售出库" : "新增ERP 销售出库"}
          </h3>
          <button onClick={onClose} data-testid="erp-sale-out-form-close" data-agent-target="erp-sale-out:close" aria-label="关闭" className="text-slate-400 hover:text-slate-600 text-lg leading-none">&times;</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="px-6 py-4 space-y-3 max-h-[70vh] overflow-y-auto">
            {error && (
              <div data-testid="erp-sale-out-form-error" role="alert" className="p-2 text-xs text-red-600 bg-red-50 rounded border border-red-200">{error}</div>
            )}
        <div>
          <label htmlFor="erp-sale-out-no" className="block text-xs text-slate-600 mb-1">销售出库单号</label>
          <input
            type="text"
            id="erp-sale-out-no"
            data-testid="field-no"
            data-agent-target="erp-sale-out:field:no"
            data-agent-state={formData.no ? "filled" : "empty"}
            aria-label="销售出库单号"
            value={formData.no ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, no: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入销售出库单号"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-status" className="block text-xs text-slate-600 mb-1">出库状态</label>
          <input
            type="number"
            id="erp-sale-out-status"
            data-testid="field-status"
            data-agent-target="erp-sale-out:field:status"
            data-agent-state={formData.status == null || formData.status === "" ? "empty" : "filled"}
            aria-label="出库状态"
            value={formData.status != null ? String(formData.status) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, status: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入出库状态"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-customer_id" className="block text-xs text-slate-600 mb-1">客户编号</label>
          <input
            type="number"
            id="erp-sale-out-customer_id"
            data-testid="field-customer_id"
            data-agent-target="erp-sale-out:field:customer_id"
            data-agent-state={formData.customer_id == null || formData.customer_id === "" ? "empty" : "filled"}
            aria-label="客户编号"
            value={formData.customer_id != null ? String(formData.customer_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, customer_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入客户编号"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-account_id" className="block text-xs text-slate-600 mb-1">结算账户编号</label>
          <input
            type="number"
            id="erp-sale-out-account_id"
            data-testid="field-account_id"
            data-agent-target="erp-sale-out:field:account_id"
            data-agent-state={formData.account_id == null || formData.account_id === "" ? "empty" : "filled"}
            aria-label="结算账户编号"
            value={formData.account_id != null ? String(formData.account_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, account_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入结算账户编号"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-sale_user_id" className="block text-xs text-slate-600 mb-1">销售员编号</label>
          <input
            type="number"
            id="erp-sale-out-sale_user_id"
            data-testid="field-sale_user_id"
            data-agent-target="erp-sale-out:field:sale_user_id"
            data-agent-state={formData.sale_user_id == null || formData.sale_user_id === "" ? "empty" : "filled"}
            aria-label="销售员编号"
            value={formData.sale_user_id != null ? String(formData.sale_user_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, sale_user_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入销售员编号"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-out_time" className="block text-xs text-slate-600 mb-1">出库时间</label>
          <input
            type="text"
            id="erp-sale-out-out_time"
            data-testid="field-out_time"
            data-agent-target="erp-sale-out:field:out_time"
            data-agent-state={formData.out_time ? "filled" : "empty"}
            aria-label="出库时间"
            value={formData.out_time ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, out_time: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入出库时间"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-order_id" className="block text-xs text-slate-600 mb-1">销售订单编号</label>
          <input
            type="number"
            id="erp-sale-out-order_id"
            data-testid="field-order_id"
            data-agent-target="erp-sale-out:field:order_id"
            data-agent-state={formData.order_id == null || formData.order_id === "" ? "empty" : "filled"}
            aria-label="销售订单编号"
            value={formData.order_id != null ? String(formData.order_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, order_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入销售订单编号"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-order_no" className="block text-xs text-slate-600 mb-1">销售订单号</label>
          <input
            type="text"
            id="erp-sale-out-order_no"
            data-testid="field-order_no"
            data-agent-target="erp-sale-out:field:order_no"
            data-agent-state={formData.order_no ? "filled" : "empty"}
            aria-label="销售订单号"
            value={formData.order_no ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, order_no: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入销售订单号"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-total_count" className="block text-xs text-slate-600 mb-1">合计数量</label>
          <input
            type="number"
            id="erp-sale-out-total_count"
            data-testid="field-total_count"
            data-agent-target="erp-sale-out:field:total_count"
            data-agent-state={formData.total_count == null || formData.total_count === "" ? "empty" : "filled"}
            aria-label="合计数量"
            value={formData.total_count != null ? String(formData.total_count) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, total_count: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入合计数量"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-total_price" className="block text-xs text-slate-600 mb-1">最终合计价格，单位：元</label>
          <input
            type="number"
            id="erp-sale-out-total_price"
            data-testid="field-total_price"
            data-agent-target="erp-sale-out:field:total_price"
            data-agent-state={formData.total_price == null || formData.total_price === "" ? "empty" : "filled"}
            aria-label="最终合计价格，单位：元"
            value={formData.total_price != null ? String(formData.total_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, total_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入最终合计价格，单位：元"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-receipt_price" className="block text-xs text-slate-600 mb-1">已收款金额，单位：元</label>
          <input
            type="number"
            id="erp-sale-out-receipt_price"
            data-testid="field-receipt_price"
            data-agent-target="erp-sale-out:field:receipt_price"
            data-agent-state={formData.receipt_price == null || formData.receipt_price === "" ? "empty" : "filled"}
            aria-label="已收款金额，单位：元"
            value={formData.receipt_price != null ? String(formData.receipt_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, receipt_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入已收款金额，单位：元"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-total_product_price" className="block text-xs text-slate-600 mb-1">合计产品价格，单位：元</label>
          <input
            type="number"
            id="erp-sale-out-total_product_price"
            data-testid="field-total_product_price"
            data-agent-target="erp-sale-out:field:total_product_price"
            data-agent-state={formData.total_product_price == null || formData.total_product_price === "" ? "empty" : "filled"}
            aria-label="合计产品价格，单位：元"
            value={formData.total_product_price != null ? String(formData.total_product_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, total_product_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入合计产品价格，单位：元"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-total_tax_price" className="block text-xs text-slate-600 mb-1">合计税额，单位：元</label>
          <input
            type="number"
            id="erp-sale-out-total_tax_price"
            data-testid="field-total_tax_price"
            data-agent-target="erp-sale-out:field:total_tax_price"
            data-agent-state={formData.total_tax_price == null || formData.total_tax_price === "" ? "empty" : "filled"}
            aria-label="合计税额，单位：元"
            value={formData.total_tax_price != null ? String(formData.total_tax_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, total_tax_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入合计税额，单位：元"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-discount_percent" className="block text-xs text-slate-600 mb-1">优惠率，百分比</label>
          <input
            type="number"
            id="erp-sale-out-discount_percent"
            data-testid="field-discount_percent"
            data-agent-target="erp-sale-out:field:discount_percent"
            data-agent-state={formData.discount_percent == null || formData.discount_percent === "" ? "empty" : "filled"}
            aria-label="优惠率，百分比"
            value={formData.discount_percent != null ? String(formData.discount_percent) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, discount_percent: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入优惠率，百分比"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-discount_price" className="block text-xs text-slate-600 mb-1">优惠金额，单位：元</label>
          <input
            type="number"
            id="erp-sale-out-discount_price"
            data-testid="field-discount_price"
            data-agent-target="erp-sale-out:field:discount_price"
            data-agent-state={formData.discount_price == null || formData.discount_price === "" ? "empty" : "filled"}
            aria-label="优惠金额，单位：元"
            value={formData.discount_price != null ? String(formData.discount_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, discount_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入优惠金额，单位：元"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-other_price" className="block text-xs text-slate-600 mb-1">其它金额，单位：元</label>
          <input
            type="number"
            id="erp-sale-out-other_price"
            data-testid="field-other_price"
            data-agent-target="erp-sale-out:field:other_price"
            data-agent-state={formData.other_price == null || formData.other_price === "" ? "empty" : "filled"}
            aria-label="其它金额，单位：元"
            value={formData.other_price != null ? String(formData.other_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, other_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入其它金额，单位：元"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-file_url" className="block text-xs text-slate-600 mb-1">附件地址</label>
          <input
            type="text"
            id="erp-sale-out-file_url"
            data-testid="field-file_url"
            data-agent-target="erp-sale-out:field:file_url"
            data-agent-state={formData.file_url ? "filled" : "empty"}
            aria-label="附件地址"
            value={formData.file_url ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, file_url: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入附件地址"
            
          />
        </div>

        <div>
          <label htmlFor="erp-sale-out-remark" className="block text-xs text-slate-600 mb-1">备注</label>
          <input
            type="text"
            id="erp-sale-out-remark"
            data-testid="field-remark"
            data-agent-target="erp-sale-out:field:remark"
            data-agent-state={formData.remark ? "filled" : "empty"}
            aria-label="备注"
            value={formData.remark ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, remark: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入备注"
            
          />
        </div>
          </div>

          <div className="flex items-center justify-end gap-2 px-6 py-3 border-t border-slate-200 bg-slate-50">
            <button
              type="button"
              onClick={onClose}
              data-testid="erp-sale-out-form-cancel"
              data-agent-target="erp-sale-out:cancel"
              className="px-4 py-1.5 text-xs text-slate-600 hover:text-slate-800 border border-slate-300 rounded hover:bg-slate-100 transition-colors"
            >
              取消
            </button>
            <button
              type="submit"
              disabled={loading}
              data-testid="erp-sale-out-form-submit"
              data-agent-target="erp-sale-out:submit"
              data-agent-state={loading ? "busy" : "idle"}
              className="px-4 py-1.5 text-xs text-white bg-blue-600 rounded hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              {loading ? "保存中..." : "保存"}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
