import {
  type CodegenConfig,
  type CodegenOutput,
  configuredColumns,
  formColumns,
  getBackendPath,
  hasTableColumn,
  persistOrderColumn,
  queryColumns,
  toCamel,
  toKebab,
} from "./common"

export function generateRepository(config: CodegenConfig): CodegenOutput {
  const { className } = config
  const kebab = toKebab(className)
  const tableColumns = configuredColumns(config).map((column) => column.name)
  const writableColumns = formColumns(config).map((column) => column.name)
  const filters = queryColumns(config).map((column) => ({ name: column.name, operator: column.query?.operator ?? column.queryType ?? "=" }))
  const content = `// Auto-generated by Codegen Engine
// Dialect differences stay in shared/dynamic-table; this repository only names the physical table and columns.
import { ApiError } from "@/modules/shared/backend/http/api-error"
import { getCurrentTenantId, isTenantRequired, isPlatformContext } from "@/modules/shared/backend/lib/biz-tenant"
import {
  alwaysTrue,
  comparePredicate,
  deleteDynamicRow,
  eqColumn,
  existsDynamicRow,
  hasRealDatabase,
  insertDynamicRow,
  joinAnd,
  matchesMemory,
  selectDynamicById,
  selectDynamicPage,
  updateDynamicRow,
  type DynamicPersistScope,
  type DynamicQueryOperator,
} from "@/modules/shared/backend/lib/database"

const TABLE_NAME = ${JSON.stringify(config.table.name)}
const TABLE_COLUMNS = ${JSON.stringify(tableColumns)} as const
const WRITABLE_COLUMNS = ${JSON.stringify(writableColumns)} as const
const FILTERS = ${JSON.stringify(filters)} as Array<{ name: string; operator: DynamicQueryOperator }>
const ORDER_COLUMN = ${JSON.stringify(persistOrderColumn(config))}
const HAS_TENANT = ${hasTableColumn(config, "tenant_id")}
const HAS_DELETED = ${hasTableColumn(config, "deleted")}
const HAS_CREATOR = ${hasTableColumn(config, "creator")}
const HAS_UPDATER = ${hasTableColumn(config, "updater")}
const HAS_CREATED_AT = ${hasTableColumn(config, "created_at")}
const HAS_UPDATED_AT = ${hasTableColumn(config, "updated_at")}
const HAS_CREATE_TIME = ${hasTableColumn(config, "create_time")}
const HAS_UPDATE_TIME = ${hasTableColumn(config, "update_time")}
const MEMORY_STORE: Array<Record<string, unknown>> = []

function resolveScope(scope?: DynamicPersistScope): DynamicPersistScope {
  const tenantId = scope?.tenantId ?? getCurrentTenantId()
  if (HAS_TENANT && !tenantId && isTenantRequired() && !isPlatformContext()) {
    throw new ApiError("FORBIDDEN", "业务数据访问缺少租户上下文")
  }
  return { ...scope, tenantId }
}

function scopedWhere(scope?: DynamicPersistScope) {
  const effective = resolveScope(scope)
  const predicates = [alwaysTrue()]
  if (HAS_DELETED) predicates.push(eqColumn("deleted", false))
  if (HAS_TENANT) {
    if (!effective.tenantId && hasRealDatabase() && isTenantRequired() && !isPlatformContext()) {
      throw new ApiError("FORBIDDEN", "Tenant scope is required")
    }
    if (effective.tenantId) predicates.push(eqColumn("tenant_id", effective.tenantId))
  }
  return joinAnd(predicates)
}

function timestamp(now: Date) {
  return hasRealDatabase() ? now : now.toISOString()
}

function persistable(data: Record<string, unknown>, extra: Record<string, unknown> = {}) {
  const row: Record<string, unknown> = { ...extra }
  for (const key of WRITABLE_COLUMNS) if (data[key] !== undefined) row[key] = data[key]
  if (typeof data.id === "string") row.id = data.id
  if (data.children !== undefined) row.children = data.children
  return row
}

function dbValues(row: Record<string, unknown>) {
  return Object.fromEntries(Object.entries(row).filter(([key]) => (TABLE_COLUMNS as readonly string[]).includes(key)))
}

function memoryMatches(row: Record<string, unknown>, scope?: DynamicPersistScope) {
  const effective = resolveScope(scope)
  if (HAS_DELETED && row.deleted === true) return false
  if (HAS_TENANT && effective.tenantId && row.tenant_id !== effective.tenantId) return false
  return true
}

export const ${className}Repository = {
  async page(input: { page: number; pageSize: number } & Record<string, unknown>, scope?: DynamicPersistScope) {
    const effective = resolveScope(scope)
    if (hasRealDatabase()) {
      const predicates = [scopedWhere(effective)]
      for (const filter of FILTERS) {
        const predicate = comparePredicate(filter.name, input[filter.name], filter.operator)
        if (predicate) predicates.push(predicate)
      }
      const result = await selectDynamicPage({ tableName: TABLE_NAME, where: joinAnd(predicates), orderColumn: ORDER_COLUMN, page: input.page, pageSize: input.pageSize })
      return { ...result, page: input.page, pageSize: input.pageSize }
    }
    let filtered = MEMORY_STORE.filter((row) => memoryMatches(row, effective))
    for (const filter of FILTERS) filtered = filtered.filter((row) => matchesMemory(row[filter.name], input[filter.name], filter.operator))
    const start = (input.page - 1) * input.pageSize
    return { items: filtered.slice(start, start + input.pageSize), total: filtered.length, page: input.page, pageSize: input.pageSize }
  },

  async findById(id: string, scope?: DynamicPersistScope) {
    const effective = resolveScope(scope)
    if (hasRealDatabase()) return selectDynamicById(TABLE_NAME, id, scopedWhere(effective))
    return MEMORY_STORE.find((row) => row.id === id && memoryMatches(row, effective)) ?? null
  },

  async existsByField(field: string, value: unknown, scope?: DynamicPersistScope) {
    const effective = resolveScope(scope)
    if (hasRealDatabase()) return existsDynamicRow(TABLE_NAME, joinAnd([scopedWhere(effective), eqColumn(field, value)]))
    return MEMORY_STORE.some((row) => row[field] === value && memoryMatches(row, effective))
  },

  async create(data: Record<string, unknown>, scope?: DynamicPersistScope) {
    const effective = resolveScope(scope)
    const now = new Date()
    const row = persistable(data, {
      id: typeof data.id === "string" ? data.id : crypto.randomUUID(),
      ...(HAS_CREATOR ? { creator: effective.actorId ?? "" } : {}),
      ...(HAS_UPDATER ? { updater: effective.actorId ?? "" } : {}),
      ...(HAS_DELETED ? { deleted: false } : {}),
      ...(HAS_TENANT ? { tenant_id: effective.tenantId ?? null } : {}),
      ...(HAS_CREATED_AT ? { created_at: timestamp(now) } : {}),
      ...(HAS_UPDATED_AT ? { updated_at: timestamp(now) } : {}),
      ...(HAS_CREATE_TIME ? { create_time: timestamp(now) } : {}),
      ...(HAS_UPDATE_TIME ? { update_time: timestamp(now) } : {}),
    })
    if (hasRealDatabase()) {
      if (HAS_TENANT && !effective.tenantId && isTenantRequired() && !isPlatformContext()) throw new ApiError("FORBIDDEN", "Tenant scope is required")
      return insertDynamicRow(TABLE_NAME, dbValues(row))
    }
    MEMORY_STORE.push(row)
    return row
  },

  async update(id: string, data: Record<string, unknown>, scope?: DynamicPersistScope) {
    const effective = resolveScope(scope)
    const now = new Date()
    const patch = persistable(data, {
      ...(HAS_UPDATER ? { updater: effective.actorId ?? "" } : {}),
      ...(HAS_UPDATED_AT ? { updated_at: timestamp(now) } : {}),
      ...(HAS_UPDATE_TIME ? { update_time: timestamp(now) } : {}),
    })
    if (hasRealDatabase()) {
      return updateDynamicRow(TABLE_NAME, dbValues(patch), joinAnd([eqColumn("id", id), scopedWhere(effective)]))
    }
    const idx = MEMORY_STORE.findIndex((row) => row.id === id && memoryMatches(row, effective))
    if (idx < 0) return null
    MEMORY_STORE[idx] = { ...MEMORY_STORE[idx], ...patch }
    return MEMORY_STORE[idx]
  },

  async delete(id: string, scope?: DynamicPersistScope) {
    const effective = resolveScope(scope)
    if (hasRealDatabase()) {
      if (HAS_DELETED) {
        const row = await updateDynamicRow(TABLE_NAME, dbValues({ deleted: true, ...(HAS_UPDATER ? { updater: effective.actorId ?? "" } : {}), ...(HAS_UPDATE_TIME ? { update_time: timestamp(new Date()) } : {}), ...(HAS_UPDATED_AT ? { updated_at: timestamp(new Date()) } : {}) }), joinAnd([eqColumn("id", id), scopedWhere(effective)]))
        return Boolean(row)
      }
      return deleteDynamicRow(TABLE_NAME, joinAnd([eqColumn("id", id), scopedWhere(effective)]))
    }
    const idx = MEMORY_STORE.findIndex((row) => row.id === id && memoryMatches(row, effective))
    if (idx < 0) return false
    MEMORY_STORE.splice(idx, 1)
    return true
  },
}

export const ${toCamel(className)}Repository = ${className}Repository
`
  return { path: `${getBackendPath(config)}/repositories/${kebab}.repository.ts`, content, type: "repository" }
}
