// Auto-generated by Codegen Engine (App Router Page)
import { MpMessageListPage } from "@/modules/mp/frontend/pages/mp-message-list.page"

export default function Page() {
  return <MpMessageListPage />
}
