// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { WmsCheckOrderDetailService } from "../wms-check-order-detail.service"

describe("WmsCheckOrderDetailService", () => {
  it("should create and query 盘点明细", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await WmsCheckOrderDetailService.create({
        check_order_id: "测试盘点明细",
        item_id: "测试盘点明细",
        system_qty: 1,
        check_qty: 1,
        diff_qty: 1,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await WmsCheckOrderDetailService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await WmsCheckOrderDetailService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await WmsCheckOrderDetailService.update(created.id, {
        id: created.id,
        check_order_id: "更新盘点明细",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await WmsCheckOrderDetailService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
