// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  ImChannelMessageCreateDTO,
  ImChannelMessagePageQuery,
  ImChannelMessageUpdateDTO,
  ImChannelMessageVO,
} from "@/modules/im/backend/types/im-channel-message.types"

const BASE_URL = "/api/v1/admin/im/im-channel-message"

export const ImChannelMessageApi = {
  async page(params?: ImChannelMessagePageQuery) {
    return request.get<{ items: ImChannelMessageVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<ImChannelMessageVO>(`${BASE_URL}/${id}`)
  },

  async create(data: ImChannelMessageCreateDTO) {
    return request.post<ImChannelMessageVO>(BASE_URL, data)
  },

  async update(data: ImChannelMessageUpdateDTO) {
    return request.put<ImChannelMessageVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: ImChannelMessagePageQuery) {
    return request.post<ImChannelMessageVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
