"use client"

import { useEffect, useMemo, useState } from "react"
import { API, request } from "@/modules/shared/frontend/lib/request"

type DataSource = { id: string; name: string; driver: string }
type ReportResult = { columns: string[]; rows: Array<Record<string, unknown>>; truncated: boolean; durationMs: number; maxRows: number }
const controlClass = "h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100 disabled:cursor-not-allowed disabled:bg-slate-100"

function parameterNames(sql: string): string[] {
  const names = new Set<string>(); let quote: "'" | '"' | "`" | null = null
  for (let index = 0; index < sql.length; index += 1) { const char = sql[index]; if (quote) { if (char === quote) { if (quote === "'" && sql[index + 1] === "'") { index += 1; continue }; quote = null }; continue }; if (char === "'" || char === '"' || char === "`") { quote = char; continue }; if (char === ":") { const match = sql.slice(index + 1).match(/^[A-Za-z_][A-Za-z0-9_]*/); if (match) { names.add(match[0]); index += match[0].length } } }
  return [...names]
}
function displayValue(value: unknown) { if (value === null || value === undefined || value === "") return "—"; if (typeof value === "object") return JSON.stringify(value); return String(value) }

export default function OnlineTestPage() {
  const [sources, setSources] = useState<DataSource[]>([]); const [dataSourceId, setDataSourceId] = useState(""); const [sql, setSql] = useState("SELECT *\nFROM your_table\nWHERE created_at >= :startDate\nORDER BY created_at DESC"); const [parameters, setParameters] = useState<Record<string, string>>({}); const [maxRows, setMaxRows] = useState(200); const [result, setResult] = useState<ReportResult | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false)
  const names = useMemo(() => parameterNames(sql), [sql])
  useEffect(() => { setParameters((current) => Object.fromEntries(names.map((name) => [name, current[name] ?? ""]))) }, [names])
  const loadSources = async () => { const response = await request.get<DataSource[]>(`${API.REPORT_CUSTOM_SQL}/data-sources`); if (response.success && response.data) { setSources(response.data); setDataSourceId((current) => current || response.data[0]?.id || ""); setMessage(response.data.length ? "" : "暂无可用数据源，请先在数据源配置中添加受限只读账号。") } else setMessage(response.error ?? "数据源加载失败") }
  useEffect(() => { void loadSources() }, [])
  const execute = async () => { if (!dataSourceId) { setMessage("请选择数据源"); return }; if (names.some((name) => !parameters[name]?.trim())) { setMessage("请填写全部 SQL 参数"); return }; setBusy(true); setMessage(""); try { const response = await request.post<ReportResult>(`${API.REPORT_CUSTOM_SQL}/execute`, { dataSourceId, sql, parameters: Object.fromEntries(names.map((name) => [name, parameters[name]])), maxRows }); if (response.success && response.data) { setResult(response.data); setMessage("") } else setMessage(response.error ?? "报表执行失败") } finally { setBusy(false) } }
  const reset = () => { setSql(""); setParameters({}); setResult(null); setMessage("") }
  return <main className="min-h-full bg-slate-50 p-4 lg:p-6"><div className="mx-auto max-w-[1600px] space-y-4">
    <header className="rounded-xl border border-slate-200 bg-white px-5 py-4 shadow-sm"><div className="text-xs font-semibold text-blue-600">AUTO REPORT · READ ONLY</div><h1 className="mt-1 text-xl font-semibold text-slate-900">AUTO报表</h1><p className="mt-1 text-sm text-slate-500">使用已配置的只读数据源执行单条参数化 SELECT，自动生成表格报表。</p></header>
    {message && <div role="status" className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">{message}</div>}
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-3"><div><h2 className="text-sm font-medium text-slate-800">报表配置</h2><p className="mt-1 text-xs text-slate-500">仅平台管理员可用；连接信息与参数值不会在界面日志中展示。</p></div><button type="button" onClick={() => void loadSources()} disabled={busy} className="h-8 rounded-lg border border-slate-200 px-3 text-xs text-slate-700 hover:bg-slate-50 disabled:opacity-50">刷新</button></div><div className="grid gap-4 p-5 lg:grid-cols-[minmax(0,1fr)_260px]"><div className="grid gap-4"><label className="grid gap-1.5 text-sm text-slate-700"><span>数据源<b className="ml-1 text-rose-600">*</b></span><select value={dataSourceId} onChange={(event) => setDataSourceId(event.target.value)} className={controlClass} disabled={busy}><option value="">请选择</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.name} · {source.driver}</option>)}</select></label><label className="grid gap-1.5 text-sm text-slate-700"><span>查询 SQL<b className="ml-1 text-rose-600">*</b></span><textarea value={sql} onChange={(event) => setSql(event.target.value)} spellCheck={false} rows={13} placeholder="SELECT id, name FROM your_table WHERE status = :status" className="w-full rounded-lg border border-slate-200 bg-slate-950 px-4 py-3 font-mono text-sm leading-6 text-slate-100 outline-none transition focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label></div><aside className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><h3 className="font-medium">安全限制</h3><ul className="mt-2 space-y-1 text-xs leading-5"><li>仅单条 SELECT；不支持分号、注释、写入和锁定。</li><li>使用 <code>:参数名</code> 绑定值，禁止拼接输入。</li><li>服务端限制 5 秒和最多 500 行。</li><li>数据源账号必须只读并限制可访问表。</li></ul><label className="mt-5 grid gap-1.5 text-sm text-slate-700"><span>行数</span><input value={maxRows} min={1} max={500} type="number" onChange={(event) => setMaxRows(Math.min(500, Math.max(1, Number(event.target.value) || 1)))} className={controlClass}/></label></aside></div>
      {names.length > 0 && <div className="border-t border-slate-100 px-5 py-4"><h3 className="mb-3 text-sm font-medium text-slate-800">查询参数</h3><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{names.map((name) => <label key={name} className="grid gap-1.5 text-sm text-slate-700"><span><code>:{name}</code><b className="ml-1 text-rose-600">*</b></span><input value={parameters[name] ?? ""} onChange={(event) => setParameters((current) => ({ ...current, [name]: event.target.value }))} placeholder={`请输入 ${name}`} className={controlClass}/></label>)}</div></div>}
      <footer className="flex justify-end gap-2 border-t border-slate-100 px-5 py-3"><button type="button" onClick={reset} disabled={busy} className="h-9 rounded-lg border border-slate-200 px-4 text-sm text-slate-700 hover:bg-slate-50 disabled:opacity-50">重置</button><button type="button" onClick={() => void execute()} disabled={busy || !sql.trim() || !dataSourceId} className="h-9 rounded-lg bg-blue-600 px-5 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50">{busy ? "执行" : "执行"}</button></footer></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-3"><div><h2 className="text-sm font-medium text-slate-800">报表结果</h2><p className="mt-1 text-xs text-slate-500">{result ? `返回 ${result.rows.length} 行 · 耗时 ${result.durationMs} ms${result.truncated ? ` · 已按 ${result.maxRows} 行截断` : ""}` : "执行 SQL 后自动生成列和表格。"}</p></div>{result?.truncated && <span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-medium text-amber-700">已截断</span>}</div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="w-16 px-5 py-3 text-center">#</th>{result?.columns.map((column) => <th key={column} className="px-4 py-3 font-medium">{column}</th>)}</tr></thead><tbody>{result?.rows.length ? result.rows.map((row, index) => <tr key={index} className="border-t border-slate-100 hover:bg-blue-50/40"><td className="px-5 py-3 text-center text-slate-500">{index + 1}</td>{result.columns.map((column) => <td key={column} className="max-w-[360px] truncate px-4 py-3 text-slate-700" title={displayValue(row[column])}>{displayValue(row[column])}</td>)}</tr>) : <tr><td colSpan={Math.max((result?.columns.length ?? 0) + 1, 1)} className="px-5 py-12 text-center text-sm text-slate-400">暂无报表数据</td></tr>}</tbody></table></div></section>
  </div></main>
}