// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  crmBusinessStatusCreateSchema,
  crmBusinessStatusPageQuerySchema,
  crmBusinessStatusUpdateSchema,
} from "../backend/validators/crm-business-status.validator"

export const crmBusinessStatusActionSchemas = {
  "ruoyi.cmd.crm.crmBusinessStatus.page": crmBusinessStatusPageQuerySchema,
  "ruoyi.cmd.crm.crmBusinessStatus.get": z.object({ id: z.string() }),
  "ruoyi.cmd.crm.crmBusinessStatus.create": crmBusinessStatusCreateSchema,
  "ruoyi.cmd.crm.crmBusinessStatus.update": crmBusinessStatusUpdateSchema,
  "ruoyi.cmd.crm.crmBusinessStatus.delete": z.object({ id: z.string() }),
  "crm.pageCrmBusinessStatus": crmBusinessStatusPageQuerySchema,
  "crm.getCrmBusinessStatus": z.object({ id: z.string() }),
  "crm.createCrmBusinessStatus": crmBusinessStatusCreateSchema,
  "crm.updateCrmBusinessStatus": crmBusinessStatusUpdateSchema,
  "crm.deleteCrmBusinessStatus": z.object({ id: z.string() }),
} as const

export const CRM_BUSINESS_STATUS_ACTION_SCHEMAS = crmBusinessStatusActionSchemas

export function registerActionSchemas() {
  return crmBusinessStatusActionSchemas
}
