// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  crmOwnerRecordCreateSchema,
  crmOwnerRecordPageQuerySchema,
  crmOwnerRecordUpdateSchema,
} from "../backend/validators/crm-owner-record.validator"

export const crmOwnerRecordActionSchemas = {
  "ruoyi.cmd.crm.crmOwnerRecord.page": crmOwnerRecordPageQuerySchema,
  "ruoyi.cmd.crm.crmOwnerRecord.get": z.object({ id: z.string() }),
  "ruoyi.cmd.crm.crmOwnerRecord.create": crmOwnerRecordCreateSchema,
  "ruoyi.cmd.crm.crmOwnerRecord.update": crmOwnerRecordUpdateSchema,
  "ruoyi.cmd.crm.crmOwnerRecord.delete": z.object({ id: z.string() }),
  "crm.pageCrmOwnerRecord": crmOwnerRecordPageQuerySchema,
  "crm.getCrmOwnerRecord": z.object({ id: z.string() }),
  "crm.createCrmOwnerRecord": crmOwnerRecordCreateSchema,
  "crm.updateCrmOwnerRecord": crmOwnerRecordUpdateSchema,
  "crm.deleteCrmOwnerRecord": z.object({ id: z.string() }),
} as const

export const CRM_OWNER_RECORD_ACTION_SCHEMAS = crmOwnerRecordActionSchemas

export function registerActionSchemas() {
  return crmOwnerRecordActionSchemas
}
