// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { CrmClueRepository } from "../repositories/crm-clue.repository"
import type {
  CrmClueCreateDTO,
  CrmCluePageQuery,
  CrmClueUpdateDTO,
} from "../types/crm-clue.types"

export class CrmClueService {
  static async page(query: CrmCluePageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return CrmClueRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return CrmClueRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: CrmClueCreateDTO, actorId?: string, tenantId?: string) {
    const row = await CrmClueRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("crm.crmClue.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: CrmClueUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await CrmClueRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("crm.crmClue.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await CrmClueRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("crm.crmClue.deleted", { id, actorId })
    }
    return ok
  }
}

export const crmClueService = CrmClueService
