// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { CrmCustomerRepository } from "../repositories/crm-customer.repository"
import type {
  CrmCustomerCreateDTO,
  CrmCustomerPageQuery,
  CrmCustomerUpdateDTO,
} from "../types/crm-customer.types"

export class CrmCustomerService {
  static async page(query: CrmCustomerPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return CrmCustomerRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return CrmCustomerRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: CrmCustomerCreateDTO, actorId?: string, tenantId?: string) {
    const row = await CrmCustomerRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("crm.crmCustomer.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: CrmCustomerUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await CrmCustomerRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("crm.crmCustomer.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await CrmCustomerRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("crm.crmCustomer.deleted", { id, actorId })
    }
    return ok
  }
}

export const crmCustomerService = CrmCustomerService
