// Auto-generated by Codegen Engine
import { z } from "zod"



export const mpAccountPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mpAccountCreateSchema = z.object({
  name: z.string().trim().optional(),
  account: z.string().trim().optional(),
  app_id: z.string().trim().optional(),
  app_secret: z.string().trim().optional(),
  token: z.string().trim().optional(),
  aes_key: z.string().trim().optional(),
  qr_code_url: z.string().trim().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mpAccountUpdateSchema = mpAccountCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MpAccountPageQueryInput = z.infer<typeof mpAccountPageQuerySchema>
export type MpAccountCreateInput = z.infer<typeof mpAccountCreateSchema>
export type MpAccountUpdateInput = z.infer<typeof mpAccountUpdateSchema>
