// Auto-generated by Codegen Engine
import { z } from "zod"



export const mpTagPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mpTagCreateSchema = z.object({
  tag_id: z.coerce.number().finite().optional(),
  name: z.string().trim().optional(),
  count: z.coerce.number().finite().optional(),
  account_id: z.coerce.number().finite().optional(),
  app_id: z.string().trim().optional(),

}).strict()

export const mpTagUpdateSchema = mpTagCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MpTagPageQueryInput = z.infer<typeof mpTagPageQuerySchema>
export type MpTagCreateInput = z.infer<typeof mpTagCreateSchema>
export type MpTagUpdateInput = z.infer<typeof mpTagUpdateSchema>
