// Auto-generated by Codegen Engine
import { z } from "zod"



export const mpUserPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mpUserCreateSchema = z.object({
  openid: z.string().trim().optional(),
  union_id: z.string().trim().optional(),
  subscribe_status: z.coerce.number().finite().optional(),
  subscribe_time: z.string().trim().optional(),
  unsubscribe_time: z.string().trim().optional(),
  nickname: z.string().trim().optional(),
  head_image_url: z.string().trim().optional(),
  language: z.string().trim().optional(),
  country: z.string().trim().optional(),
  province: z.string().trim().optional(),
  city: z.string().trim().optional(),
  remark: z.string().trim().optional(),
  tag_ids: z.string().trim().optional(),
  account_id: z.coerce.number().finite().optional(),
  app_id: z.string().trim().optional(),

}).strict()

export const mpUserUpdateSchema = mpUserCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MpUserPageQueryInput = z.infer<typeof mpUserPageQuerySchema>
export type MpUserCreateInput = z.infer<typeof mpUserCreateSchema>
export type MpUserUpdateInput = z.infer<typeof mpUserUpdateSchema>
