// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { AiModelService } from "../ai-model.service"

describe("AiModelService", () => {
  it("should create and query AI 模型 DO默认模型： 为开启，并且 排序第一", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await AiModelService.create({
        name: "测试AI 模型 DO默认模型： 为开启，并且 排序第一",
        sort: 1,
        status: "测试AI 模型 DO默认模型： 为开启，并且 排序第一",
        model_key: "测试AI 模型 DO默认模型： 为开启，并且 排序第一",
        input_ratio: "测试AI 模型 DO默认模型： 为开启，并且 排序第一",
        output_ratio: "测试AI 模型 DO默认模型： 为开启，并且 排序第一",
        provider: "测试AI 模型 DO默认模型： 为开启，并且 排序第一",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await AiModelService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await AiModelService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await AiModelService.update(created.id, {
        id: created.id,
          key_id: "测试更新AI 模型 DO默认模型： 为开启，并且 排序第一",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await AiModelService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
