// Auto-generated by Codegen Engine (App Router Page)
import { MesCalTeamListPage } from "@/modules/mes/frontend/pages/mes-cal-team-list.page"

export default function Page() {
  return <MesCalTeamListPage />
}
