// Auto-generated by Codegen Engine (App Router Page)
import { MesWmReturnIssueListPage } from "@/modules/mes/frontend/pages/mes-wm-return-issue-list.page"

export default function Page() {
  return <MesWmReturnIssueListPage />
}
