// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { MesProFeedbackService } from "./mes-pro-feedback.service"
import { registerActionSchemas } from "../contract/mes-pro-feedback.actions"
import type {
  MesProFeedbackCreateDTO,
  MesProFeedbackPageQuery,
  MesProFeedbackUpdateDTO,
} from "../types/mes-pro-feedback.types"

export class MesProFeedbackRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mes.mesProFeedback.page", async (req) => {
      const query = req.data as MesProFeedbackPageQuery
      return MesProFeedbackService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesProFeedback.get", async (req) => {
      const { id } = req.data as { id: string }
      return MesProFeedbackService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesProFeedback.create", async (req) => {
      const data = req.data as MesProFeedbackCreateDTO
      return MesProFeedbackService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesProFeedback.update", async (req) => {
      const { id, ...rest } = req.data as MesProFeedbackUpdateDTO
      return MesProFeedbackService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesProFeedback.delete", async (req) => {
      const { id } = req.data as { id: string }
      return MesProFeedbackService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const mesProFeedbackRpc = MesProFeedbackRpc

export const mesProFeedbackDomainFacade = createDomainFacade({
  domain: "mes",
  serviceBus,
})
