// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MesQcTemplateRepository } from "../repositories/mes-qc-template.repository"
import type {
  MesQcTemplateCreateDTO,
  MesQcTemplatePageQuery,
  MesQcTemplateUpdateDTO,
} from "../types/mes-qc-template.types"

export class MesQcTemplateService {
  static async page(query: MesQcTemplatePageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MesQcTemplateRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MesQcTemplateRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MesQcTemplateCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MesQcTemplateRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesQcTemplate.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MesQcTemplateUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MesQcTemplateRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesQcTemplate.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MesQcTemplateRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mes.mesQcTemplate.deleted", { id, actorId })
    }
    return ok
  }
}

export const mesQcTemplateService = MesQcTemplateService
