// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MesCalPlanTeamRepository } from "../repositories/mes-cal-plan-team.repository"
import type {
  MesCalPlanTeamCreateDTO,
  MesCalPlanTeamPageQuery,
  MesCalPlanTeamUpdateDTO,
} from "../types/mes-cal-plan-team.types"

export class MesCalPlanTeamService {
  static async page(query: MesCalPlanTeamPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MesCalPlanTeamRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MesCalPlanTeamRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MesCalPlanTeamCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MesCalPlanTeamRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesCalPlanTeam.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MesCalPlanTeamUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MesCalPlanTeamRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesCalPlanTeam.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MesCalPlanTeamRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mes.mesCalPlanTeam.deleted", { id, actorId })
    }
    return ok
  }
}

export const mesCalPlanTeamService = MesCalPlanTeamService
