// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MesWmPackageRepository } from "../repositories/mes-wm-package.repository"
import type {
  MesWmPackageCreateDTO,
  MesWmPackagePageQuery,
  MesWmPackageUpdateDTO,
} from "../types/mes-wm-package.types"

export class MesWmPackageService {
  static async page(query: MesWmPackagePageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MesWmPackageRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MesWmPackageRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MesWmPackageCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MesWmPackageRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesWmPackage.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MesWmPackageUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MesWmPackageRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesWmPackage.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MesWmPackageRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mes.mesWmPackage.deleted", { id, actorId })
    }
    return ok
  }
}

export const mesWmPackageService = MesWmPackageService
