// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { MesDvCheckPlanSubjectService } from "./mes-dv-check-plan-subject.service"
import { registerActionSchemas } from "../contract/mes-dv-check-plan-subject.actions"
import type {
  MesDvCheckPlanSubjectCreateDTO,
  MesDvCheckPlanSubjectPageQuery,
  MesDvCheckPlanSubjectUpdateDTO,
} from "../types/mes-dv-check-plan-subject.types"

export class MesDvCheckPlanSubjectRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvCheckPlanSubject.page", async (req) => {
      const query = req.data as MesDvCheckPlanSubjectPageQuery
      return MesDvCheckPlanSubjectService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvCheckPlanSubject.get", async (req) => {
      const { id } = req.data as { id: string }
      return MesDvCheckPlanSubjectService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvCheckPlanSubject.create", async (req) => {
      const data = req.data as MesDvCheckPlanSubjectCreateDTO
      return MesDvCheckPlanSubjectService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvCheckPlanSubject.update", async (req) => {
      const { id, ...rest } = req.data as MesDvCheckPlanSubjectUpdateDTO
      return MesDvCheckPlanSubjectService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvCheckPlanSubject.delete", async (req) => {
      const { id } = req.data as { id: string }
      return MesDvCheckPlanSubjectService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const mesDvCheckPlanSubjectRpc = MesDvCheckPlanSubjectRpc

export const mesDvCheckPlanSubjectDomainFacade = createDomainFacade({
  domain: "mes",
  serviceBus,
})
