// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MesProRouteProductBomRepository } from "../repositories/mes-pro-route-product-bom.repository"
import type {
  MesProRouteProductBomCreateDTO,
  MesProRouteProductBomPageQuery,
  MesProRouteProductBomUpdateDTO,
} from "../types/mes-pro-route-product-bom.types"

export class MesProRouteProductBomService {
  static async page(query: MesProRouteProductBomPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MesProRouteProductBomRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MesProRouteProductBomRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MesProRouteProductBomCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MesProRouteProductBomRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesProRouteProductBom.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MesProRouteProductBomUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MesProRouteProductBomRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesProRouteProductBom.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MesProRouteProductBomRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mes.mesProRouteProductBom.deleted", { id, actorId })
    }
    return ok
  }
}

export const mesProRouteProductBomService = MesProRouteProductBomService
