// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { MesWmReturnSalesLineService } from "./mes-wm-return-sales-line.service"
import { registerActionSchemas } from "../contract/mes-wm-return-sales-line.actions"
import type {
  MesWmReturnSalesLineCreateDTO,
  MesWmReturnSalesLinePageQuery,
  MesWmReturnSalesLineUpdateDTO,
} from "../types/mes-wm-return-sales-line.types"

export class MesWmReturnSalesLineRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnSalesLine.page", async (req) => {
      const query = req.data as MesWmReturnSalesLinePageQuery
      return MesWmReturnSalesLineService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnSalesLine.get", async (req) => {
      const { id } = req.data as { id: string }
      return MesWmReturnSalesLineService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnSalesLine.create", async (req) => {
      const data = req.data as MesWmReturnSalesLineCreateDTO
      return MesWmReturnSalesLineService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnSalesLine.update", async (req) => {
      const { id, ...rest } = req.data as MesWmReturnSalesLineUpdateDTO
      return MesWmReturnSalesLineService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnSalesLine.delete", async (req) => {
      const { id } = req.data as { id: string }
      return MesWmReturnSalesLineService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const mesWmReturnSalesLineRpc = MesWmReturnSalesLineRpc

export const mesWmReturnSalesLineDomainFacade = createDomainFacade({
  domain: "mes",
  serviceBus,
})
