// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { MesWmReturnIssueService } from "./mes-wm-return-issue.service"
import { registerActionSchemas } from "../contract/mes-wm-return-issue.actions"
import type {
  MesWmReturnIssueCreateDTO,
  MesWmReturnIssuePageQuery,
  MesWmReturnIssueUpdateDTO,
} from "../types/mes-wm-return-issue.types"

export class MesWmReturnIssueRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnIssue.page", async (req) => {
      const query = req.data as MesWmReturnIssuePageQuery
      return MesWmReturnIssueService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnIssue.get", async (req) => {
      const { id } = req.data as { id: string }
      return MesWmReturnIssueService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnIssue.create", async (req) => {
      const data = req.data as MesWmReturnIssueCreateDTO
      return MesWmReturnIssueService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnIssue.update", async (req) => {
      const { id, ...rest } = req.data as MesWmReturnIssueUpdateDTO
      return MesWmReturnIssueService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesWmReturnIssue.delete", async (req) => {
      const { id } = req.data as { id: string }
      return MesWmReturnIssueService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const mesWmReturnIssueRpc = MesWmReturnIssueRpc

export const mesWmReturnIssueDomainFacade = createDomainFacade({
  domain: "mes",
  serviceBus,
})
