// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MesDvCheckPlanRepository } from "../repositories/mes-dv-check-plan.repository"
import type {
  MesDvCheckPlanCreateDTO,
  MesDvCheckPlanPageQuery,
  MesDvCheckPlanUpdateDTO,
} from "../types/mes-dv-check-plan.types"

export class MesDvCheckPlanService {
  static async page(query: MesDvCheckPlanPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MesDvCheckPlanRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MesDvCheckPlanRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MesDvCheckPlanCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MesDvCheckPlanRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesDvCheckPlan.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MesDvCheckPlanUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MesDvCheckPlanRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesDvCheckPlan.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MesDvCheckPlanRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mes.mesDvCheckPlan.deleted", { id, actorId })
    }
    return ok
  }
}

export const mesDvCheckPlanService = MesDvCheckPlanService
