// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MesProWorkRecordLogRepository } from "../repositories/mes-pro-work-record-log.repository"
import type {
  MesProWorkRecordLogCreateDTO,
  MesProWorkRecordLogPageQuery,
  MesProWorkRecordLogUpdateDTO,
} from "../types/mes-pro-work-record-log.types"

export class MesProWorkRecordLogService {
  static async page(query: MesProWorkRecordLogPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MesProWorkRecordLogRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MesProWorkRecordLogRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MesProWorkRecordLogCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MesProWorkRecordLogRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesProWorkRecordLog.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MesProWorkRecordLogUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MesProWorkRecordLogRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesProWorkRecordLog.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MesProWorkRecordLogRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mes.mesProWorkRecordLog.deleted", { id, actorId })
    }
    return ok
  }
}

export const mesProWorkRecordLogService = MesProWorkRecordLogService
