// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { MesDvMaintenRecordLineService } from "./mes-dv-mainten-record-line.service"
import { registerActionSchemas } from "../contract/mes-dv-mainten-record-line.actions"
import type {
  MesDvMaintenRecordLineCreateDTO,
  MesDvMaintenRecordLinePageQuery,
  MesDvMaintenRecordLineUpdateDTO,
} from "../types/mes-dv-mainten-record-line.types"

export class MesDvMaintenRecordLineRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvMaintenRecordLine.page", async (req) => {
      const query = req.data as MesDvMaintenRecordLinePageQuery
      return MesDvMaintenRecordLineService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvMaintenRecordLine.get", async (req) => {
      const { id } = req.data as { id: string }
      return MesDvMaintenRecordLineService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvMaintenRecordLine.create", async (req) => {
      const data = req.data as MesDvMaintenRecordLineCreateDTO
      return MesDvMaintenRecordLineService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvMaintenRecordLine.update", async (req) => {
      const { id, ...rest } = req.data as MesDvMaintenRecordLineUpdateDTO
      return MesDvMaintenRecordLineService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mes.mesDvMaintenRecordLine.delete", async (req) => {
      const { id } = req.data as { id: string }
      return MesDvMaintenRecordLineService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const mesDvMaintenRecordLineRpc = MesDvMaintenRecordLineRpc

export const mesDvMaintenRecordLineDomainFacade = createDomainFacade({
  domain: "mes",
  serviceBus,
})
