// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MesDvMaintenRecordRepository } from "../repositories/mes-dv-mainten-record.repository"
import type {
  MesDvMaintenRecordCreateDTO,
  MesDvMaintenRecordPageQuery,
  MesDvMaintenRecordUpdateDTO,
} from "../types/mes-dv-mainten-record.types"

export class MesDvMaintenRecordService {
  static async page(query: MesDvMaintenRecordPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MesDvMaintenRecordRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MesDvMaintenRecordRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MesDvMaintenRecordCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MesDvMaintenRecordRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesDvMaintenRecord.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MesDvMaintenRecordUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MesDvMaintenRecordRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mes.mesDvMaintenRecord.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MesDvMaintenRecordRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mes.mesDvMaintenRecord.deleted", { id, actorId })
    }
    return ok
  }
}

export const mesDvMaintenRecordService = MesDvMaintenRecordService
