// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { ErpFinanceReceiptService } from "../erp-finance-receipt.service"

describe("ErpFinanceReceiptService", () => {
  it("should create and query ERP 收款单", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await ErpFinanceReceiptService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await ErpFinanceReceiptService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await ErpFinanceReceiptService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await ErpFinanceReceiptService.update(created.id, {
        id: created.id,
          no: "测试更新ERP 收款单",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await ErpFinanceReceiptService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
