// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { ErpFinanceReceiptItemService } from "../erp-finance-receipt-item.service"

describe("ErpFinanceReceiptItemService", () => {
  it("should create and query ERP 收款项", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await ErpFinanceReceiptItemService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await ErpFinanceReceiptItemService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await ErpFinanceReceiptItemService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await ErpFinanceReceiptItemService.update(created.id, {
        id: created.id,
          receipt_id: "测试更新ERP 收款项",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await ErpFinanceReceiptItemService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
