// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { ImPrivateMessageRepository } from "../repositories/im-private-message.repository"
import type {
  ImPrivateMessageCreateDTO,
  ImPrivateMessagePageQuery,
  ImPrivateMessageUpdateDTO,
} from "../types/im-private-message.types"

export class ImPrivateMessageService {
  static async page(query: ImPrivateMessagePageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return ImPrivateMessageRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return ImPrivateMessageRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: ImPrivateMessageCreateDTO, actorId?: string, tenantId?: string) {
    const row = await ImPrivateMessageRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("im.imPrivateMessage.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: ImPrivateMessageUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await ImPrivateMessageRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("im.imPrivateMessage.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await ImPrivateMessageRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("im.imPrivateMessage.deleted", { id, actorId })
    }
    return ok
  }
}

export const imPrivateMessageService = ImPrivateMessageService
