// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  BpmFormCreateDTO,
  BpmFormPageQuery,
  BpmFormUpdateDTO,
  BpmFormVO,
} from "@/modules/bpm/backend/types/bpm-form.types"

const BASE_URL = "/api/v1/admin/bpm/bpm-form"

export const BpmFormApi = {
  async page(params?: BpmFormPageQuery) {
    return request.get<{ items: BpmFormVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<BpmFormVO>(`${BASE_URL}/${id}`)
  },

  async create(data: BpmFormCreateDTO) {
    return request.post<BpmFormVO>(BASE_URL, data)
  },

  async update(data: BpmFormUpdateDTO) {
    return request.put<BpmFormVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: BpmFormPageQuery) {
    return request.post<BpmFormVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
