// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  BpmCategoryCreateDTO,
  BpmCategoryPageQuery,
  BpmCategoryUpdateDTO,
  BpmCategoryVO,
} from "@/modules/bpm/backend/types/bpm-category.types"

const BASE_URL = "/api/v1/admin/bpm/bpm-category"

export const BpmCategoryApi = {
  async page(params?: BpmCategoryPageQuery) {
    return request.get<{ items: BpmCategoryVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<BpmCategoryVO>(`${BASE_URL}/${id}`)
  },

  async create(data: BpmCategoryCreateDTO) {
    return request.post<BpmCategoryVO>(BASE_URL, data)
  },

  async update(data: BpmCategoryUpdateDTO) {
    return request.put<BpmCategoryVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: BpmCategoryPageQuery) {
    return request.post<BpmCategoryVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
