// Auto-generated by Codegen Engine
export interface MemberLevelRecordDO {
  id: number
  user_id?: number
  level_id?: number
  level?: number
  discount_percent?: number
  experience?: number
  user_experience?: number
  remark?: string
  description?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MemberLevelRecordVO {
  id: number
  user_id?: number
  level_id?: number
  level?: number
  discount_percent?: number
  experience?: number
  user_experience?: number
  remark?: string
  description?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MemberLevelRecordCreateDTO {
  user_id?: number
  level_id?: number
  level?: number
  discount_percent?: number
  experience?: number
  user_experience?: number
  remark?: string
  description?: string
}

export interface MemberLevelRecordUpdateDTO extends Partial<MemberLevelRecordCreateDTO> {
  id: string
}

export interface MemberLevelRecordPageQuery {
  page?: number
  pageSize?: number

}
