// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  WmsInventoryCreateDTO,
  WmsInventoryPageQuery,
  WmsInventoryUpdateDTO,
  WmsInventoryVO,
} from "@/modules/wms/backend/types/wms-inventory.types"

const BASE_URL = "/api/v1/admin/wms/wms-inventory"

export const WmsInventoryApi = {
  async page(params?: WmsInventoryPageQuery) {
    return request.get<{ items: WmsInventoryVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<WmsInventoryVO>(`${BASE_URL}/${id}`)
  },

  async create(data: WmsInventoryCreateDTO) {
    return request.post<WmsInventoryVO>(BASE_URL, data)
  },

  async update(data: WmsInventoryUpdateDTO) {
    return request.put<WmsInventoryVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: WmsInventoryPageQuery) {
    return request.post<WmsInventoryVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
