// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  combinationActivityCreateSchema,
  combinationActivityPageQuerySchema,
  combinationActivityUpdateSchema,
} from "../backend/validators/combination-activity.validator"

export const combinationActivityActionSchemas = {
  "ruoyi.cmd.mall.combinationActivity.page": combinationActivityPageQuerySchema,
  "ruoyi.cmd.mall.combinationActivity.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mall.combinationActivity.create": combinationActivityCreateSchema,
  "ruoyi.cmd.mall.combinationActivity.update": combinationActivityUpdateSchema,
  "ruoyi.cmd.mall.combinationActivity.delete": z.object({ id: z.string() }),
  "mall.pageCombinationActivity": combinationActivityPageQuerySchema,
  "mall.getCombinationActivity": z.object({ id: z.string() }),
  "mall.createCombinationActivity": combinationActivityCreateSchema,
  "mall.updateCombinationActivity": combinationActivityUpdateSchema,
  "mall.deleteCombinationActivity": z.object({ id: z.string() }),
} as const

export const COMBINATION_ACTIVITY_ACTION_SCHEMAS = combinationActivityActionSchemas

export function registerActionSchemas() {
  return combinationActivityActionSchemas
}
