// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  productPropertyValueCreateSchema,
  productPropertyValuePageQuerySchema,
  productPropertyValueUpdateSchema,
} from "../backend/validators/product-property-value.validator"

export const productPropertyValueActionSchemas = {
  "ruoyi.cmd.mall.productPropertyValue.page": productPropertyValuePageQuerySchema,
  "ruoyi.cmd.mall.productPropertyValue.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mall.productPropertyValue.create": productPropertyValueCreateSchema,
  "ruoyi.cmd.mall.productPropertyValue.update": productPropertyValueUpdateSchema,
  "ruoyi.cmd.mall.productPropertyValue.delete": z.object({ id: z.string() }),
  "mall.pageProductPropertyValue": productPropertyValuePageQuerySchema,
  "mall.getProductPropertyValue": z.object({ id: z.string() }),
  "mall.createProductPropertyValue": productPropertyValueCreateSchema,
  "mall.updateProductPropertyValue": productPropertyValueUpdateSchema,
  "mall.deleteProductPropertyValue": z.object({ id: z.string() }),
} as const

export const PRODUCT_PROPERTY_VALUE_ACTION_SCHEMAS = productPropertyValueActionSchemas

export function registerActionSchemas() {
  return productPropertyValueActionSchemas
}
