// Auto-generated by Codegen Engine (Action Route: export)
import { NextResponse } from "next/server"
import { withAdminRoute } from "@/modules/shared/backend/http/admin-route"
import { AigwPartnerService } from "@/modules/aigw/backend/services/aigw-partner.service"

export const POST = withAdminRoute(async (_request, auth) => {
  const result = await AigwPartnerService.page({ page: 1, pageSize: 1000 }, auth.userId, auth.tenantId)
  return NextResponse.json({ success: true, data: result.items ?? result })
})
