// Auto-generated by Codegen Engine
import { z } from "zod"



export const aiKnowledgePageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const aiKnowledgeCreateSchema = z.object({
  name: z.string().trim().optional(),
  description: z.string().trim().optional(),
  embedding_model_id: z.coerce.number().finite().optional(),
  embedding_model: z.string().trim().optional(),
  top_k: z.coerce.number().finite().optional(),
  similarity_threshold: z.coerce.number().finite().optional(),
  status: z.coerce.number().finite().optional(),

}).strict()

export const aiKnowledgeUpdateSchema = aiKnowledgeCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type AiKnowledgePageQueryInput = z.infer<typeof aiKnowledgePageQuerySchema>
export type AiKnowledgeCreateInput = z.infer<typeof aiKnowledgeCreateSchema>
export type AiKnowledgeUpdateInput = z.infer<typeof aiKnowledgeUpdateSchema>
