// Auto-generated by Codegen Engine
import { z } from "zod"



export const aiMindMapPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const aiMindMapCreateSchema = z.object({
  user_id: z.coerce.number().finite().optional(),
  platform: z.string().trim().optional(),
  model_id: z.coerce.number().finite().optional(),
  model: z.string().trim().optional(),
  prompt: z.string().trim().optional(),
  generated_content: z.string().trim().optional(),
  error_message: z.string().trim().optional(),

}).strict()

export const aiMindMapUpdateSchema = aiMindMapCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type AiMindMapPageQueryInput = z.infer<typeof aiMindMapPageQuerySchema>
export type AiMindMapCreateInput = z.infer<typeof aiMindMapCreateSchema>
export type AiMindMapUpdateInput = z.infer<typeof aiMindMapUpdateSchema>
