// Auto-generated by Codegen Engine
import { z } from "zod"



export const aiModelPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const aiModelCreateSchema = z.object({
  key_id: z.coerce.number().finite().optional(),
  name: z.string().trim().optional(),
  model: z.string().trim().optional(),
  platform: z.string().trim().optional(),
  type: z.coerce.number().finite().optional(),
  sort: z.coerce.number().finite().optional(),
  status: z.coerce.number().finite().optional(),
  temperature: z.coerce.number().finite().optional(),
  max_tokens: z.coerce.number().finite().optional(),
  max_contexts: z.coerce.number().finite().optional(),

}).strict()

export const aiModelUpdateSchema = aiModelCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type AiModelPageQueryInput = z.infer<typeof aiModelPageQuerySchema>
export type AiModelCreateInput = z.infer<typeof aiModelCreateSchema>
export type AiModelUpdateInput = z.infer<typeof aiModelUpdateSchema>
