// Auto-generated by Codegen Engine (App Router Page)
import { CrmContractListPage } from "@/modules/crm/frontend/pages/crm-contract-list.page"

export default function Page() {
  return <CrmContractListPage />
}
