// Auto-generated by Codegen Engine
"use client"

import React, { useState, useEffect, useCallback } from "react"
import { IotOtaTaskApi } from "../api/iot-ota-task.api"
import { IotOtaTaskForm } from "../components/IotOtaTaskForm"
import { Pagination } from "@/modules/shared/frontend/components/pagination"
import type { IotOtaTaskVO, IotOtaTaskPageQuery } from "@/modules/iot/backend/types/iot-ota-task.types"

export function IotOtaTaskListPage() {
    const [data, setData] = useState<IotOtaTaskVO[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)
  const [loading, setLoading] = useState(false)
  const [searchForm, setSearchForm] = useState<Record<string, any>>({})
  const [formOpen, setFormOpen] = useState(false)
  const [editItem, setEditItem] = useState<IotOtaTaskVO | null>(null)

  const fetchData = useCallback(async () => {
    setLoading(true)
    try {
      const res = await IotOtaTaskApi.page({ page, pageSize, ...searchForm })
      setData(res.items || [])
      setTotal(res.total || 0)
    } catch (err) {
      console.error("加载数据失败:", err)
    } finally {
      setLoading(false)
    }
  }, [page, pageSize, searchForm])

  useEffect(() => {
    fetchData()
  }, [fetchData])

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    setPage(1)
    fetchData()
  }

  const handleReset = () => {
    setSearchForm({})
    setPage(1)
  }

  const handleAdd = () => {
    setEditItem(null)
    setFormOpen(true)
  }

  const handleEdit = (item: IotOtaTaskVO) => {
    setEditItem(item)
    setFormOpen(true)
  }

  const handleDelete = async (id: string) => {
    if (!window.confirm("确定要删除该记录吗？")) return
    try {
      await IotOtaTaskApi.delete(id)
      fetchData()
    } catch (err: any) {
      alert(err?.message || "删除失败")
    }
  }

  // Agent-Native: 根节点暴露就绪信号；弹窗打开时基底打 inert，让无障碍树只留弹窗一层
  const agentState = loading ? "loading" : formOpen ? "modal-open" : total === 0 ? "empty" : "ready"

  return (
    <div
      data-agent-scope="iot-ota-task"
      data-agent-state={agentState}
      data-agent-page-ready={String(!loading)}
      className="p-6 space-y-4"
    >
      {/* 弹窗打开时基底内容 inert —— Agent 不会误点到被遮挡的元素 */}
      <div inert={formOpen ? true : undefined} className="space-y-4">
      {/* 页面头部 */}
      <div className="flex items-center justify-between">
        <div>
          <h1 data-testid="iot-ota-task-title" className="text-xl font-bold tracking-tight text-slate-900">IoT OTA 升级任务管理</h1>
          <p className="text-xs text-slate-500 mt-0.5">IoT OTA 升级任务列表与配置管理</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={fetchData}
            data-testid="iot-ota-task-refresh"
            data-agent-target="iot-ota-task:refresh"
            className="px-3 py-1.5 text-xs text-slate-600 bg-white border border-slate-300 rounded-lg hover:bg-slate-50 transition-colors"
          >
            刷新
          </button>
          <button
            onClick={handleAdd}
            data-testid="iot-ota-task-create"
            data-agent-target="iot-ota-task:create"
            className="px-3.5 py-1.5 text-xs text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors font-medium shadow-xs"
          >
            + 新增IoT OTA 升级任务
          </button>
        </div>
      </div>

      {/* 搜索工具栏 */}
      <form
        onSubmit={handleSearch}
        data-testid="iot-ota-task-search"
        data-agent-scope="iot-ota-task:search"
        aria-label="IoT OTA 升级任务搜索"
        className="p-3.5 bg-white rounded-xl border border-slate-200 shadow-xs flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-3">
        <div className="flex items-center gap-1.5">
          <label htmlFor="iot-ota-task-search-name" className="text-xs text-slate-500 whitespace-nowrap">任务名称:</label>
          <input
            type="text"
            id="iot-ota-task-search-name"
            data-testid="search-name"
            data-agent-target="iot-ota-task:field:name"
            data-agent-state={searchForm.name ? "filled" : "empty"}
            aria-label="任务名称"
            value={searchForm.name ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, name: e.target.value }))}
            placeholder="搜索任务名称"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
        <div className="flex items-center gap-1.5">
          <label htmlFor="iot-ota-task-search-firmware_id" className="text-xs text-slate-500 whitespace-nowrap">固件编号:</label>
          <input
            type="text"
            id="iot-ota-task-search-firmware_id"
            data-testid="search-firmware_id"
            data-agent-target="iot-ota-task:field:firmware_id"
            data-agent-state={searchForm.firmware_id ? "filled" : "empty"}
            aria-label="固件编号"
            value={searchForm.firmware_id ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, firmware_id: e.target.value }))}
            placeholder="搜索固件编号"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
        <div className="flex items-center gap-1.5">
          <label htmlFor="iot-ota-task-search-status" className="text-xs text-slate-500 whitespace-nowrap">任务状态:</label>
          <input
            type="text"
            id="iot-ota-task-search-status"
            data-testid="search-status"
            data-agent-target="iot-ota-task:field:status"
            data-agent-state={searchForm.status ? "filled" : "empty"}
            aria-label="任务状态"
            value={searchForm.status ?? ""}
            onChange={(e) => setSearchForm((prev) => ({ ...prev, status: e.target.value }))}
            placeholder="搜索任务状态"
            className="w-36 px-2.5 py-1 text-xs border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500"
          />
        </div>
          <button type="submit" data-testid="iot-ota-task-search-submit" data-agent-target="iot-ota-task:search" className="px-3 py-1 text-xs text-white bg-slate-900 rounded-lg hover:bg-slate-800 transition-colors">查询</button>
          <button type="button" onClick={handleReset} data-testid="iot-ota-task-search-reset" data-agent-target="iot-ota-task:reset" className="px-3 py-1 text-xs text-slate-600 bg-slate-100 rounded-lg hover:bg-slate-200 transition-colors">重置</button>
        </div>
        <div className="text-xs text-slate-500">共 <span data-testid="iot-ota-task-total" className="font-semibold text-slate-700">{total}</span> 条记录</div>
      </form>

      {/* 数据表格 */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="overflow-x-auto">
          <table data-testid="iot-ota-task-table" aria-label="IoT OTA 升级任务列表" className="min-w-full divide-y divide-slate-200">
            <thead className="bg-slate-50/80">
              <tr>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">任务名称</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">任务描述</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">固件编号</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">任务状态</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">设备升级范围</th>
                <th className="px-4 py-2.5 text-left text-[11px] font-semibold text-slate-500 uppercase tracking-wider">设备总数数量</th>
                <th className="px-4 py-2.5 text-right text-[11px] font-semibold text-slate-500 uppercase tracking-wider min-w-[140px]">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 bg-white">
              {loading ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center text-xs text-slate-400">加载中...</td>
                </tr>
              ) : data.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center text-xs text-slate-400">暂无数据</td>
                </tr>
              ) : (
                data.map((item) => (
                  <tr
                    key={item.id}
                    data-testid="iot-ota-task-row"
                    data-agent-target="iot-ota-task:row"
                    data-agent-state={editItem?.id === item.id ? "editing" : "idle"}
                    data-agent-id={item.id}
                    className="hover:bg-slate-50/60 transition-colors"
                  >
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.name ?? "-")}>{String(item.name ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.description ?? "-")}>{String(item.description ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.firmware_id ?? "-")}>{String(item.firmware_id ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.status ?? "-")}>{String(item.status ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.device_scope ?? "-")}>{String(item.device_scope ?? "-")}</td>
                  <td className="px-4 py-2.5 text-xs text-slate-700 max-w-[200px] truncate" title={String(item.device_total_count ?? "-")}>{String(item.device_total_count ?? "-")}</td>
                    <td className="px-4 py-2.5 text-xs text-right whitespace-nowrap space-x-2">
                      <button onClick={() => handleEdit(item)} data-testid="iot-ota-task-edit" data-agent-target="iot-ota-task:edit" data-agent-id={item.id} aria-label={"编辑 " + item.id} className="text-blue-600 hover:text-blue-800 font-medium">编辑</button>
                      <button onClick={() => handleDelete(item.id)} data-testid="iot-ota-task-delete" data-agent-target="iot-ota-task:delete" data-agent-id={item.id} aria-label={"删除 " + item.id} className="text-rose-600 hover:text-rose-800 font-medium">删除</button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {/* 分页组件 */}
        <div data-agent-target="iot-ota-task:pagination" className="p-3 border-t border-slate-200">
          <Pagination
            total={total}
            page={page}
            pageSize={pageSize}
            onPageChange={(p) => setPage(p)}
            onPageSizeChange={(ps) => setPageSize(ps)}
          />
        </div>
      </div>

      </div>

      {/* 弹窗表单 */}
      <IotOtaTaskForm
        open={formOpen}
        initialData={editItem}
        onClose={() => setFormOpen(false)}
        onSuccess={fetchData}
      />
    </div>
  )
}
