// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MesWmMiscReceiptDetailService } from "../mes-wm-misc-receipt-detail.service"

describe("MesWmMiscReceiptDetailService", () => {
  it("should create and query MES 杂项入库明细", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MesWmMiscReceiptDetailService.create({
        receipt_id: 1,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MesWmMiscReceiptDetailService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MesWmMiscReceiptDetailService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MesWmMiscReceiptDetailService.update(created.id, {
        id: created.id,
        receipt_id: "更新MES 杂项入库明细",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MesWmMiscReceiptDetailService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
