// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MesDvCheckRecordService } from "../mes-dv-check-record.service"

describe("MesDvCheckRecordService", () => {
  it("should create and query MES 设备点检记录", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MesDvCheckRecordService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MesDvCheckRecordService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MesDvCheckRecordService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MesDvCheckRecordService.update(created.id, {
        id: created.id,
          plan_id: "测试更新MES 设备点检记录",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MesDvCheckRecordService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
