// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MesWmProductSalesService } from "../mes-wm-product-sales.service"

describe("MesWmProductSalesService", () => {
  it("should create and query MES 销售出库单", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MesWmProductSalesService.create({
        code: "测试MES 销售出库单",
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MesWmProductSalesService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MesWmProductSalesService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MesWmProductSalesService.update(created.id, {
        id: created.id,
        code: "更新MES 销售出库单",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MesWmProductSalesService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
