// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MesWmTransferService } from "../mes-wm-transfer.service"

describe("MesWmTransferService", () => {
  it("should create and query MES 转移单", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MesWmTransferService.create({
        code: "测试MES 转移单",
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MesWmTransferService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MesWmTransferService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MesWmTransferService.update(created.id, {
        id: created.id,
        code: "更新MES 转移单",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MesWmTransferService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
