// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MesProTaskService } from "../mes-pro-task.service"

describe("MesProTaskService", () => {
  it("should create and query MesProTask（源框架导入）", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MesProTaskService.create({
        code: "测试MesProTask（源框架导入）",
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MesProTaskService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MesProTaskService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MesProTaskService.update(created.id, {
        id: created.id,
        code: "更新MesProTask（源框架导入）",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MesProTaskService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
