// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MesProWorkOrderService } from "../mes-pro-work-order.service"

describe("MesProWorkOrderService", () => {
  it("should create and query MES 生产工单", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MesProWorkOrderService.create({
        code: "测试MES 生产工单",
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MesProWorkOrderService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MesProWorkOrderService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MesProWorkOrderService.update(created.id, {
        id: created.id,
        code: "更新MES 生产工单",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MesProWorkOrderService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
