// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  erpSaleOrderCreateSchema,
  erpSaleOrderPageQuerySchema,
  erpSaleOrderUpdateSchema,
} from "../backend/validators/erp-sale-order.validator"

export const erpSaleOrderActionSchemas = {
  "ruoyi.cmd.erp.erpSaleOrder.page": erpSaleOrderPageQuerySchema,
  "ruoyi.cmd.erp.erpSaleOrder.get": z.object({ id: z.string() }),
  "ruoyi.cmd.erp.erpSaleOrder.create": erpSaleOrderCreateSchema,
  "ruoyi.cmd.erp.erpSaleOrder.update": erpSaleOrderUpdateSchema,
  "ruoyi.cmd.erp.erpSaleOrder.delete": z.object({ id: z.string() }),
  "erp.pageErpSaleOrder": erpSaleOrderPageQuerySchema,
  "erp.getErpSaleOrder": z.object({ id: z.string() }),
  "erp.createErpSaleOrder": erpSaleOrderCreateSchema,
  "erp.updateErpSaleOrder": erpSaleOrderUpdateSchema,
  "erp.deleteErpSaleOrder": z.object({ id: z.string() }),
} as const

export const ERP_SALE_ORDER_ACTION_SCHEMAS = erpSaleOrderActionSchemas

export function registerActionSchemas() {
  return erpSaleOrderActionSchemas
}
