// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  erpStockInCreateSchema,
  erpStockInPageQuerySchema,
  erpStockInUpdateSchema,
} from "../backend/validators/erp-stock-in.validator"

export const erpStockInActionSchemas = {
  "ruoyi.cmd.erp.erpStockIn.page": erpStockInPageQuerySchema,
  "ruoyi.cmd.erp.erpStockIn.get": z.object({ id: z.string() }),
  "ruoyi.cmd.erp.erpStockIn.create": erpStockInCreateSchema,
  "ruoyi.cmd.erp.erpStockIn.update": erpStockInUpdateSchema,
  "ruoyi.cmd.erp.erpStockIn.delete": z.object({ id: z.string() }),
  "erp.pageErpStockIn": erpStockInPageQuerySchema,
  "erp.getErpStockIn": z.object({ id: z.string() }),
  "erp.createErpStockIn": erpStockInCreateSchema,
  "erp.updateErpStockIn": erpStockInUpdateSchema,
  "erp.deleteErpStockIn": z.object({ id: z.string() }),
} as const

export const ERP_STOCK_IN_ACTION_SCHEMAS = erpStockInActionSchemas

export function registerActionSchemas() {
  return erpStockInActionSchemas
}
