// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  erpStockMoveItemCreateSchema,
  erpStockMoveItemPageQuerySchema,
  erpStockMoveItemUpdateSchema,
} from "../backend/validators/erp-stock-move-item.validator"

export const erpStockMoveItemActionSchemas = {
  "ruoyi.cmd.erp.erpStockMoveItem.page": erpStockMoveItemPageQuerySchema,
  "ruoyi.cmd.erp.erpStockMoveItem.get": z.object({ id: z.string() }),
  "ruoyi.cmd.erp.erpStockMoveItem.create": erpStockMoveItemCreateSchema,
  "ruoyi.cmd.erp.erpStockMoveItem.update": erpStockMoveItemUpdateSchema,
  "ruoyi.cmd.erp.erpStockMoveItem.delete": z.object({ id: z.string() }),
  "erp.pageErpStockMoveItem": erpStockMoveItemPageQuerySchema,
  "erp.getErpStockMoveItem": z.object({ id: z.string() }),
  "erp.createErpStockMoveItem": erpStockMoveItemCreateSchema,
  "erp.updateErpStockMoveItem": erpStockMoveItemUpdateSchema,
  "erp.deleteErpStockMoveItem": z.object({ id: z.string() }),
} as const

export const ERP_STOCK_MOVE_ITEM_ACTION_SCHEMAS = erpStockMoveItemActionSchemas

export function registerActionSchemas() {
  return erpStockMoveItemActionSchemas
}
