// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MesWmStockTakingTaskCreateDTO,
  MesWmStockTakingTaskPageQuery,
  MesWmStockTakingTaskUpdateDTO,
  MesWmStockTakingTaskVO,
} from "@/modules/mes/backend/types/mes-wm-stock-taking-task.types"

const BASE_URL = "/api/v1/admin/mes/mes-wm-stock-taking-task"

export const MesWmStockTakingTaskApi = {
  async page(params?: MesWmStockTakingTaskPageQuery) {
    return request.get<{ items: MesWmStockTakingTaskVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MesWmStockTakingTaskVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MesWmStockTakingTaskCreateDTO) {
    return request.post<MesWmStockTakingTaskVO>(BASE_URL, data)
  },

  async update(data: MesWmStockTakingTaskUpdateDTO) {
    return request.put<MesWmStockTakingTaskVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MesWmStockTakingTaskPageQuery) {
    return request.post<MesWmStockTakingTaskVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
