// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MesWmProductIssueLineCreateDTO,
  MesWmProductIssueLinePageQuery,
  MesWmProductIssueLineUpdateDTO,
  MesWmProductIssueLineVO,
} from "@/modules/mes/backend/types/mes-wm-product-issue-line.types"

const BASE_URL = "/api/v1/admin/mes/mes-wm-product-issue-line"

export const MesWmProductIssueLineApi = {
  async page(params?: MesWmProductIssueLinePageQuery) {
    return request.get<{ items: MesWmProductIssueLineVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MesWmProductIssueLineVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MesWmProductIssueLineCreateDTO) {
    return request.post<MesWmProductIssueLineVO>(BASE_URL, data)
  },

  async update(data: MesWmProductIssueLineUpdateDTO) {
    return request.put<MesWmProductIssueLineVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MesWmProductIssueLinePageQuery) {
    return request.post<MesWmProductIssueLineVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
