// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MesMdProductSipCreateDTO,
  MesMdProductSipPageQuery,
  MesMdProductSipUpdateDTO,
  MesMdProductSipVO,
} from "@/modules/mes/backend/types/mes-md-product-sip.types"

const BASE_URL = "/api/v1/admin/mes/mes-md-product-sip"

export const MesMdProductSipApi = {
  async page(params?: MesMdProductSipPageQuery) {
    return request.get<{ items: MesMdProductSipVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MesMdProductSipVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MesMdProductSipCreateDTO) {
    return request.post<MesMdProductSipVO>(BASE_URL, data)
  },

  async update(data: MesMdProductSipUpdateDTO) {
    return request.put<MesMdProductSipVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MesMdProductSipPageQuery) {
    return request.post<MesMdProductSipVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
