// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MesWmReturnSalesDetailCreateDTO,
  MesWmReturnSalesDetailPageQuery,
  MesWmReturnSalesDetailUpdateDTO,
  MesWmReturnSalesDetailVO,
} from "@/modules/mes/backend/types/mes-wm-return-sales-detail.types"

const BASE_URL = "/api/v1/admin/mes/mes-wm-return-sales-detail"

export const MesWmReturnSalesDetailApi = {
  async page(params?: MesWmReturnSalesDetailPageQuery) {
    return request.get<{ items: MesWmReturnSalesDetailVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MesWmReturnSalesDetailVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MesWmReturnSalesDetailCreateDTO) {
    return request.post<MesWmReturnSalesDetailVO>(BASE_URL, data)
  },

  async update(data: MesWmReturnSalesDetailUpdateDTO) {
    return request.put<MesWmReturnSalesDetailVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MesWmReturnSalesDetailPageQuery) {
    return request.post<MesWmReturnSalesDetailVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
