// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MesWmTransactionCreateDTO,
  MesWmTransactionPageQuery,
  MesWmTransactionUpdateDTO,
  MesWmTransactionVO,
} from "@/modules/mes/backend/types/mes-wm-transaction.types"

const BASE_URL = "/api/v1/admin/mes/mes-wm-transaction"

export const MesWmTransactionApi = {
  async page(params?: MesWmTransactionPageQuery) {
    return request.get<{ items: MesWmTransactionVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MesWmTransactionVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MesWmTransactionCreateDTO) {
    return request.post<MesWmTransactionVO>(BASE_URL, data)
  },

  async update(data: MesWmTransactionUpdateDTO) {
    return request.put<MesWmTransactionVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MesWmTransactionPageQuery) {
    return request.post<MesWmTransactionVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
