// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MesDvCheckRecordLineCreateDTO,
  MesDvCheckRecordLinePageQuery,
  MesDvCheckRecordLineUpdateDTO,
  MesDvCheckRecordLineVO,
} from "@/modules/mes/backend/types/mes-dv-check-record-line.types"

const BASE_URL = "/api/v1/admin/mes/mes-dv-check-record-line"

export const MesDvCheckRecordLineApi = {
  async page(params?: MesDvCheckRecordLinePageQuery) {
    return request.get<{ items: MesDvCheckRecordLineVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MesDvCheckRecordLineVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MesDvCheckRecordLineCreateDTO) {
    return request.post<MesDvCheckRecordLineVO>(BASE_URL, data)
  },

  async update(data: MesDvCheckRecordLineUpdateDTO) {
    return request.put<MesDvCheckRecordLineVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MesDvCheckRecordLinePageQuery) {
    return request.post<MesDvCheckRecordLineVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
