// Auto-generated by Codegen Engine
export interface CrmContactBusinessDO {
  id: number
  contact_id?: number
  business_id?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmContactBusinessVO {
  id: number
  contact_id?: number
  business_id?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmContactBusinessCreateDTO {
  contact_id?: number
  business_id?: number
}

export interface CrmContactBusinessUpdateDTO extends Partial<CrmContactBusinessCreateDTO> {
  id: string
}

export interface CrmContactBusinessPageQuery {
  page?: number
  pageSize?: number

}
