// Auto-generated by Codegen Engine
export interface CrmProductCategoryDO {
  id: number
  name?: string
  parent_id?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmProductCategoryVO {
  id: number
  name?: string
  parent_id?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmProductCategoryCreateDTO {
  name?: string
  parent_id?: number
}

export interface CrmProductCategoryUpdateDTO extends Partial<CrmProductCategoryCreateDTO> {
  id: string
}

export interface CrmProductCategoryPageQuery {
  page?: number
  pageSize?: number

}
