// Auto-generated by Codegen Engine
export interface CrmReceivableDO {
  id: number
  no?: string
  plan_id?: number
  customer_id?: number
  contract_id?: number
  owner_user_id?: number
  return_time?: string
  return_type?: number
  price?: number
  remark?: string
  process_instance_id?: string
  audit_status?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmReceivableVO {
  id: number
  no?: string
  plan_id?: number
  customer_id?: number
  contract_id?: number
  owner_user_id?: number
  return_time?: string
  return_type?: number
  price?: number
  remark?: string
  process_instance_id?: string
  audit_status?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmReceivableCreateDTO {
  no?: string
  plan_id?: number
  customer_id?: number
  contract_id?: number
  owner_user_id?: number
  return_time?: string
  return_type?: number
  price?: number
  remark?: string
  process_instance_id?: string
  audit_status?: number
}

export interface CrmReceivableUpdateDTO extends Partial<CrmReceivableCreateDTO> {
  id: string
}

export interface CrmReceivablePageQuery {
  page?: number
  pageSize?: number

}
