// Auto-generated by Codegen Engine
export interface CrmCustomerPoolConfigDO {
  id: number
  enabled?: boolean
  contact_expire_days?: number
  deal_expire_days?: number
  notify_enabled?: boolean
  notify_days?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmCustomerPoolConfigVO {
  id: number
  enabled?: boolean
  contact_expire_days?: number
  deal_expire_days?: number
  notify_enabled?: boolean
  notify_days?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmCustomerPoolConfigCreateDTO {
  enabled?: boolean
  contact_expire_days?: number
  deal_expire_days?: number
  notify_enabled?: boolean
  notify_days?: number
}

export interface CrmCustomerPoolConfigUpdateDTO extends Partial<CrmCustomerPoolConfigCreateDTO> {
  id: string
}

export interface CrmCustomerPoolConfigPageQuery {
  page?: number
  pageSize?: number

}
