// Auto-generated by Codegen Engine
export interface CrmPerformanceConfigDO {
  id: number
  biz_type?: number
  object_id?: number
  object_type?: number
  year?: number
  year_target_price?: number
  january_target_price?: number
  february_target_price?: number
  march_target_price?: number
  april_target_price?: number
  may_target_price?: number
  june_target_price?: number
  july_target_price?: number
  august_target_price?: number
  september_target_price?: number
  october_target_price?: number
  november_target_price?: number
  december_target_price?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmPerformanceConfigVO {
  id: number
  biz_type?: number
  object_id?: number
  object_type?: number
  year?: number
  year_target_price?: number
  january_target_price?: number
  february_target_price?: number
  march_target_price?: number
  april_target_price?: number
  may_target_price?: number
  june_target_price?: number
  july_target_price?: number
  august_target_price?: number
  september_target_price?: number
  october_target_price?: number
  november_target_price?: number
  december_target_price?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface CrmPerformanceConfigCreateDTO {
  biz_type?: number
  object_id?: number
  object_type?: number
  year?: number
  year_target_price?: number
  january_target_price?: number
  february_target_price?: number
  march_target_price?: number
  april_target_price?: number
  may_target_price?: number
  june_target_price?: number
  july_target_price?: number
  august_target_price?: number
  september_target_price?: number
  october_target_price?: number
  november_target_price?: number
  december_target_price?: number
}

export interface CrmPerformanceConfigUpdateDTO extends Partial<CrmPerformanceConfigCreateDTO> {
  id: string
}

export interface CrmPerformanceConfigPageQuery {
  page?: number
  pageSize?: number

}
