// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { AiApiKeyRepository } from "../repositories/ai-api-key.repository"
import type {
  AiApiKeyCreateDTO,
  AiApiKeyPageQuery,
  AiApiKeyUpdateDTO,
} from "../types/ai-api-key.types"

export class AiApiKeyService {
  static async page(query: AiApiKeyPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return AiApiKeyRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return AiApiKeyRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: AiApiKeyCreateDTO, actorId?: string, tenantId?: string) {
    const row = await AiApiKeyRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("ai.aiApiKey.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: AiApiKeyUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await AiApiKeyRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("ai.aiApiKey.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await AiApiKeyRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("ai.aiApiKey.deleted", { id, actorId })
    }
    return ok
  }
}

export const aiApiKeyService = AiApiKeyService
