// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { AiChatMessageService } from "./ai-chat-message.service"
import { registerActionSchemas } from "../contract/ai-chat-message.actions"
import type {
  AiChatMessageCreateDTO,
  AiChatMessagePageQuery,
  AiChatMessageUpdateDTO,
} from "../types/ai-chat-message.types"

export class AiChatMessageRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.ai.aiChatMessage.page", async (req) => {
      const query = req.data as AiChatMessagePageQuery
      return AiChatMessageService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.ai.aiChatMessage.get", async (req) => {
      const { id } = req.data as { id: string }
      return AiChatMessageService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.ai.aiChatMessage.create", async (req) => {
      const data = req.data as AiChatMessageCreateDTO
      return AiChatMessageService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.ai.aiChatMessage.update", async (req) => {
      const { id, ...rest } = req.data as AiChatMessageUpdateDTO
      return AiChatMessageService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.ai.aiChatMessage.delete", async (req) => {
      const { id } = req.data as { id: string }
      return AiChatMessageService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const aiChatMessageRpc = AiChatMessageRpc

export const aiChatMessageDomainFacade = createDomainFacade({
  domain: "ai",
  serviceBus,
})
