// Auto-generated by Codegen Engine (App Router Page)
import { ErpPurchaseInItemListPage } from "@/modules/erp/frontend/pages/erp-purchase-in-item-list.page"

export default function Page() {
  return <ErpPurchaseInItemListPage />
}
