// Auto-generated by Codegen Engine (App Router Page)
import { IotSceneRuleListPage } from "@/modules/iot/frontend/pages/iot-scene-rule-list.page"

export default function Page() {
  return <IotSceneRuleListPage />
}
