// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { BpmUserGroupService } from "./bpm-user-group.service"
import { registerActionSchemas } from "../contract/bpm-user-group.actions"
import type {
  BpmUserGroupCreateDTO,
  BpmUserGroupPageQuery,
  BpmUserGroupUpdateDTO,
} from "../types/bpm-user-group.types"

export class BpmUserGroupRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.bpm.bpmUserGroup.page", async (req) => {
      const query = req.data as BpmUserGroupPageQuery
      return BpmUserGroupService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.bpm.bpmUserGroup.get", async (req) => {
      const { id } = req.data as { id: string }
      return BpmUserGroupService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.bpm.bpmUserGroup.create", async (req) => {
      const data = req.data as BpmUserGroupCreateDTO
      return BpmUserGroupService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.bpm.bpmUserGroup.update", async (req) => {
      const { id, ...rest } = req.data as BpmUserGroupUpdateDTO
      return BpmUserGroupService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.bpm.bpmUserGroup.delete", async (req) => {
      const { id } = req.data as { id: string }
      return BpmUserGroupService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const bpmUserGroupRpc = BpmUserGroupRpc

export const bpmUserGroupDomainFacade = createDomainFacade({
  domain: "bpm",
  serviceBus,
})
