// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { IotSceneRuleService } from "../iot-scene-rule.service"

describe("IotSceneRuleService", () => {
  it("should create and query IoT 场景联动规则", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await IotSceneRuleService.create({
        name: "测试IoT 场景联动规则",
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await IotSceneRuleService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await IotSceneRuleService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await IotSceneRuleService.update(created.id, {
        id: created.id,
          name: "测试更新IoT 场景联动规则",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await IotSceneRuleService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
