// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  WmsItemCreateDTO,
  WmsItemPageQuery,
  WmsItemUpdateDTO,
  WmsItemVO,
} from "@/modules/wms/backend/types/wms-item.types"

const BASE_URL = "/api/v1/admin/wms/wms-item"

export const WmsItemApi = {
  async page(params?: WmsItemPageQuery) {
    return request.get<{ items: WmsItemVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<WmsItemVO>(`${BASE_URL}/${id}`)
  },

  async create(data: WmsItemCreateDTO) {
    return request.post<WmsItemVO>(BASE_URL, data)
  },

  async update(data: WmsItemUpdateDTO) {
    return request.put<WmsItemVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: WmsItemPageQuery) {
    return request.post<WmsItemVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
