// Auto-generated by Codegen Engine
export interface PayChannelDO {
  id: number
  code?: string
  status?: number
  fee_rate?: number
  remark?: string
  app_id?: number
  config?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface PayChannelVO {
  id: number
  code?: string
  status?: number
  fee_rate?: number
  remark?: string
  app_id?: number
  config?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface PayChannelCreateDTO {
  code?: string
  status?: number
  fee_rate?: number
  remark?: string
  app_id?: number
  config?: string
}

export interface PayChannelUpdateDTO extends Partial<PayChannelCreateDTO> {
  id: string
}

export interface PayChannelPageQuery {
  page?: number
  pageSize?: number

}
