// Auto-generated by Codegen Engine
"use client"

import React, { useState, useEffect } from "react"
import { MesDvRepairApi } from "../api/mes-dv-repair.api"
import type { MesDvRepairCreateDTO, MesDvRepairVO } from "@/modules/mes/backend/types/mes-dv-repair.types"

interface MesDvRepairFormProps {
  open: boolean
  initialData?: MesDvRepairVO | null
  onClose: () => void
  onSuccess: () => void
}

export function MesDvRepairForm({ open, initialData, onClose, onSuccess }: MesDvRepairFormProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [formData, setFormData] = useState<Record<string, any>>({})

  useEffect(() => {
    if (open) {
      setError(null)
      setFormData({
    code: initialData?.code ?? "",
    name: initialData?.name ?? "",
    machinery_id: initialData?.machinery_id ?? undefined,
    require_date: initialData?.require_date ?? "",
    finish_date: initialData?.finish_date ?? "",
    confirm_date: initialData?.confirm_date ?? "",
    result: initialData?.result ?? undefined,
    accepted_user_id: initialData?.accepted_user_id ?? undefined,
    confirm_user_id: initialData?.confirm_user_id ?? undefined,
    source_doc_type: initialData?.source_doc_type ?? undefined,
    source_doc_id: initialData?.source_doc_id ?? undefined,
    source_doc_code: initialData?.source_doc_code ?? "",
    status: initialData?.status ?? undefined,
    remark: initialData?.remark ?? "",
      })
    }
  }, [open, initialData])

  if (!open) return null

  const isEdit = Boolean(initialData?.id)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)
    try {
      if (isEdit && initialData?.id) {
        await MesDvRepairApi.update({ id: initialData.id, ...formData } as any)
      } else {
        await MesDvRepairApi.create(formData as MesDvRepairCreateDTO)
      }
      onSuccess()
      onClose()
    } catch (err: any) {
      setError(err?.message || "操作失败")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div data-testid="mes-dv-repair-form-overlay" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs">
      <div
        role="dialog"
        aria-modal="true"
        aria-label={isEdit ? "编辑MES 维修工单" : "新增MES 维修工单"}
        data-testid="mes-dv-repair-form"
        data-agent-scope="mes-dv-repair:form"
        data-agent-state={loading ? "submitting" : error ? "error" : "open"}
        className="bg-white rounded-lg shadow-xl w-full max-w-lg mx-4 overflow-hidden">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h3 className="text-sm font-semibold text-slate-800">
            {isEdit ? "编辑MES 维修工单" : "新增MES 维修工单"}
          </h3>
          <button onClick={onClose} data-testid="mes-dv-repair-form-close" data-agent-target="mes-dv-repair:close" aria-label="关闭" className="text-slate-400 hover:text-slate-600 text-lg leading-none">&times;</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="px-6 py-4 space-y-3 max-h-[70vh] overflow-y-auto">
            {error && (
              <div data-testid="mes-dv-repair-form-error" role="alert" className="p-2 text-xs text-red-600 bg-red-50 rounded border border-red-200">{error}</div>
            )}
        <div>
          <label htmlFor="mes-dv-repair-code" className="block text-xs text-slate-600 mb-1">维修工单编码</label>
          <input
            type="text"
            id="mes-dv-repair-code"
            data-testid="field-code"
            data-agent-target="mes-dv-repair:field:code"
            data-agent-state={formData.code ? "filled" : "empty"}
            aria-label="维修工单编码"
            value={formData.code ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, code: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入维修工单编码"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-name" className="block text-xs text-slate-600 mb-1">维修工单名称</label>
          <input
            type="text"
            id="mes-dv-repair-name"
            data-testid="field-name"
            data-agent-target="mes-dv-repair:field:name"
            data-agent-state={formData.name ? "filled" : "empty"}
            aria-label="维修工单名称"
            value={formData.name ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入维修工单名称"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-machinery_id" className="block text-xs text-slate-600 mb-1">设备编号</label>
          <input
            type="number"
            id="mes-dv-repair-machinery_id"
            data-testid="field-machinery_id"
            data-agent-target="mes-dv-repair:field:machinery_id"
            data-agent-state={formData.machinery_id == null || formData.machinery_id === "" ? "empty" : "filled"}
            aria-label="设备编号"
            value={formData.machinery_id != null ? String(formData.machinery_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, machinery_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入设备编号"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-require_date" className="block text-xs text-slate-600 mb-1">报修日期</label>
          <input
            type="text"
            id="mes-dv-repair-require_date"
            data-testid="field-require_date"
            data-agent-target="mes-dv-repair:field:require_date"
            data-agent-state={formData.require_date ? "filled" : "empty"}
            aria-label="报修日期"
            value={formData.require_date ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, require_date: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入报修日期"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-finish_date" className="block text-xs text-slate-600 mb-1">维修完成日期</label>
          <input
            type="text"
            id="mes-dv-repair-finish_date"
            data-testid="field-finish_date"
            data-agent-target="mes-dv-repair:field:finish_date"
            data-agent-state={formData.finish_date ? "filled" : "empty"}
            aria-label="维修完成日期"
            value={formData.finish_date ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, finish_date: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入维修完成日期"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-confirm_date" className="block text-xs text-slate-600 mb-1">验收日期</label>
          <input
            type="text"
            id="mes-dv-repair-confirm_date"
            data-testid="field-confirm_date"
            data-agent-target="mes-dv-repair:field:confirm_date"
            data-agent-state={formData.confirm_date ? "filled" : "empty"}
            aria-label="验收日期"
            value={formData.confirm_date ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, confirm_date: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入验收日期"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-result" className="block text-xs text-slate-600 mb-1">维修结果</label>
          <input
            type="number"
            id="mes-dv-repair-result"
            data-testid="field-result"
            data-agent-target="mes-dv-repair:field:result"
            data-agent-state={formData.result == null || formData.result === "" ? "empty" : "filled"}
            aria-label="维修结果"
            value={formData.result != null ? String(formData.result) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, result: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入维修结果"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-accepted_user_id" className="block text-xs text-slate-600 mb-1">维修人用户编号</label>
          <input
            type="number"
            id="mes-dv-repair-accepted_user_id"
            data-testid="field-accepted_user_id"
            data-agent-target="mes-dv-repair:field:accepted_user_id"
            data-agent-state={formData.accepted_user_id == null || formData.accepted_user_id === "" ? "empty" : "filled"}
            aria-label="维修人用户编号"
            value={formData.accepted_user_id != null ? String(formData.accepted_user_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, accepted_user_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入维修人用户编号"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-confirm_user_id" className="block text-xs text-slate-600 mb-1">验收人用户编号</label>
          <input
            type="number"
            id="mes-dv-repair-confirm_user_id"
            data-testid="field-confirm_user_id"
            data-agent-target="mes-dv-repair:field:confirm_user_id"
            data-agent-state={formData.confirm_user_id == null || formData.confirm_user_id === "" ? "empty" : "filled"}
            aria-label="验收人用户编号"
            value={formData.confirm_user_id != null ? String(formData.confirm_user_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, confirm_user_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入验收人用户编号"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-source_doc_type" className="block text-xs text-slate-600 mb-1">来源单据类型</label>
          <input
            type="number"
            id="mes-dv-repair-source_doc_type"
            data-testid="field-source_doc_type"
            data-agent-target="mes-dv-repair:field:source_doc_type"
            data-agent-state={formData.source_doc_type == null || formData.source_doc_type === "" ? "empty" : "filled"}
            aria-label="来源单据类型"
            value={formData.source_doc_type != null ? String(formData.source_doc_type) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, source_doc_type: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入来源单据类型"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-source_doc_id" className="block text-xs text-slate-600 mb-1">来源单据编号</label>
          <input
            type="number"
            id="mes-dv-repair-source_doc_id"
            data-testid="field-source_doc_id"
            data-agent-target="mes-dv-repair:field:source_doc_id"
            data-agent-state={formData.source_doc_id == null || formData.source_doc_id === "" ? "empty" : "filled"}
            aria-label="来源单据编号"
            value={formData.source_doc_id != null ? String(formData.source_doc_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, source_doc_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入来源单据编号"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-source_doc_code" className="block text-xs text-slate-600 mb-1">来源单据编码</label>
          <input
            type="text"
            id="mes-dv-repair-source_doc_code"
            data-testid="field-source_doc_code"
            data-agent-target="mes-dv-repair:field:source_doc_code"
            data-agent-state={formData.source_doc_code ? "filled" : "empty"}
            aria-label="来源单据编码"
            value={formData.source_doc_code ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, source_doc_code: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入来源单据编码"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-status" className="block text-xs text-slate-600 mb-1">状态</label>
          <input
            type="number"
            id="mes-dv-repair-status"
            data-testid="field-status"
            data-agent-target="mes-dv-repair:field:status"
            data-agent-state={formData.status == null || formData.status === "" ? "empty" : "filled"}
            aria-label="状态"
            value={formData.status != null ? String(formData.status) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, status: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入状态"
            
          />
        </div>

        <div>
          <label htmlFor="mes-dv-repair-remark" className="block text-xs text-slate-600 mb-1">备注</label>
          <input
            type="text"
            id="mes-dv-repair-remark"
            data-testid="field-remark"
            data-agent-target="mes-dv-repair:field:remark"
            data-agent-state={formData.remark ? "filled" : "empty"}
            aria-label="备注"
            value={formData.remark ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, remark: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入备注"
            
          />
        </div>
          </div>

          <div className="flex items-center justify-end gap-2 px-6 py-3 border-t border-slate-200 bg-slate-50">
            <button
              type="button"
              onClick={onClose}
              data-testid="mes-dv-repair-form-cancel"
              data-agent-target="mes-dv-repair:cancel"
              className="px-4 py-1.5 text-xs text-slate-600 hover:text-slate-800 border border-slate-300 rounded hover:bg-slate-100 transition-colors"
            >
              取消
            </button>
            <button
              type="submit"
              disabled={loading}
              data-testid="mes-dv-repair-form-submit"
              data-agent-target="mes-dv-repair:submit"
              data-agent-state={loading ? "busy" : "idle"}
              className="px-4 py-1.5 text-xs text-white bg-blue-600 rounded hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              {loading ? "保存中..." : "保存"}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
