// Auto-generated by Codegen Engine
"use client"

import React, { useState, useEffect } from "react"
import { MesProProcessContentApi } from "../api/mes-pro-process-content.api"
import type { MesProProcessContentCreateDTO, MesProProcessContentVO } from "@/modules/mes/backend/types/mes-pro-process-content.types"

interface MesProProcessContentFormProps {
  open: boolean
  initialData?: MesProProcessContentVO | null
  onClose: () => void
  onSuccess: () => void
}

export function MesProProcessContentForm({ open, initialData, onClose, onSuccess }: MesProProcessContentFormProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [formData, setFormData] = useState<Record<string, any>>({})

  useEffect(() => {
    if (open) {
      setError(null)
      setFormData({
    process_id: initialData?.process_id ?? undefined,
    sort: initialData?.sort ?? undefined,
    content: initialData?.content ?? "",
    device: initialData?.device ?? "",
    material: initialData?.material ?? "",
    doc_url: initialData?.doc_url ?? "",
    remark: initialData?.remark ?? "",
      })
    }
  }, [open, initialData])

  if (!open) return null

  const isEdit = Boolean(initialData?.id)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)
    try {
      if (isEdit && initialData?.id) {
        await MesProProcessContentApi.update({ id: initialData.id, ...formData } as any)
      } else {
        await MesProProcessContentApi.create(formData as MesProProcessContentCreateDTO)
      }
      onSuccess()
      onClose()
    } catch (err: any) {
      setError(err?.message || "操作失败")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div data-testid="mes-pro-process-content-form-overlay" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs">
      <div
        role="dialog"
        aria-modal="true"
        aria-label={isEdit ? "编辑MES 生产工序内容" : "新增MES 生产工序内容"}
        data-testid="mes-pro-process-content-form"
        data-agent-scope="mes-pro-process-content:form"
        data-agent-state={loading ? "submitting" : error ? "error" : "open"}
        className="bg-white rounded-lg shadow-xl w-full max-w-lg mx-4 overflow-hidden">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h3 className="text-sm font-semibold text-slate-800">
            {isEdit ? "编辑MES 生产工序内容" : "新增MES 生产工序内容"}
          </h3>
          <button onClick={onClose} data-testid="mes-pro-process-content-form-close" data-agent-target="mes-pro-process-content:close" aria-label="关闭" className="text-slate-400 hover:text-slate-600 text-lg leading-none">&times;</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="px-6 py-4 space-y-3 max-h-[70vh] overflow-y-auto">
            {error && (
              <div data-testid="mes-pro-process-content-form-error" role="alert" className="p-2 text-xs text-red-600 bg-red-50 rounded border border-red-200">{error}</div>
            )}
        <div>
          <label htmlFor="mes-pro-process-content-process_id" className="block text-xs text-slate-600 mb-1">工序编号</label>
          <input
            type="number"
            id="mes-pro-process-content-process_id"
            data-testid="field-process_id"
            data-agent-target="mes-pro-process-content:field:process_id"
            data-agent-state={formData.process_id == null || formData.process_id === "" ? "empty" : "filled"}
            aria-label="工序编号"
            value={formData.process_id != null ? String(formData.process_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, process_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入工序编号"
            
          />
        </div>

        <div>
          <label htmlFor="mes-pro-process-content-sort" className="block text-xs text-slate-600 mb-1">顺序编号</label>
          <input
            type="number"
            id="mes-pro-process-content-sort"
            data-testid="field-sort"
            data-agent-target="mes-pro-process-content:field:sort"
            data-agent-state={formData.sort == null || formData.sort === "" ? "empty" : "filled"}
            aria-label="顺序编号"
            value={formData.sort != null ? String(formData.sort) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, sort: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入顺序编号"
            
          />
        </div>

        <div>
          <label htmlFor="mes-pro-process-content-content" className="block text-xs text-slate-600 mb-1">步骤说明</label>
          <input
            type="text"
            id="mes-pro-process-content-content"
            data-testid="field-content"
            data-agent-target="mes-pro-process-content:field:content"
            data-agent-state={formData.content ? "filled" : "empty"}
            aria-label="步骤说明"
            value={formData.content ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, content: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入步骤说明"
            
          />
        </div>

        <div>
          <label htmlFor="mes-pro-process-content-device" className="block text-xs text-slate-600 mb-1">辅助设备</label>
          <input
            type="text"
            id="mes-pro-process-content-device"
            data-testid="field-device"
            data-agent-target="mes-pro-process-content:field:device"
            data-agent-state={formData.device ? "filled" : "empty"}
            aria-label="辅助设备"
            value={formData.device ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, device: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入辅助设备"
            
          />
        </div>

        <div>
          <label htmlFor="mes-pro-process-content-material" className="block text-xs text-slate-600 mb-1">辅助材料</label>
          <input
            type="text"
            id="mes-pro-process-content-material"
            data-testid="field-material"
            data-agent-target="mes-pro-process-content:field:material"
            data-agent-state={formData.material ? "filled" : "empty"}
            aria-label="辅助材料"
            value={formData.material ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, material: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入辅助材料"
            
          />
        </div>

        <div>
          <label htmlFor="mes-pro-process-content-doc_url" className="block text-xs text-slate-600 mb-1">材料文档 URL</label>
          <input
            type="text"
            id="mes-pro-process-content-doc_url"
            data-testid="field-doc_url"
            data-agent-target="mes-pro-process-content:field:doc_url"
            data-agent-state={formData.doc_url ? "filled" : "empty"}
            aria-label="材料文档 URL"
            value={formData.doc_url ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, doc_url: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入材料文档 URL"
            
          />
        </div>

        <div>
          <label htmlFor="mes-pro-process-content-remark" className="block text-xs text-slate-600 mb-1">备注</label>
          <input
            type="text"
            id="mes-pro-process-content-remark"
            data-testid="field-remark"
            data-agent-target="mes-pro-process-content:field:remark"
            data-agent-state={formData.remark ? "filled" : "empty"}
            aria-label="备注"
            value={formData.remark ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, remark: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入备注"
            
          />
        </div>
          </div>

          <div className="flex items-center justify-end gap-2 px-6 py-3 border-t border-slate-200 bg-slate-50">
            <button
              type="button"
              onClick={onClose}
              data-testid="mes-pro-process-content-form-cancel"
              data-agent-target="mes-pro-process-content:cancel"
              className="px-4 py-1.5 text-xs text-slate-600 hover:text-slate-800 border border-slate-300 rounded hover:bg-slate-100 transition-colors"
            >
              取消
            </button>
            <button
              type="submit"
              disabled={loading}
              data-testid="mes-pro-process-content-form-submit"
              data-agent-target="mes-pro-process-content:submit"
              data-agent-state={loading ? "busy" : "idle"}
              className="px-4 py-1.5 text-xs text-white bg-blue-600 rounded hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              {loading ? "保存中..." : "保存"}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
