// Auto-generated by Codegen Engine
"use client"

import React, { useState, useEffect } from "react"
import { MesWmStockTakingPlanApi } from "../api/mes-wm-stock-taking-plan.api"
import type { MesWmStockTakingPlanCreateDTO, MesWmStockTakingPlanVO } from "@/modules/mes/backend/types/mes-wm-stock-taking-plan.types"

interface MesWmStockTakingPlanFormProps {
  open: boolean
  initialData?: MesWmStockTakingPlanVO | null
  onClose: () => void
  onSuccess: () => void
}

export function MesWmStockTakingPlanForm({ open, initialData, onClose, onSuccess }: MesWmStockTakingPlanFormProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [formData, setFormData] = useState<Record<string, any>>({})

  useEffect(() => {
    if (open) {
      setError(null)
      setFormData({
    code: initialData?.code ?? "",
    name: initialData?.name ?? "",
    type: initialData?.type ?? undefined,
    start_time: initialData?.start_time ?? "",
    end_time: initialData?.end_time ?? "",
    blind_flag: initialData?.blind_flag ?? false,
    frozen: initialData?.frozen ?? false,
    status: initialData?.status ?? undefined,
    remark: initialData?.remark ?? "",
      })
    }
  }, [open, initialData])

  if (!open) return null

  const isEdit = Boolean(initialData?.id)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)
    try {
      if (isEdit && initialData?.id) {
        await MesWmStockTakingPlanApi.update({ id: initialData.id, ...formData } as any)
      } else {
        await MesWmStockTakingPlanApi.create(formData as MesWmStockTakingPlanCreateDTO)
      }
      onSuccess()
      onClose()
    } catch (err: any) {
      setError(err?.message || "操作失败")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div data-testid="mes-wm-stock-taking-plan-form-overlay" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs">
      <div
        role="dialog"
        aria-modal="true"
        aria-label={isEdit ? "编辑MES 盘点方案" : "新增MES 盘点方案"}
        data-testid="mes-wm-stock-taking-plan-form"
        data-agent-scope="mes-wm-stock-taking-plan:form"
        data-agent-state={loading ? "submitting" : error ? "error" : "open"}
        className="bg-white rounded-lg shadow-xl w-full max-w-lg mx-4 overflow-hidden">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h3 className="text-sm font-semibold text-slate-800">
            {isEdit ? "编辑MES 盘点方案" : "新增MES 盘点方案"}
          </h3>
          <button onClick={onClose} data-testid="mes-wm-stock-taking-plan-form-close" data-agent-target="mes-wm-stock-taking-plan:close" aria-label="关闭" className="text-slate-400 hover:text-slate-600 text-lg leading-none">&times;</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="px-6 py-4 space-y-3 max-h-[70vh] overflow-y-auto">
            {error && (
              <div data-testid="mes-wm-stock-taking-plan-form-error" role="alert" className="p-2 text-xs text-red-600 bg-red-50 rounded border border-red-200">{error}</div>
            )}
        <div>
          <label htmlFor="mes-wm-stock-taking-plan-code" className="block text-xs text-slate-600 mb-1">方案编码</label>
          <input
            type="text"
            id="mes-wm-stock-taking-plan-code"
            data-testid="field-code"
            data-agent-target="mes-wm-stock-taking-plan:field:code"
            data-agent-state={formData.code ? "filled" : "empty"}
            aria-label="方案编码"
            value={formData.code ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, code: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入方案编码"
            
          />
        </div>

        <div>
          <label htmlFor="mes-wm-stock-taking-plan-name" className="block text-xs text-slate-600 mb-1">方案名称</label>
          <input
            type="text"
            id="mes-wm-stock-taking-plan-name"
            data-testid="field-name"
            data-agent-target="mes-wm-stock-taking-plan:field:name"
            data-agent-state={formData.name ? "filled" : "empty"}
            aria-label="方案名称"
            value={formData.name ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入方案名称"
            
          />
        </div>

        <div>
          <label htmlFor="mes-wm-stock-taking-plan-type" className="block text-xs text-slate-600 mb-1">盘点类型</label>
          <input
            type="number"
            id="mes-wm-stock-taking-plan-type"
            data-testid="field-type"
            data-agent-target="mes-wm-stock-taking-plan:field:type"
            data-agent-state={formData.type == null || formData.type === "" ? "empty" : "filled"}
            aria-label="盘点类型"
            value={formData.type != null ? String(formData.type) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, type: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入盘点类型"
            
          />
        </div>

        <div>
          <label htmlFor="mes-wm-stock-taking-plan-start_time" className="block text-xs text-slate-600 mb-1">计划开始时间</label>
          <input
            type="text"
            id="mes-wm-stock-taking-plan-start_time"
            data-testid="field-start_time"
            data-agent-target="mes-wm-stock-taking-plan:field:start_time"
            data-agent-state={formData.start_time ? "filled" : "empty"}
            aria-label="计划开始时间"
            value={formData.start_time ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, start_time: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入计划开始时间"
            
          />
        </div>

        <div>
          <label htmlFor="mes-wm-stock-taking-plan-end_time" className="block text-xs text-slate-600 mb-1">计划结束时间</label>
          <input
            type="text"
            id="mes-wm-stock-taking-plan-end_time"
            data-testid="field-end_time"
            data-agent-target="mes-wm-stock-taking-plan:field:end_time"
            data-agent-state={formData.end_time ? "filled" : "empty"}
            aria-label="计划结束时间"
            value={formData.end_time ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, end_time: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入计划结束时间"
            
          />
        </div>

        <div className="flex items-center gap-2">
          <input
            type="checkbox"
            id="mes-wm-stock-taking-plan-blind_flag"
            data-testid="field-blind_flag"
            data-agent-target="mes-wm-stock-taking-plan:field:blind_flag"
            data-agent-state={formData.blind_flag ? "on" : "off"}
            aria-label="是否盲盘"
            checked={Boolean(formData.blind_flag)}
            onChange={(e) => setFormData((prev) => ({ ...prev, blind_flag: e.target.checked }))}
            className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
          />
          <label htmlFor="mes-wm-stock-taking-plan-blind_flag" className="text-xs text-slate-700 font-medium">是否盲盘</label>
        </div>

        <div className="flex items-center gap-2">
          <input
            type="checkbox"
            id="mes-wm-stock-taking-plan-frozen"
            data-testid="field-frozen"
            data-agent-target="mes-wm-stock-taking-plan:field:frozen"
            data-agent-state={formData.frozen ? "on" : "off"}
            aria-label="是否冻结库存"
            checked={Boolean(formData.frozen)}
            onChange={(e) => setFormData((prev) => ({ ...prev, frozen: e.target.checked }))}
            className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"
          />
          <label htmlFor="mes-wm-stock-taking-plan-frozen" className="text-xs text-slate-700 font-medium">是否冻结库存</label>
        </div>

        <div>
          <label htmlFor="mes-wm-stock-taking-plan-status" className="block text-xs text-slate-600 mb-1">状态</label>
          <input
            type="number"
            id="mes-wm-stock-taking-plan-status"
            data-testid="field-status"
            data-agent-target="mes-wm-stock-taking-plan:field:status"
            data-agent-state={formData.status == null || formData.status === "" ? "empty" : "filled"}
            aria-label="状态"
            value={formData.status != null ? String(formData.status) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, status: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入状态"
            
          />
        </div>

        <div>
          <label htmlFor="mes-wm-stock-taking-plan-remark" className="block text-xs text-slate-600 mb-1">备注</label>
          <input
            type="text"
            id="mes-wm-stock-taking-plan-remark"
            data-testid="field-remark"
            data-agent-target="mes-wm-stock-taking-plan:field:remark"
            data-agent-state={formData.remark ? "filled" : "empty"}
            aria-label="备注"
            value={formData.remark ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, remark: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入备注"
            
          />
        </div>
          </div>

          <div className="flex items-center justify-end gap-2 px-6 py-3 border-t border-slate-200 bg-slate-50">
            <button
              type="button"
              onClick={onClose}
              data-testid="mes-wm-stock-taking-plan-form-cancel"
              data-agent-target="mes-wm-stock-taking-plan:cancel"
              className="px-4 py-1.5 text-xs text-slate-600 hover:text-slate-800 border border-slate-300 rounded hover:bg-slate-100 transition-colors"
            >
              取消
            </button>
            <button
              type="submit"
              disabled={loading}
              data-testid="mes-wm-stock-taking-plan-form-submit"
              data-agent-target="mes-wm-stock-taking-plan:submit"
              data-agent-state={loading ? "busy" : "idle"}
              className="px-4 py-1.5 text-xs text-white bg-blue-600 rounded hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              {loading ? "保存中..." : "保存"}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
