// Auto-generated by Codegen Engine
export interface BpmProcessInstanceCopyDO {
  id: number
  start_user_id?: number
  process_instance_name?: string
  process_instance_id?: string
  process_definition_id?: string
  category?: string
  activity_id?: string
  activity_name?: string
  task_id?: string
  user_id?: number
  reason?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface BpmProcessInstanceCopyVO {
  id: number
  start_user_id?: number
  process_instance_name?: string
  process_instance_id?: string
  process_definition_id?: string
  category?: string
  activity_id?: string
  activity_name?: string
  task_id?: string
  user_id?: number
  reason?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface BpmProcessInstanceCopyCreateDTO {
  start_user_id?: number
  process_instance_name?: string
  process_instance_id?: string
  process_definition_id?: string
  category?: string
  activity_id?: string
  activity_name?: string
  task_id?: string
  user_id?: number
  reason?: string
}

export interface BpmProcessInstanceCopyUpdateDTO extends Partial<BpmProcessInstanceCopyCreateDTO> {
  id: string
}

export interface BpmProcessInstanceCopyPageQuery {
  page?: number
  pageSize?: number

}
