// Auto-generated by Codegen Engine
export interface BpmCategoryDO {
  id: number
  name?: string
  code?: string
  description?: string
  status?: number
  sort?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface BpmCategoryVO {
  id: number
  name?: string
  code?: string
  description?: string
  status?: number
  sort?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface BpmCategoryCreateDTO {
  name?: string
  code?: string
  description?: string
  status?: number
  sort?: number
}

export interface BpmCategoryUpdateDTO extends Partial<BpmCategoryCreateDTO> {
  id: string
}

export interface BpmCategoryPageQuery {
  page?: number
  pageSize?: number

}
