// Auto-generated by Codegen Engine
"use client"

import React, { useState, useEffect } from "react"
import { BargainActivityApi } from "../api/bargain-activity.api"
import type { BargainActivityCreateDTO, BargainActivityVO } from "@/modules/mall/backend/types/bargain-activity.types"

interface BargainActivityFormProps {
  open: boolean
  initialData?: BargainActivityVO | null
  onClose: () => void
  onSuccess: () => void
}

export function BargainActivityForm({ open, initialData, onClose, onSuccess }: BargainActivityFormProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [formData, setFormData] = useState<Record<string, any>>({})

  useEffect(() => {
    if (open) {
      setError(null)
      setFormData({
    name: initialData?.name ?? "",
    start_time: initialData?.start_time ?? "",
    end_time: initialData?.end_time ?? "",
    status: initialData?.status ?? undefined,
    spu_id: initialData?.spu_id ?? undefined,
    sku_id: initialData?.sku_id ?? undefined,
    bargain_first_price: initialData?.bargain_first_price ?? undefined,
    bargain_min_price: initialData?.bargain_min_price ?? undefined,
    stock: initialData?.stock ?? undefined,
    total_stock: initialData?.total_stock ?? undefined,
    help_max_count: initialData?.help_max_count ?? undefined,
    bargain_count: initialData?.bargain_count ?? undefined,
    total_limit_count: initialData?.total_limit_count ?? undefined,
    random_min_price: initialData?.random_min_price ?? undefined,
    random_max_price: initialData?.random_max_price ?? undefined,
      })
    }
  }, [open, initialData])

  if (!open) return null

  const isEdit = Boolean(initialData?.id)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError(null)
    try {
      if (isEdit && initialData?.id) {
        await BargainActivityApi.update({ id: initialData.id, ...formData } as any)
      } else {
        await BargainActivityApi.create(formData as BargainActivityCreateDTO)
      }
      onSuccess()
      onClose()
    } catch (err: any) {
      setError(err?.message || "操作失败")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div data-testid="bargain-activity-form-overlay" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-xs">
      <div
        role="dialog"
        aria-modal="true"
        aria-label={isEdit ? "编辑砍价活动" : "新增砍价活动"}
        data-testid="bargain-activity-form"
        data-agent-scope="bargain-activity:form"
        data-agent-state={loading ? "submitting" : error ? "error" : "open"}
        className="bg-white rounded-lg shadow-xl w-full max-w-lg mx-4 overflow-hidden">
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200">
          <h3 className="text-sm font-semibold text-slate-800">
            {isEdit ? "编辑砍价活动" : "新增砍价活动"}
          </h3>
          <button onClick={onClose} data-testid="bargain-activity-form-close" data-agent-target="bargain-activity:close" aria-label="关闭" className="text-slate-400 hover:text-slate-600 text-lg leading-none">&times;</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="px-6 py-4 space-y-3 max-h-[70vh] overflow-y-auto">
            {error && (
              <div data-testid="bargain-activity-form-error" role="alert" className="p-2 text-xs text-red-600 bg-red-50 rounded border border-red-200">{error}</div>
            )}
        <div>
          <label htmlFor="bargain-activity-name" className="block text-xs text-slate-600 mb-1">砍价活动名称</label>
          <input
            type="text"
            id="bargain-activity-name"
            data-testid="field-name"
            data-agent-target="bargain-activity:field:name"
            data-agent-state={formData.name ? "filled" : "empty"}
            aria-label="砍价活动名称"
            value={formData.name ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入砍价活动名称"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-start_time" className="block text-xs text-slate-600 mb-1">活动开始时间</label>
          <input
            type="text"
            id="bargain-activity-start_time"
            data-testid="field-start_time"
            data-agent-target="bargain-activity:field:start_time"
            data-agent-state={formData.start_time ? "filled" : "empty"}
            aria-label="活动开始时间"
            value={formData.start_time ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, start_time: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入活动开始时间"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-end_time" className="block text-xs text-slate-600 mb-1">活动结束时间</label>
          <input
            type="text"
            id="bargain-activity-end_time"
            data-testid="field-end_time"
            data-agent-target="bargain-activity:field:end_time"
            data-agent-state={formData.end_time ? "filled" : "empty"}
            aria-label="活动结束时间"
            value={formData.end_time ?? ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, end_time: e.target.value }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入活动结束时间"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-status" className="block text-xs text-slate-600 mb-1">活动状态</label>
          <input
            type="number"
            id="bargain-activity-status"
            data-testid="field-status"
            data-agent-target="bargain-activity:field:status"
            data-agent-state={formData.status == null || formData.status === "" ? "empty" : "filled"}
            aria-label="活动状态"
            value={formData.status != null ? String(formData.status) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, status: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入活动状态"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-spu_id" className="block text-xs text-slate-600 mb-1">商品 SPU 编号</label>
          <input
            type="number"
            id="bargain-activity-spu_id"
            data-testid="field-spu_id"
            data-agent-target="bargain-activity:field:spu_id"
            data-agent-state={formData.spu_id == null || formData.spu_id === "" ? "empty" : "filled"}
            aria-label="商品 SPU 编号"
            value={formData.spu_id != null ? String(formData.spu_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, spu_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入商品 SPU 编号"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-sku_id" className="block text-xs text-slate-600 mb-1">商品 SKU 编号</label>
          <input
            type="number"
            id="bargain-activity-sku_id"
            data-testid="field-sku_id"
            data-agent-target="bargain-activity:field:sku_id"
            data-agent-state={formData.sku_id == null || formData.sku_id === "" ? "empty" : "filled"}
            aria-label="商品 SKU 编号"
            value={formData.sku_id != null ? String(formData.sku_id) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, sku_id: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入商品 SKU 编号"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-bargain_first_price" className="block text-xs text-slate-600 mb-1">砍价起始价格，单位：分</label>
          <input
            type="number"
            id="bargain-activity-bargain_first_price"
            data-testid="field-bargain_first_price"
            data-agent-target="bargain-activity:field:bargain_first_price"
            data-agent-state={formData.bargain_first_price == null || formData.bargain_first_price === "" ? "empty" : "filled"}
            aria-label="砍价起始价格，单位：分"
            value={formData.bargain_first_price != null ? String(formData.bargain_first_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, bargain_first_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入砍价起始价格，单位：分"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-bargain_min_price" className="block text-xs text-slate-600 mb-1">砍价底价，单位：分</label>
          <input
            type="number"
            id="bargain-activity-bargain_min_price"
            data-testid="field-bargain_min_price"
            data-agent-target="bargain-activity:field:bargain_min_price"
            data-agent-state={formData.bargain_min_price == null || formData.bargain_min_price === "" ? "empty" : "filled"}
            aria-label="砍价底价，单位：分"
            value={formData.bargain_min_price != null ? String(formData.bargain_min_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, bargain_min_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入砍价底价，单位：分"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-stock" className="block text-xs text-slate-600 mb-1">砍价库存(剩余库存砍价时扣减)</label>
          <input
            type="number"
            id="bargain-activity-stock"
            data-testid="field-stock"
            data-agent-target="bargain-activity:field:stock"
            data-agent-state={formData.stock == null || formData.stock === "" ? "empty" : "filled"}
            aria-label="砍价库存(剩余库存砍价时扣减)"
            value={formData.stock != null ? String(formData.stock) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, stock: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入砍价库存(剩余库存砍价时扣减)"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-total_stock" className="block text-xs text-slate-600 mb-1">砍价总库存</label>
          <input
            type="number"
            id="bargain-activity-total_stock"
            data-testid="field-total_stock"
            data-agent-target="bargain-activity:field:total_stock"
            data-agent-state={formData.total_stock == null || formData.total_stock === "" ? "empty" : "filled"}
            aria-label="砍价总库存"
            value={formData.total_stock != null ? String(formData.total_stock) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, total_stock: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入砍价总库存"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-help_max_count" className="block text-xs text-slate-600 mb-1">砍价人数</label>
          <input
            type="number"
            id="bargain-activity-help_max_count"
            data-testid="field-help_max_count"
            data-agent-target="bargain-activity:field:help_max_count"
            data-agent-state={formData.help_max_count == null || formData.help_max_count === "" ? "empty" : "filled"}
            aria-label="砍价人数"
            value={formData.help_max_count != null ? String(formData.help_max_count) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, help_max_count: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入砍价人数"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-bargain_count" className="block text-xs text-slate-600 mb-1">帮砍次数</label>
          <input
            type="number"
            id="bargain-activity-bargain_count"
            data-testid="field-bargain_count"
            data-agent-target="bargain-activity:field:bargain_count"
            data-agent-state={formData.bargain_count == null || formData.bargain_count === "" ? "empty" : "filled"}
            aria-label="帮砍次数"
            value={formData.bargain_count != null ? String(formData.bargain_count) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, bargain_count: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入帮砍次数"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-total_limit_count" className="block text-xs text-slate-600 mb-1">总限购数量</label>
          <input
            type="number"
            id="bargain-activity-total_limit_count"
            data-testid="field-total_limit_count"
            data-agent-target="bargain-activity:field:total_limit_count"
            data-agent-state={formData.total_limit_count == null || formData.total_limit_count === "" ? "empty" : "filled"}
            aria-label="总限购数量"
            value={formData.total_limit_count != null ? String(formData.total_limit_count) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, total_limit_count: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入总限购数量"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-random_min_price" className="block text-xs text-slate-600 mb-1">用户每次砍价的最小金额，单位：分</label>
          <input
            type="number"
            id="bargain-activity-random_min_price"
            data-testid="field-random_min_price"
            data-agent-target="bargain-activity:field:random_min_price"
            data-agent-state={formData.random_min_price == null || formData.random_min_price === "" ? "empty" : "filled"}
            aria-label="用户每次砍价的最小金额，单位：分"
            value={formData.random_min_price != null ? String(formData.random_min_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, random_min_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入用户每次砍价的最小金额，单位：分"
            
          />
        </div>

        <div>
          <label htmlFor="bargain-activity-random_max_price" className="block text-xs text-slate-600 mb-1">用户每次砍价的最大金额，单位：分</label>
          <input
            type="number"
            id="bargain-activity-random_max_price"
            data-testid="field-random_max_price"
            data-agent-target="bargain-activity:field:random_max_price"
            data-agent-state={formData.random_max_price == null || formData.random_max_price === "" ? "empty" : "filled"}
            aria-label="用户每次砍价的最大金额，单位：分"
            value={formData.random_max_price != null ? String(formData.random_max_price) : ""}
            onChange={(e) => setFormData((prev) => ({ ...prev, random_max_price: e.target.value === "" ? undefined : Number(e.target.value) }))}
            className="w-full px-3 py-1.5 border border-slate-300 rounded text-xs focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
            placeholder="请输入用户每次砍价的最大金额，单位：分"
            
          />
        </div>
          </div>

          <div className="flex items-center justify-end gap-2 px-6 py-3 border-t border-slate-200 bg-slate-50">
            <button
              type="button"
              onClick={onClose}
              data-testid="bargain-activity-form-cancel"
              data-agent-target="bargain-activity:cancel"
              className="px-4 py-1.5 text-xs text-slate-600 hover:text-slate-800 border border-slate-300 rounded hover:bg-slate-100 transition-colors"
            >
              取消
            </button>
            <button
              type="submit"
              disabled={loading}
              data-testid="bargain-activity-form-submit"
              data-agent-target="bargain-activity:submit"
              data-agent-state={loading ? "busy" : "idle"}
              className="px-4 py-1.5 text-xs text-white bg-blue-600 rounded hover:bg-blue-700 disabled:opacity-50 transition-colors"
            >
              {loading ? "保存中..." : "保存"}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
