// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  ArticleCategoryCreateDTO,
  ArticleCategoryPageQuery,
  ArticleCategoryUpdateDTO,
  ArticleCategoryVO,
} from "@/modules/mall/backend/types/article-category.types"

const BASE_URL = "/api/v1/admin/mall/article-category"

export const ArticleCategoryApi = {
  async page(params?: ArticleCategoryPageQuery) {
    return request.get<{ items: ArticleCategoryVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<ArticleCategoryVO>(`${BASE_URL}/${id}`)
  },

  async create(data: ArticleCategoryCreateDTO) {
    return request.post<ArticleCategoryVO>(BASE_URL, data)
  },

  async update(data: ArticleCategoryUpdateDTO) {
    return request.put<ArticleCategoryVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: ArticleCategoryPageQuery) {
    return request.post<ArticleCategoryVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
