// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  BargainRecordCreateDTO,
  BargainRecordPageQuery,
  BargainRecordUpdateDTO,
  BargainRecordVO,
} from "@/modules/mall/backend/types/bargain-record.types"

const BASE_URL = "/api/v1/admin/mall/bargain-record"

export const BargainRecordApi = {
  async page(params?: BargainRecordPageQuery) {
    return request.get<{ items: BargainRecordVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<BargainRecordVO>(`${BASE_URL}/${id}`)
  },

  async create(data: BargainRecordCreateDTO) {
    return request.post<BargainRecordVO>(BASE_URL, data)
  },

  async update(data: BargainRecordUpdateDTO) {
    return request.put<BargainRecordVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: BargainRecordPageQuery) {
    return request.post<BargainRecordVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
