// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  DiyTemplateCreateDTO,
  DiyTemplatePageQuery,
  DiyTemplateUpdateDTO,
  DiyTemplateVO,
} from "@/modules/mall/backend/types/diy-template.types"

const BASE_URL = "/api/v1/admin/mall/diy-template"

export const DiyTemplateApi = {
  async page(params?: DiyTemplatePageQuery) {
    return request.get<{ items: DiyTemplateVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<DiyTemplateVO>(`${BASE_URL}/${id}`)
  },

  async create(data: DiyTemplateCreateDTO) {
    return request.post<DiyTemplateVO>(BASE_URL, data)
  },

  async update(data: DiyTemplateUpdateDTO) {
    return request.put<DiyTemplateVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: DiyTemplatePageQuery) {
    return request.post<DiyTemplateVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
