// Auto-generated by Codegen Engine (App Router Page)
import { MesWmMiscReceiptLineListPage } from "@/modules/mes/frontend/pages/mes-wm-misc-receipt-line-list.page"

export default function Page() {
  return <MesWmMiscReceiptLineListPage />
}
