// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { WmsMerchantService } from "../wms-merchant.service"

describe("WmsMerchantService", () => {
  it("should create and query 货主管理", async () => {
    const created = await WmsMerchantService.create({
      code: "测试货主管理",
    } as any)
    expect(created).toBeDefined()
    expect(created.id).toBeDefined()

    const list = await WmsMerchantService.page({ page: 1, pageSize: 10 })
    expect(list.items.length).toBeGreaterThan(0)

    const fetched = await WmsMerchantService.get(created.id)
    expect(fetched).toBeDefined()
    expect(fetched?.id).toBe(created.id)

    const updated = await WmsMerchantService.update(created.id, {
      id: created.id,
      code: "更新货主管理",
    } as any)
    expect(updated).toBeDefined()

    const deleted = await WmsMerchantService.delete(created.id)
    expect(deleted).toBe(true)
  })
})
