// Auto-generated by Codegen Engine (App Router Page)
import { ProductSpuListPage } from "@/modules/mall/frontend/pages/product-spu-list.page"

export default function Page() {
  return <ProductSpuListPage />
}
