// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { MpTagRepository } from "../repositories/mp-tag.repository"
import type {
  MpTagCreateDTO,
  MpTagPageQuery,
  MpTagUpdateDTO,
} from "../types/mp-tag.types"

export class MpTagService {
  static async page(query: MpTagPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return MpTagRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return MpTagRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: MpTagCreateDTO, actorId?: string, tenantId?: string) {
    const row = await MpTagRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mp.mpTag.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: MpTagUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await MpTagRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mp.mpTag.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await MpTagRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mp.mpTag.deleted", { id, actorId })
    }
    return ok
  }
}

export const mpTagService = MpTagService
