import { readFileSync } from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"
import { listDomainCatalog } from "../../constants/domain-catalog"
import rpcActions from "../../constants/rpc-actions.json"
import { grpcMethodPath } from "../grpc-fabric"

describe("rpc action contracts", () => {
  it("covers every catalog domain", () => {
    const names = listDomainCatalog().map((domain) => domain.name)
    expect(Object.keys(rpcActions.domains).sort()).toEqual([...names].sort())
  })

  it("keeps gRPC paths aligned with generated proto and Go stubs", () => {
    expect(grpcMethodPath("pay", "createOrder")).toBe("/ruoyi.pay.v1.PayService/CreateOrder")
    expect(grpcMethodPath("mall", "issueCoupon")).toBe("/ruoyi.mall.v1.MallService/IssueCoupon")
    expect(rpcActions.domains.pay.actions.map((item) => item.method)).toEqual([
      "ping",
      "listOrders",
      "createOrder",
      "createRefund",
      "listRefunds",
    ])
    expect(rpcActions.domains.system.actions.map((item) => item.method)).toEqual([
      "ping",
      "getDictDataByType",
      "resolveTenantEntitlement",
      "listUsers",
      "createUser",
      "listRoles",
      "createRole",
      "listMenus",
      "treeMenus",
      "createMenu",
      "listDepts",
      "treeDepts",
      "createDept",
      "listPosts",
      "createPost",
      "listDictTypes",
      "createDictType",
      "listTenants",
      "createTenant",
      "getUser",
      "updateUser",
      "deleteUser",
      "resetUserPassword",
      "updateUserStatus",
      "getRole",
      "updateRole",
      "deleteRole",
      "updateRoleStatus",
      "getMenu",
      "updateMenu",
      "deleteMenu",
      "getDept",
      "updateDept",
      "deleteDept",
      "getPost",
      "updatePost",
      "deletePost",
      "getDictType",
      "updateDictType",
      "deleteDictType",
      "getTenant",
      "updateTenant",
      "deleteTenant",
      "updateTenantStatus",
      "listDictData",
      "createDictData",
      "getDictData",
      "updateDictData",
      "deleteDictData",
      "listTenantPackages",
      "createTenantPackage",
      "getTenantPackage",
      "updateTenantPackage",
      "deleteTenantPackage",
      "assignTenantPackage",
      "getTenantSubscriptions",
      "getRoleMenus",
      "assignRoleMenu",
      "assignUserRole",
      "pageLoginLogs",
      "getLoginLog",
      "exportLoginLogs",
      "pageOperateLogs",
      "getOperateLog",
      "exportOperateLogs",
      "listOnlineUsers",
      "forceLogoutOnlineUser",
      "pageNotices",
      "createNotice",
      "getNotice",
      "updateNotice",
      "deleteNotice",
      "listOauth2Clients",
      "listOauth2Tokens",
      "listSocialUsers",
      "createSocialUser",
      "listMailAccounts",
      "createMailAccount",
      "listMailLogs",
      "listSmsChannels",
      "createSmsChannel",
      "listSmsLogs",
      "pageNotifyMessages",
      "createNotifyMessage",
      "pageNotifyTemplates",
      "createNotifyTemplate",
      "pageIpAreas",
      "pageAreas",
      "createArea",
      "getArea",
      "updateArea",
      "deleteArea",
      "login",
      "getPermissionInfoByUser",
      "refreshAccessToken",
      "logout",
      "generateCaptcha",
      "verifyCaptcha",
      "getUserProfile",
      "updateUserProfile",
      "getSidebarNav",
      "openOauth2Token",
      "getOauth2UserInfo",
      "listMailTemplates",
      "createMailTemplate",
      "getMailTemplate",
      "updateMailTemplate",
      "deleteMailTemplate",
      "listSmsTemplates",
      "createSmsTemplate",
      "getSmsTemplate",
      "updateSmsTemplate",
      "deleteSmsTemplate",
      "listSocialClients",
      "createSocialClient",
      "getSocialClient",
      "updateSocialClient",
      "deleteSocialClient",
    ])
    expect(rpcActions.domains.infra.actions.map((item) => item.method)).toEqual([
      "ping",
      "updateConfig",
      "previewCodegen",
      "generateCodegen",
      "previewTemplate",
      "generateTemplate",
      "listQueryDataSources",
      "getQueryConnection",
      "listConfigs",
      "getConfigByKey",
      "createConfig",
      "listJobs",
      "createJob",
      "listFiles",
      "recordFile",
      "pageDataSourceConfigs",
      "getConfig",
      "updateConfigItem",
      "deleteConfig",
      "getJob",
      "updateJob",
      "deleteJob",
      "triggerJob",
      "updateJobStatus",
      "getFile",
      "deleteFile",
      "listPages",
      "getPage",
      "getPageBySlug",
      "pageApiErrorLogs",
      "getApiErrorLog",
      "processApiErrorLog",
      "pageApiAccessLogs",
      "getApiAccessLog",
      "testDataSourceConnection",
      "listCodegenTables",
      "getCodegenTable",
      "updateCodegenTable",
      "deleteCodegenTable",
      "deleteCodegenTables",
      "exportApiAccessLogs",
      "exportApiErrorLogs",
      "runAuditLogRetention",
      "listCodegenCandidates",
      "importCodegenTables",
      "generateCodegenArchive",
      "listCodegenCatalog",
    ])
    expect(grpcMethodPath("system", "getDictDataByType")).toBe("/ruoyi.system.v1.SystemService/GetDictDataByType")
    expect(grpcMethodPath("system", "resolveTenantEntitlement")).toBe("/ruoyi.system.v1.SystemService/ResolveTenantEntitlement")
    expect(rpcActions.exposure.system.public).toEqual(["getDictDataByType", "getPermissionInfoByUser"])
    expect(rpcActions.exposure.infra.public).toEqual([])
    const goStub = readFileSync(path.resolve(process.cwd(), "gen/go/pay/v1/service.go"), "utf8")
    expect(goStub).toContain('CreateOrderPath = "/ruoyi.pay.v1.PayService/CreateOrder"')
    expect(goStub).toContain("type PayService interface")
    expect(goStub).toContain("func (c *Client) CreateOrder")
  })
})
