// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  wmsItemCreateSchema,
  wmsItemPageQuerySchema,
  wmsItemUpdateSchema,
} from "../backend/validators/wms-item.validator"

export const wmsItemActionSchemas = {
  "ruoyi.cmd.wms.wmsItem.page": wmsItemPageQuerySchema,
  "ruoyi.cmd.wms.wmsItem.get": z.object({ id: z.string() }),
  "ruoyi.cmd.wms.wmsItem.create": wmsItemCreateSchema,
  "ruoyi.cmd.wms.wmsItem.update": wmsItemUpdateSchema,
  "ruoyi.cmd.wms.wmsItem.delete": z.object({ id: z.string() }),
} as const
