// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { PayNotifyLogService } from "../pay-notify-log.service"

describe("PayNotifyLogService", () => {
  it("should create and query 商户支付、退款等的通知 Log每次通知时，都会在该表中，记录一次 Log，方便排查问题", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await PayNotifyLogService.create({
        task_id: 1,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await PayNotifyLogService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await PayNotifyLogService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await PayNotifyLogService.update(created.id, {
        id: created.id,
        task_id: "更新商户支付、退款等的通知 Log每次通知时，都会在该表中，记录一次 Log，方便排查问题",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await PayNotifyLogService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
