// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MemberConfigService } from "../member-config.service"

describe("MemberConfigService", () => {
  it("should create and query 会员配置", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MemberConfigService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MemberConfigService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MemberConfigService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MemberConfigService.update(created.id, {
        id: created.id,
          point_trade_deduct_enable: true,
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MemberConfigService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
