// Auto-generated by Codegen Engine (App Router Page)
import { MesProAndonRecordListPage } from "@/modules/mes/frontend/pages/mes-pro-andon-record-list.page"

export default function Page() {
  return <MesProAndonRecordListPage />
}
