// Auto-generated by Codegen Engine
export interface IotThingModelDO {
  id: number
  identifier?: string
  name?: string
  description?: string
  product_id?: number
  product_key?: string
  type?: number
  property?: string
  event?: string
  service?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface IotThingModelVO {
  id: number
  identifier?: string
  name?: string
  description?: string
  product_id?: number
  product_key?: string
  type?: number
  property?: string
  event?: string
  service?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface IotThingModelCreateDTO {
  identifier?: string
  name?: string
  description?: string
  product_id?: number
  product_key?: string
  type?: number
  property?: string
  event?: string
  service?: string
}

export interface IotThingModelUpdateDTO extends Partial<IotThingModelCreateDTO> {
  id: string
}

export interface IotThingModelPageQuery {
  page?: number
  pageSize?: number

}
