// Auto-generated by Codegen Engine
export interface BrokerageUserDO {
  id: number
  bind_user_id?: number
  bind_user_time?: string
  brokerage_enabled?: boolean
  brokerage_time?: string
  brokerage_price?: number
  frozen_price?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface BrokerageUserVO {
  id: number
  bind_user_id?: number
  bind_user_time?: string
  brokerage_enabled?: boolean
  brokerage_time?: string
  brokerage_price?: number
  frozen_price?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface BrokerageUserCreateDTO {
  bind_user_id?: number
  bind_user_time?: string
  brokerage_enabled?: boolean
  brokerage_time?: string
  brokerage_price?: number
  frozen_price?: number
}

export interface BrokerageUserUpdateDTO extends Partial<BrokerageUserCreateDTO> {
  id: string
}

export interface BrokerageUserPageQuery {
  page?: number
  pageSize?: number

}
