// Auto-generated by Codegen Engine
export interface DeliveryPickUpStoreDO {
  id: number
  name?: string
  introduction?: string
  phone?: string
  area_id?: number
  detail_address?: string
  logo?: string
  opening_time?: string
  closing_time?: string
  latitude?: number
  longitude?: number
  verify_user_ids?: string
  status?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface DeliveryPickUpStoreVO {
  id: number
  name?: string
  introduction?: string
  phone?: string
  area_id?: number
  detail_address?: string
  logo?: string
  opening_time?: string
  closing_time?: string
  latitude?: number
  longitude?: number
  verify_user_ids?: string
  status?: number
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface DeliveryPickUpStoreCreateDTO {
  name?: string
  introduction?: string
  phone?: string
  area_id?: number
  detail_address?: string
  logo?: string
  opening_time?: string
  closing_time?: string
  latitude?: number
  longitude?: number
  verify_user_ids?: string
  status?: number
}

export interface DeliveryPickUpStoreUpdateDTO extends Partial<DeliveryPickUpStoreCreateDTO> {
  id: string
}

export interface DeliveryPickUpStorePageQuery {
  page?: number
  pageSize?: number

}
