// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { ImChannelMessageService } from "../im-channel-message.service"

describe("ImChannelMessageService", () => {
  it("should create and query IM 频道消息 DO业务语义：- 一次推送 1 行； 为空表示全员- 冗余 便于按频道检索- 存推送时 payload 的 JSON 快照（title / coverUrl / summa", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await ImChannelMessageService.create({
        channel_id: 1,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await ImChannelMessageService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await ImChannelMessageService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await ImChannelMessageService.update(created.id, {
        id: created.id,
        channel_id: "更新IM 频道消息 DO业务语义：- 一次推送 1 行； 为空表示全员- 冗余 便于按频道检索- 存推送时 payload 的 JSON 快照（title / coverUrl / summa",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await ImChannelMessageService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
