// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { ImChannelService } from "../im-channel.service"

describe("ImChannelService", () => {
  it("should create and query ImChannel（源框架导入）", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await ImChannelService.create({
        code: "测试ImChannel（源框架导入）",
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await ImChannelService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await ImChannelService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await ImChannelService.update(created.id, {
        id: created.id,
        code: "更新ImChannel（源框架导入）",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await ImChannelService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
