// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { ImChannelMaterialService } from "../im-channel-material.service"

describe("ImChannelMaterialService", () => {
  it("should create and query IM 频道素材 DO业务语义：- 运营素材库，可被反复推送- 一条素材 1:N ", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await ImChannelMaterialService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await ImChannelMaterialService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await ImChannelMaterialService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await ImChannelMaterialService.update(created.id, {
        id: created.id,
          channel_id: "测试更新IM 频道素材 DO业务语义：- 运营素材库，可被反复推送- 一条素材 1:N ",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await ImChannelMaterialService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
