// Auto-generated by Codegen Engine
export interface MesDvMachineryTypeDO {
  id: number
  code?: string
  name?: string
  parent_id?: number
  status?: number
  sort?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesDvMachineryTypeVO {
  id: number
  code?: string
  name?: string
  parent_id?: number
  status?: number
  sort?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesDvMachineryTypeCreateDTO {
  code?: string
  name?: string
  parent_id?: number
  status?: number
  sort?: number
  remark?: string
}

export interface MesDvMachineryTypeUpdateDTO extends Partial<MesDvMachineryTypeCreateDTO> {
  id: string
}

export interface MesDvMachineryTypePageQuery {
  page?: number
  pageSize?: number

}
