// Auto-generated by Codegen Engine
export interface MesMdUnitMeasureDO {
  id: number
  code?: string
  name?: string
  primary_flag?: boolean
  primary_id?: number
  change_rate?: number
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesMdUnitMeasureVO {
  id: number
  code?: string
  name?: string
  primary_flag?: boolean
  primary_id?: number
  change_rate?: number
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesMdUnitMeasureCreateDTO {
  code?: string
  name?: string
  primary_flag?: boolean
  primary_id?: number
  change_rate?: number
  status?: number
  remark?: string
}

export interface MesMdUnitMeasureUpdateDTO extends Partial<MesMdUnitMeasureCreateDTO> {
  id: string
}

export interface MesMdUnitMeasurePageQuery {
  page?: number
  pageSize?: number

}
