// Auto-generated by Codegen Engine
export interface MesWmItemReceiptDO {
  id: number
  code?: string
  name?: string
  iqc_id?: number
  notice_id?: number
  purchase_order_code?: string
  vendor_id?: number
  receipt_date?: string
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmItemReceiptVO {
  id: number
  code?: string
  name?: string
  iqc_id?: number
  notice_id?: number
  purchase_order_code?: string
  vendor_id?: number
  receipt_date?: string
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmItemReceiptCreateDTO {
  code?: string
  name?: string
  iqc_id?: number
  notice_id?: number
  purchase_order_code?: string
  vendor_id?: number
  receipt_date?: string
  status?: number
  remark?: string
}

export interface MesWmItemReceiptUpdateDTO extends Partial<MesWmItemReceiptCreateDTO> {
  id: string
}

export interface MesWmItemReceiptPageQuery {
  page?: number
  pageSize?: number

}
