// Auto-generated by Codegen Engine
export interface MesWmProductReceiptDO {
  id: number
  code?: string
  name?: string
  work_order_id?: number
  item_id?: number
  receipt_date?: string
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmProductReceiptVO {
  id: number
  code?: string
  name?: string
  work_order_id?: number
  item_id?: number
  receipt_date?: string
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmProductReceiptCreateDTO {
  code?: string
  name?: string
  work_order_id?: number
  item_id?: number
  receipt_date?: string
  status?: number
  remark?: string
}

export interface MesWmProductReceiptUpdateDTO extends Partial<MesWmProductReceiptCreateDTO> {
  id: string
}

export interface MesWmProductReceiptPageQuery {
  page?: number
  pageSize?: number

}
