// Auto-generated by Codegen Engine
export interface MesProWorkRecordDO {
  id: number
  user_id?: number
  workstation_id?: number
  type?: number
  clock_in_time?: string
  clock_out_time?: string
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesProWorkRecordVO {
  id: number
  user_id?: number
  workstation_id?: number
  type?: number
  clock_in_time?: string
  clock_out_time?: string
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesProWorkRecordCreateDTO {
  user_id?: number
  workstation_id?: number
  type?: number
  clock_in_time?: string
  clock_out_time?: string
  remark?: string
}

export interface MesProWorkRecordUpdateDTO extends Partial<MesProWorkRecordCreateDTO> {
  id: string
}

export interface MesProWorkRecordPageQuery {
  page?: number
  pageSize?: number

}
