// Auto-generated by Codegen Engine
export interface MesWmWarehouseAreaDO {
  id: number
  code?: string
  name?: string
  location_id?: number
  area?: number
  max_load?: number
  position_x?: number
  position_y?: number
  position_z?: number
  status?: number
  frozen?: boolean
  allow_item_mixing?: boolean
  allow_batch_mixing?: boolean
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmWarehouseAreaVO {
  id: number
  code?: string
  name?: string
  location_id?: number
  area?: number
  max_load?: number
  position_x?: number
  position_y?: number
  position_z?: number
  status?: number
  frozen?: boolean
  allow_item_mixing?: boolean
  allow_batch_mixing?: boolean
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmWarehouseAreaCreateDTO {
  code?: string
  name?: string
  location_id?: number
  area?: number
  max_load?: number
  position_x?: number
  position_y?: number
  position_z?: number
  status?: number
  frozen?: boolean
  allow_item_mixing?: boolean
  allow_batch_mixing?: boolean
  remark?: string
}

export interface MesWmWarehouseAreaUpdateDTO extends Partial<MesWmWarehouseAreaCreateDTO> {
  id: string
}

export interface MesWmWarehouseAreaPageQuery {
  page?: number
  pageSize?: number

}
