// Auto-generated by Codegen Engine
export interface MesWmItemConsumeDO {
  id: number
  work_order_id?: number
  task_id?: number
  workstation_id?: number
  process_id?: number
  feedback_id?: number
  consume_date?: string
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmItemConsumeVO {
  id: number
  work_order_id?: number
  task_id?: number
  workstation_id?: number
  process_id?: number
  feedback_id?: number
  consume_date?: string
  status?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmItemConsumeCreateDTO {
  work_order_id?: number
  task_id?: number
  workstation_id?: number
  process_id?: number
  feedback_id?: number
  consume_date?: string
  status?: number
  remark?: string
}

export interface MesWmItemConsumeUpdateDTO extends Partial<MesWmItemConsumeCreateDTO> {
  id: string
}

export interface MesWmItemConsumePageQuery {
  page?: number
  pageSize?: number

}
