// Auto-generated by Codegen Engine
export interface MesWmProductIssueLineDO {
  id: number
  issue_id?: number
  item_id?: number
  quantity?: number
  batch_id?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmProductIssueLineVO {
  id: number
  issue_id?: number
  item_id?: number
  quantity?: number
  batch_id?: number
  remark?: string
  tenant_id: string
  created_by?: string
  created_at: string
  updated_by?: string
  updated_at: string
  deleted: boolean
}

export interface MesWmProductIssueLineCreateDTO {
  issue_id?: number
  item_id?: number
  quantity?: number
  batch_id?: number
  remark?: string
}

export interface MesWmProductIssueLineUpdateDTO extends Partial<MesWmProductIssueLineCreateDTO> {
  id: string
}

export interface MesWmProductIssueLinePageQuery {
  page?: number
  pageSize?: number

}
