// Auto-generated by Codegen Engine
import { z } from "zod"



export const crmBusinessPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const crmBusinessCreateSchema = z.object({
  name: z.string().trim().optional(),
  customer_id: z.coerce.number().finite().optional(),
  follow_up_status: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),
  contact_last_time: z.string().trim().optional(),
  contact_next_time: z.string().trim().optional(),
  owner_user_id: z.coerce.number().finite().optional(),
  status_type_id: z.coerce.number().finite().optional(),
  status_id: z.coerce.number().finite().optional(),
  end_status: z.coerce.number().finite().optional(),
  end_remark: z.string().trim().optional(),
  deal_time: z.string().trim().optional(),
  total_product_price: z.coerce.number().finite().optional(),
  discount_percent: z.coerce.number().finite().optional(),
  total_price: z.coerce.number().finite().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const crmBusinessUpdateSchema = crmBusinessCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type CrmBusinessPageQueryInput = z.infer<typeof crmBusinessPageQuerySchema>
export type CrmBusinessCreateInput = z.infer<typeof crmBusinessCreateSchema>
export type CrmBusinessUpdateInput = z.infer<typeof crmBusinessUpdateSchema>
