// Auto-generated by Codegen Engine (App Router Page)
import { ErpPurchaseInListPage } from "@/modules/erp/frontend/pages/erp-purchase-in-list.page"

export default function Page() {
  return <ErpPurchaseInListPage />
}
