// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  mesMdAutoCodePartCreateSchema,
  mesMdAutoCodePartPageQuerySchema,
  mesMdAutoCodePartUpdateSchema,
} from "../backend/validators/mes-md-auto-code-part.validator"

export const mesMdAutoCodePartActionSchemas = {
  "ruoyi.cmd.mes.mesMdAutoCodePart.page": mesMdAutoCodePartPageQuerySchema,
  "ruoyi.cmd.mes.mesMdAutoCodePart.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mes.mesMdAutoCodePart.create": mesMdAutoCodePartCreateSchema,
  "ruoyi.cmd.mes.mesMdAutoCodePart.update": mesMdAutoCodePartUpdateSchema,
  "ruoyi.cmd.mes.mesMdAutoCodePart.delete": z.object({ id: z.string() }),
  "mes.pageMesMdAutoCodePart": mesMdAutoCodePartPageQuerySchema,
  "mes.getMesMdAutoCodePart": z.object({ id: z.string() }),
  "mes.createMesMdAutoCodePart": mesMdAutoCodePartCreateSchema,
  "mes.updateMesMdAutoCodePart": mesMdAutoCodePartUpdateSchema,
  "mes.deleteMesMdAutoCodePart": z.object({ id: z.string() }),
} as const

export const MES_MD_AUTO_CODE_PART_ACTION_SCHEMAS = mesMdAutoCodePartActionSchemas

export function registerActionSchemas() {
  return mesMdAutoCodePartActionSchemas
}
