// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  mesWmStockTakingPlanCreateSchema,
  mesWmStockTakingPlanPageQuerySchema,
  mesWmStockTakingPlanUpdateSchema,
} from "../backend/validators/mes-wm-stock-taking-plan.validator"

export const mesWmStockTakingPlanActionSchemas = {
  "ruoyi.cmd.mes.mesWmStockTakingPlan.page": mesWmStockTakingPlanPageQuerySchema,
  "ruoyi.cmd.mes.mesWmStockTakingPlan.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mes.mesWmStockTakingPlan.create": mesWmStockTakingPlanCreateSchema,
  "ruoyi.cmd.mes.mesWmStockTakingPlan.update": mesWmStockTakingPlanUpdateSchema,
  "ruoyi.cmd.mes.mesWmStockTakingPlan.delete": z.object({ id: z.string() }),
  "mes.pageMesWmStockTakingPlan": mesWmStockTakingPlanPageQuerySchema,
  "mes.getMesWmStockTakingPlan": z.object({ id: z.string() }),
  "mes.createMesWmStockTakingPlan": mesWmStockTakingPlanCreateSchema,
  "mes.updateMesWmStockTakingPlan": mesWmStockTakingPlanUpdateSchema,
  "mes.deleteMesWmStockTakingPlan": z.object({ id: z.string() }),
} as const

export const MES_WM_STOCK_TAKING_PLAN_ACTION_SCHEMAS = mesWmStockTakingPlanActionSchemas

export function registerActionSchemas() {
  return mesWmStockTakingPlanActionSchemas
}
