// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  mesWmStockTakingTaskLineCreateSchema,
  mesWmStockTakingTaskLinePageQuerySchema,
  mesWmStockTakingTaskLineUpdateSchema,
} from "../backend/validators/mes-wm-stock-taking-task-line.validator"

export const mesWmStockTakingTaskLineActionSchemas = {
  "ruoyi.cmd.mes.mesWmStockTakingTaskLine.page": mesWmStockTakingTaskLinePageQuerySchema,
  "ruoyi.cmd.mes.mesWmStockTakingTaskLine.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mes.mesWmStockTakingTaskLine.create": mesWmStockTakingTaskLineCreateSchema,
  "ruoyi.cmd.mes.mesWmStockTakingTaskLine.update": mesWmStockTakingTaskLineUpdateSchema,
  "ruoyi.cmd.mes.mesWmStockTakingTaskLine.delete": z.object({ id: z.string() }),
  "mes.pageMesWmStockTakingTaskLine": mesWmStockTakingTaskLinePageQuerySchema,
  "mes.getMesWmStockTakingTaskLine": z.object({ id: z.string() }),
  "mes.createMesWmStockTakingTaskLine": mesWmStockTakingTaskLineCreateSchema,
  "mes.updateMesWmStockTakingTaskLine": mesWmStockTakingTaskLineUpdateSchema,
  "mes.deleteMesWmStockTakingTaskLine": z.object({ id: z.string() }),
} as const

export const MES_WM_STOCK_TAKING_TASK_LINE_ACTION_SCHEMAS = mesWmStockTakingTaskLineActionSchemas

export function registerActionSchemas() {
  return mesWmStockTakingTaskLineActionSchemas
}
