// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  mesWmMiscIssueLineCreateSchema,
  mesWmMiscIssueLinePageQuerySchema,
  mesWmMiscIssueLineUpdateSchema,
} from "../backend/validators/mes-wm-misc-issue-line.validator"

export const mesWmMiscIssueLineActionSchemas = {
  "ruoyi.cmd.mes.mesWmMiscIssueLine.page": mesWmMiscIssueLinePageQuerySchema,
  "ruoyi.cmd.mes.mesWmMiscIssueLine.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mes.mesWmMiscIssueLine.create": mesWmMiscIssueLineCreateSchema,
  "ruoyi.cmd.mes.mesWmMiscIssueLine.update": mesWmMiscIssueLineUpdateSchema,
  "ruoyi.cmd.mes.mesWmMiscIssueLine.delete": z.object({ id: z.string() }),
  "mes.pageMesWmMiscIssueLine": mesWmMiscIssueLinePageQuerySchema,
  "mes.getMesWmMiscIssueLine": z.object({ id: z.string() }),
  "mes.createMesWmMiscIssueLine": mesWmMiscIssueLineCreateSchema,
  "mes.updateMesWmMiscIssueLine": mesWmMiscIssueLineUpdateSchema,
  "mes.deleteMesWmMiscIssueLine": z.object({ id: z.string() }),
} as const

export const MES_WM_MISC_ISSUE_LINE_ACTION_SCHEMAS = mesWmMiscIssueLineActionSchemas

export function registerActionSchemas() {
  return mesWmMiscIssueLineActionSchemas
}
