// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  mesWmOutsourceReceiptLineCreateSchema,
  mesWmOutsourceReceiptLinePageQuerySchema,
  mesWmOutsourceReceiptLineUpdateSchema,
} from "../backend/validators/mes-wm-outsource-receipt-line.validator"

export const mesWmOutsourceReceiptLineActionSchemas = {
  "ruoyi.cmd.mes.mesWmOutsourceReceiptLine.page": mesWmOutsourceReceiptLinePageQuerySchema,
  "ruoyi.cmd.mes.mesWmOutsourceReceiptLine.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mes.mesWmOutsourceReceiptLine.create": mesWmOutsourceReceiptLineCreateSchema,
  "ruoyi.cmd.mes.mesWmOutsourceReceiptLine.update": mesWmOutsourceReceiptLineUpdateSchema,
  "ruoyi.cmd.mes.mesWmOutsourceReceiptLine.delete": z.object({ id: z.string() }),
  "mes.pageMesWmOutsourceReceiptLine": mesWmOutsourceReceiptLinePageQuerySchema,
  "mes.getMesWmOutsourceReceiptLine": z.object({ id: z.string() }),
  "mes.createMesWmOutsourceReceiptLine": mesWmOutsourceReceiptLineCreateSchema,
  "mes.updateMesWmOutsourceReceiptLine": mesWmOutsourceReceiptLineUpdateSchema,
  "mes.deleteMesWmOutsourceReceiptLine": z.object({ id: z.string() }),
} as const

export const MES_WM_OUTSOURCE_RECEIPT_LINE_ACTION_SCHEMAS = mesWmOutsourceReceiptLineActionSchemas

export function registerActionSchemas() {
  return mesWmOutsourceReceiptLineActionSchemas
}
