// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  mesWmWarehouseCreateSchema,
  mesWmWarehousePageQuerySchema,
  mesWmWarehouseUpdateSchema,
} from "../backend/validators/mes-wm-warehouse.validator"

export const mesWmWarehouseActionSchemas = {
  "ruoyi.cmd.mes.mesWmWarehouse.page": mesWmWarehousePageQuerySchema,
  "ruoyi.cmd.mes.mesWmWarehouse.get": z.object({ id: z.string() }),
  "ruoyi.cmd.mes.mesWmWarehouse.create": mesWmWarehouseCreateSchema,
  "ruoyi.cmd.mes.mesWmWarehouse.update": mesWmWarehouseUpdateSchema,
  "ruoyi.cmd.mes.mesWmWarehouse.delete": z.object({ id: z.string() }),
  "mes.pageMesWmWarehouse": mesWmWarehousePageQuerySchema,
  "mes.getMesWmWarehouse": z.object({ id: z.string() }),
  "mes.createMesWmWarehouse": mesWmWarehouseCreateSchema,
  "mes.updateMesWmWarehouse": mesWmWarehouseUpdateSchema,
  "mes.deleteMesWmWarehouse": z.object({ id: z.string() }),
} as const

export const MES_WM_WAREHOUSE_ACTION_SCHEMAS = mesWmWarehouseActionSchemas

export function registerActionSchemas() {
  return mesWmWarehouseActionSchemas
}
