// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { MpAutoReplyService } from "../mp-auto-reply.service"

describe("MpAutoReplyService", () => {
  it("should create and query 公众号消息自动回复", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await MpAutoReplyService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await MpAutoReplyService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await MpAutoReplyService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await MpAutoReplyService.update(created.id, {
        id: created.id,
          account_id: "测试更新公众号消息自动回复",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await MpAutoReplyService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
