// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { AfterSaleService } from "./after-sale.service"
import { registerActionSchemas } from "../contract/after-sale.actions"
import type {
  AfterSaleCreateDTO,
  AfterSalePageQuery,
  AfterSaleUpdateDTO,
} from "../types/after-sale.types"

export class AfterSaleRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mall.afterSale.page", async (req) => {
      const query = req.data as AfterSalePageQuery
      return AfterSaleService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.afterSale.get", async (req) => {
      const { id } = req.data as { id: string }
      return AfterSaleService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.afterSale.create", async (req) => {
      const data = req.data as AfterSaleCreateDTO
      return AfterSaleService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.afterSale.update", async (req) => {
      const { id, ...rest } = req.data as AfterSaleUpdateDTO
      return AfterSaleService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.afterSale.delete", async (req) => {
      const { id } = req.data as { id: string }
      return AfterSaleService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const afterSaleRpc = AfterSaleRpc

export const afterSaleDomainFacade = createDomainFacade({
  domain: "mall",
  serviceBus,
})
