// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { BargainRecordService } from "./bargain-record.service"
import { registerActionSchemas } from "../contract/bargain-record.actions"
import type {
  BargainRecordCreateDTO,
  BargainRecordPageQuery,
  BargainRecordUpdateDTO,
} from "../types/bargain-record.types"

export class BargainRecordRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mall.bargainRecord.page", async (req) => {
      const query = req.data as BargainRecordPageQuery
      return BargainRecordService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.bargainRecord.get", async (req) => {
      const { id } = req.data as { id: string }
      return BargainRecordService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.bargainRecord.create", async (req) => {
      const data = req.data as BargainRecordCreateDTO
      return BargainRecordService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.bargainRecord.update", async (req) => {
      const { id, ...rest } = req.data as BargainRecordUpdateDTO
      return BargainRecordService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.bargainRecord.delete", async (req) => {
      const { id } = req.data as { id: string }
      return BargainRecordService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const bargainRecordRpc = BargainRecordRpc

export const bargainRecordDomainFacade = createDomainFacade({
  domain: "mall",
  serviceBus,
})
