// Auto-generated by Codegen Engine
// Rule: Cross-domain callers must use createDomainFacade; never import this Service directly.
import { domainLog } from "@/modules/shared/backend/lib/domain-log"
import { BrokerageWithdrawRepository } from "../repositories/brokerage-withdraw.repository"
import type {
  BrokerageWithdrawCreateDTO,
  BrokerageWithdrawPageQuery,
  BrokerageWithdrawUpdateDTO,
} from "../types/brokerage-withdraw.types"

export class BrokerageWithdrawService {
  static async page(query: BrokerageWithdrawPageQuery, actorId?: string, tenantId?: string) {
    const page = query.page ?? 1
    const pageSize = query.pageSize ?? 20
    const filter = { ...query }
    delete (filter as Record<string, unknown>).page
    delete (filter as Record<string, unknown>).pageSize

    return BrokerageWithdrawRepository.page(
      { page, pageSize, ...filter },
      { actorId, tenantId }
    )
  }

  static async get(id: string, actorId?: string, tenantId?: string) {
    return BrokerageWithdrawRepository.findById(id, { actorId, tenantId })
  }

  static async create(data: BrokerageWithdrawCreateDTO, actorId?: string, tenantId?: string) {
    const row = await BrokerageWithdrawRepository.create(data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mall.brokerageWithdraw.created", { id: row.id, actorId })
    return row
  }

  static async update(id: string, data: BrokerageWithdrawUpdateDTO, actorId?: string, tenantId?: string) {
    const row = await BrokerageWithdrawRepository.update(id, data as unknown as Record<string, unknown>, { actorId, tenantId })
    domainLog.event("mall.brokerageWithdraw.updated", { id, actorId })
    return row
  }

  static async delete(id: string, actorId?: string, tenantId?: string) {
    const ok = await BrokerageWithdrawRepository.delete(id, { actorId, tenantId })
    if (ok) {
      domainLog.event("mall.brokerageWithdraw.deleted", { id, actorId })
    }
    return ok
  }
}

export const brokerageWithdrawService = BrokerageWithdrawService
