// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { CombinationActivityService } from "./combination-activity.service"
import { registerActionSchemas } from "../contract/combination-activity.actions"
import type {
  CombinationActivityCreateDTO,
  CombinationActivityPageQuery,
  CombinationActivityUpdateDTO,
} from "../types/combination-activity.types"

export class CombinationActivityRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationActivity.page", async (req) => {
      const query = req.data as CombinationActivityPageQuery
      return CombinationActivityService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationActivity.get", async (req) => {
      const { id } = req.data as { id: string }
      return CombinationActivityService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationActivity.create", async (req) => {
      const data = req.data as CombinationActivityCreateDTO
      return CombinationActivityService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationActivity.update", async (req) => {
      const { id, ...rest } = req.data as CombinationActivityUpdateDTO
      return CombinationActivityService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationActivity.delete", async (req) => {
      const { id } = req.data as { id: string }
      return CombinationActivityService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const combinationActivityRpc = CombinationActivityRpc

export const combinationActivityDomainFacade = createDomainFacade({
  domain: "mall",
  serviceBus,
})
