// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { createDomainFacade } from "@/modules/shared/backend/lib/rpc-facade"
import { CombinationRecordService } from "./combination-record.service"
import { registerActionSchemas } from "../contract/combination-record.actions"
import type {
  CombinationRecordCreateDTO,
  CombinationRecordPageQuery,
  CombinationRecordUpdateDTO,
} from "../types/combination-record.types"

export class CombinationRecordRpc {
  static async register() {
    registerActionSchemas()

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationRecord.page", async (req) => {
      const query = req.data as CombinationRecordPageQuery
      return CombinationRecordService.page(query, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationRecord.get", async (req) => {
      const { id } = req.data as { id: string }
      return CombinationRecordService.get(id, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationRecord.create", async (req) => {
      const data = req.data as CombinationRecordCreateDTO
      return CombinationRecordService.create(data, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationRecord.update", async (req) => {
      const { id, ...rest } = req.data as CombinationRecordUpdateDTO
      return CombinationRecordService.update(id, rest as any, req.actorId, req.tenantId)
    })

    serviceBus.registerHandler("ruoyi.cmd.mall.combinationRecord.delete", async (req) => {
      const { id } = req.data as { id: string }
      return CombinationRecordService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const combinationRecordRpc = CombinationRecordRpc

export const combinationRecordDomainFacade = createDomainFacade({
  domain: "mall",
  serviceBus,
})
