// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  PayOrderExtensionCreateDTO,
  PayOrderExtensionPageQuery,
  PayOrderExtensionUpdateDTO,
  PayOrderExtensionVO,
} from "@/modules/pay/backend/types/pay-order-extension.types"

const BASE_URL = "/api/v1/admin/pay/pay-order-extension"

export const PayOrderExtensionApi = {
  async page(params?: PayOrderExtensionPageQuery) {
    return request.get<{ items: PayOrderExtensionVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<PayOrderExtensionVO>(`${BASE_URL}/${id}`)
  },

  async create(data: PayOrderExtensionCreateDTO) {
    return request.post<PayOrderExtensionVO>(BASE_URL, data)
  },

  async update(data: PayOrderExtensionUpdateDTO) {
    return request.put<PayOrderExtensionVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: PayOrderExtensionPageQuery) {
    return request.post<PayOrderExtensionVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
