// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  PayRefundCreateDTO,
  PayRefundPageQuery,
  PayRefundUpdateDTO,
  PayRefundVO,
} from "@/modules/pay/backend/types/pay-refund.types"

const BASE_URL = "/api/v1/admin/pay/pay-refund"

export const PayRefundApi = {
  async page(params?: PayRefundPageQuery) {
    return request.get<{ items: PayRefundVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<PayRefundVO>(`${BASE_URL}/${id}`)
  },

  async create(data: PayRefundCreateDTO) {
    return request.post<PayRefundVO>(BASE_URL, data)
  },

  async update(data: PayRefundUpdateDTO) {
    return request.put<PayRefundVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: PayRefundPageQuery) {
    return request.post<PayRefundVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
