// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  PayChannelCreateDTO,
  PayChannelPageQuery,
  PayChannelUpdateDTO,
  PayChannelVO,
} from "@/modules/pay/backend/types/pay-channel.types"

const BASE_URL = "/api/v1/admin/pay/pay-channel"

export const PayChannelApi = {
  async page(params?: PayChannelPageQuery) {
    return request.get<{ items: PayChannelVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<PayChannelVO>(`${BASE_URL}/${id}`)
  },

  async create(data: PayChannelCreateDTO) {
    return request.post<PayChannelVO>(BASE_URL, data)
  },

  async update(data: PayChannelUpdateDTO) {
    return request.put<PayChannelVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: PayChannelPageQuery) {
    return request.post<PayChannelVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
