// Auto-generated by Codegen Engine (API Route)
import { NextResponse } from "next/server"
import { withAdminRoute } from "@/modules/shared/backend/http/admin-route"
import { WmsShipmentOrderService } from "@/modules/wms/backend/services/wms-shipment-order.service"
import {
  wmsShipmentOrderCreateSchema,
  wmsShipmentOrderPageQuerySchema,
  wmsShipmentOrderUpdateSchema,
} from "@/modules/wms/backend/validators/wms-shipment-order.validator"
import { PERMISSIONS } from "@/modules/shared/backend/constants/permissions"

const PERM_PREFIX = "WMS_SHIPMENT"
const VIEW_PERM = (PERMISSIONS as Record<string, string>)[`${PERM_PREFIX}_VIEW`] ?? "wms:wms-shipment-order:view"
const CREATE_PERM = (PERMISSIONS as Record<string, string>)[`${PERM_PREFIX}_CREATE`] ?? "wms:wms-shipment-order:create"
const UPDATE_PERM = (PERMISSIONS as Record<string, string>)[`${PERM_PREFIX}_UPDATE`] ?? "wms:wms-shipment-order:update"
const DELETE_PERM = (PERMISSIONS as Record<string, string>)[`${PERM_PREFIX}_DELETE`] ?? "wms:wms-shipment-order:delete"

export const GET = withAdminRoute(async (request, auth) => {
  const { searchParams } = new URL(request.url)
  const raw: Record<string, unknown> = {}
  searchParams.forEach((v, k) => { raw[k] = v })
  const query = wmsShipmentOrderPageQuerySchema.parse(raw)
  const result = await WmsShipmentOrderService.page(query, auth.userId, auth.tenantId)
  return NextResponse.json({ success: true, data: result })
}, { permission: VIEW_PERM })

export const POST = withAdminRoute(async (request, auth) => {
  const body = await request.json()
  const data = wmsShipmentOrderCreateSchema.parse(body)
  const result = await WmsShipmentOrderService.create(data, auth.userId, auth.tenantId)
  return NextResponse.json({ success: true, data: result })
}, { permission: CREATE_PERM })

export const PUT = withAdminRoute(async (request, auth) => {
  const body = await request.json()
  const data = wmsShipmentOrderUpdateSchema.parse(body)
  const result = await WmsShipmentOrderService.update(data.id, data, auth.userId, auth.tenantId)
  return NextResponse.json({ success: true, data: result })
}, { permission: UPDATE_PERM })

export const DELETE = withAdminRoute(async (request, auth) => {
  const { searchParams } = new URL(request.url)
  const id = searchParams.get("id")
  if (!id) return NextResponse.json({ success: false, error: "id is required" }, { status: 400 })
  const result = await WmsShipmentOrderService.delete(id, auth.userId, auth.tenantId)
  return NextResponse.json({ success: true, data: result })
}, { permission: DELETE_PERM })
