// Auto-generated by Codegen Engine
import { z } from "zod"



export const imConversationReadPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const imConversationReadCreateSchema = z.object({
  user_id: z.coerce.number().finite().optional(),
  conversation_type: z.coerce.number().finite().optional(),
  target_id: z.coerce.number().finite().optional(),
  message_id: z.coerce.number().finite().optional(),
  read_time: z.string().trim().optional(),

}).strict()

export const imConversationReadUpdateSchema = imConversationReadCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type ImConversationReadPageQueryInput = z.infer<typeof imConversationReadPageQuerySchema>
export type ImConversationReadCreateInput = z.infer<typeof imConversationReadCreateSchema>
export type ImConversationReadUpdateInput = z.infer<typeof imConversationReadUpdateSchema>
