// Auto-generated by Codegen Engine (admin page dispatcher) —— 不要手改
import type React from "react"

import { redirect } from "next/navigation"

import { ADMIN_PAGE_REGISTRY } from "../_generated/admin-page-registry"
import { UniversalSchemaCanvas } from "@/shared/frontend/components/universal-schema-canvas"
import { GENERATED_PAGE_SCHEMAS } from "@/shared/contract/page-schemas.generated"

/**
 * **必须显式声明已知路由，并关掉"未知参数也匹配"。**
 *
 * 只靠页面里调 notFound() 是不够的: 这是个 async 页面、上层又是客户端 layout，
 * 流式渲染一旦开始状态码就定了 —— 实测结果就是**未知路径返回 200**（改前是 404，
 * 用 git stash 对比确认是我的重构引入的）。
 * 用 generateStaticParams + dynamicParams=false 让**路由层**就拒绝未知 slug。
 */
export const dynamicParams = false

export function generateStaticParams() {
  const standardSlugs = Object.keys(ADMIN_PAGE_REGISTRY).map((slug) => ({ slug: slug.split("/") }))
  const canvasSlugs = Object.keys(GENERATED_PAGE_SCHEMAS).map((entity) => ({ slug: ["canvas", entity] }))
  return [...standardSlugs, ...canvasSlugs]
}

/**
 * admin 页面的**唯一派发器**。
 *
 * 与插件 API 挂载同构: 接口面是 `plugins/[pluginKey]/api/[...path]/route.ts` 两个文件，
 * 页面面就是这一个文件 + 一张生成的映射表（而不是 476 个硬编码薄壳）。
 * 页面实现仍在各域包里（`@/modules/<域>/frontend/pages/*`），这里只负责按 slug 找到它。
 */
export default async function AdminPage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string[] }>
  searchParams?: Promise<{ mode?: string }>
}) {
  const { slug } = await params
  const { mode } = (await searchParams) ?? {}
  const key = slug.join("/")

  // 1. 动态本体画布路由: /admin/canvas/[entity]
  if (slug[0] === "canvas" && slug.length >= 2) {
    const entity = slug[1]
    const domain = slug.length >= 3 ? slug[2] : undefined
    return <UniversalSchemaCanvas entity={entity} domain={domain} />
  }

  const entry = ADMIN_PAGE_REGISTRY[key]
  // 走到这里 key 一定在表里（unknown slug 在路由层就被 dynamicParams=false 挡掉）；
  // 保底一句，避免表被改坏时静默渲染空页。
  if (!entry) redirect("/admin")
  if (entry.kind === "redirect") redirect(entry.target)

  if (entry.kind === "canvas") {
    return <UniversalSchemaCanvas entity={entry.entity} domain={entry.domain} />
  }

  // 2. 支持查询参数 ?mode=canvas 无缝切换至通用本体画布
  if (mode === "canvas") {
    const possibleEntity = slug[slug.length - 1].replace(/-/g, "_")
    return <UniversalSchemaCanvas entity={possibleEntity} domain={slug[0]} />
  }

  const Component = (await entry.load()) as React.ComponentType
  // **必须当 JSX 渲染，不能当函数调用**: 业务页面多是客户端组件（"use client"），
  // 从服务端调用会报 "Attempted to call X() from the server but X is on the client"。
  // 写这一版时踩到，构建期预渲染 476 个页面时炸出来。
  return <Component />
}
