// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { CrmFollowUpRecordService } from "../crm-follow-up-record.service"

describe("CrmFollowUpRecordService", () => {
  it("should create and query 跟进记录 DO用于记录客户、联系人的每一次跟进", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await CrmFollowUpRecordService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await CrmFollowUpRecordService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await CrmFollowUpRecordService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await CrmFollowUpRecordService.update(created.id, {
        id: created.id,
          biz_type: 1,
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await CrmFollowUpRecordService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
