// Auto-generated by Codegen Engine
import { z } from "zod"



export const discountProductPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const discountProductCreateSchema = z.object({
  activity_id: z.coerce.number().finite().optional(),
  spu_id: z.coerce.number().finite().optional(),
  sku_id: z.coerce.number().finite().optional(),
  discount_type: z.coerce.number().finite().optional(),
  discount_percent: z.coerce.number().finite().optional(),
  discount_price: z.coerce.number().finite().optional(),
  activity_name: z.string().trim().optional(),
  activity_status: z.coerce.number().finite().optional(),
  activity_start_time: z.string().trim().optional(),
  activity_end_time: z.string().trim().optional(),

}).strict()

export const discountProductUpdateSchema = discountProductCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type DiscountProductPageQueryInput = z.infer<typeof discountProductPageQuerySchema>
export type DiscountProductCreateInput = z.infer<typeof discountProductCreateSchema>
export type DiscountProductUpdateInput = z.infer<typeof discountProductUpdateSchema>
