// Auto-generated by Codegen Engine
import { z } from "zod"



export const diyTemplatePageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const diyTemplateCreateSchema = z.object({
  name: z.string().trim().optional(),
  used: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),
  used_time: z.string().trim().optional(),
  remark: z.string().trim().optional(),
  preview_pic_urls: z.string().trim().optional(),
  property: z.string().trim().optional(),

}).strict()

export const diyTemplateUpdateSchema = diyTemplateCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type DiyTemplatePageQueryInput = z.infer<typeof diyTemplatePageQuerySchema>
export type DiyTemplateCreateInput = z.infer<typeof diyTemplateCreateSchema>
export type DiyTemplateUpdateInput = z.infer<typeof diyTemplateUpdateSchema>
