// Auto-generated by Codegen Engine
import { z } from "zod"



export const productPropertyPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const productPropertyCreateSchema = z.object({
  name: z.string().trim().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const productPropertyUpdateSchema = productPropertyCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type ProductPropertyPageQueryInput = z.infer<typeof productPropertyPageQuerySchema>
export type ProductPropertyCreateInput = z.infer<typeof productPropertyCreateSchema>
export type ProductPropertyUpdateInput = z.infer<typeof productPropertyUpdateSchema>
