// Auto-generated by Codegen Engine
import { z } from "zod"



export const productCategoryPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const productCategoryCreateSchema = z.object({
  parent_id: z.coerce.number().finite().optional(),
  name: z.string().trim().optional(),
  pic_url: z.string().trim().optional(),
  sort: z.coerce.number().finite().optional(),
  status: z.coerce.number().finite().optional(),

}).strict()

export const productCategoryUpdateSchema = productCategoryCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type ProductCategoryPageQueryInput = z.infer<typeof productCategoryPageQuerySchema>
export type ProductCategoryCreateInput = z.infer<typeof productCategoryCreateSchema>
export type ProductCategoryUpdateInput = z.infer<typeof productCategoryUpdateSchema>
