// Auto-generated by Codegen Engine
import { z } from "zod"



export const tradeConfigPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const tradeConfigCreateSchema = z.object({
  after_sale_refund_reasons: z.string().trim().optional(),
  after_sale_return_reasons: z.string().trim().optional(),
  delivery_express_free_enabled: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),
  delivery_express_free_price: z.coerce.number().finite().optional(),
  delivery_pick_up_enabled: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),
  brokerage_enabled: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),
  brokerage_enabled_condition: z.coerce.number().finite().optional(),
  brokerage_bind_mode: z.coerce.number().finite().optional(),
  brokerage_poster_urls: z.string().trim().optional(),
  brokerage_first_percent: z.coerce.number().finite().optional(),
  brokerage_second_percent: z.coerce.number().finite().optional(),
  brokerage_withdraw_min_price: z.coerce.number().finite().optional(),
  brokerage_withdraw_fee_percent: z.coerce.number().finite().optional(),
  brokerage_frozen_days: z.coerce.number().finite().optional(),
  brokerage_withdraw_types: z.string().trim().optional(),

}).strict()

export const tradeConfigUpdateSchema = tradeConfigCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type TradeConfigPageQueryInput = z.infer<typeof tradeConfigPageQuerySchema>
export type TradeConfigCreateInput = z.infer<typeof tradeConfigCreateSchema>
export type TradeConfigUpdateInput = z.infer<typeof tradeConfigUpdateSchema>
