// Auto-generated by Codegen Engine
export interface WmsInventoryHistoryDO {
  id: string
  warehouse_id: string
  item_id: string
  change_type: string
  qty_change: number
  before_qty: number
  after_qty: number
  ref_order_no?: string
  tenant_id: string
  create_time: string
}

export interface WmsInventoryHistoryVO {
  id: string
  warehouse_id: string
  item_id: string
  change_type: string
  qty_change: number
  before_qty: number
  after_qty: number
  ref_order_no?: string
  tenant_id: string
  create_time: string
}

export interface WmsInventoryHistoryCreateDTO {
  warehouse_id: string
  item_id: string
  change_type: string
  qty_change: number
  before_qty: number
  after_qty: number
  ref_order_no?: string
}

export interface WmsInventoryHistoryUpdateDTO extends Partial<WmsInventoryHistoryCreateDTO> {
  id: string
}

export interface WmsInventoryHistoryPageQuery {
  page?: number
  pageSize?: number
  ref_order_no?: string
}
