// Auto-generated by Codegen Engine (App Router Page)
import { MemberLevelRecordListPage } from "@/modules/member/frontend/pages/member-level-record-list.page"

export default function Page() {
  return <MemberLevelRecordListPage />
}
