import { z } from "zod"
import { registerActionSchema } from "@/modules/shared/backend/lib/broker-validator"
import {
  updateConfigSchema,
  infraCodegenPreviewSchema,
  templatePreviewSchema,
  infraCodegenExportSchema,
  listQueryDataSourcesSchema,
  getQueryConnectionSchema,
  infraConfigListSchema,
  getConfigByKeySchema,
  infraConfigCreateSchema,
  infraJobListSchema,
  infraJobCreateSchema,
  infraFileListSchema,
  infraFileRecordSchema,
  dataSourceConfigPageSchema,
  infraResourceIdSchema,
  infraConfigItemUpdateSchema,
  infraJobUpdateSchema,
  infraResourceStatusSchema,
  infraPageListSchema,
  getPageBySlugSchema,
  apiErrorLogQuerySchema,
  processApiErrorLogSchema,
  infraPageQuerySchema,
  testDataSourceConnectionSchema,
  codegenTableListSchema,
  codegenTableIdSchema,
  codegenTableUpdateSchema,
  codegenTableIdsSchema,
  auditLogRetentionSchema,
  codegenCandidateQuerySchema,
  codegenImportSchema,
  emptyPayloadSchema,
} from "../backend/validators"

export const infraPingSchema = z.object({
  n: z.number().optional(),
})

export const INFRA_ACTION_SCHEMAS = {
  "infra.ping": infraPingSchema,
  "infra.updateConfig": updateConfigSchema,
  "infra.previewCodegen": infraCodegenPreviewSchema,
  "infra.generateCodegen": infraCodegenPreviewSchema,
  "infra.previewTemplate": templatePreviewSchema,
  "infra.generateTemplate": infraCodegenExportSchema,
  "infra.listQueryDataSources": listQueryDataSourcesSchema,
  "infra.getQueryConnection": getQueryConnectionSchema,
  "infra.listConfigs": infraConfigListSchema,
  "infra.getConfigByKey": getConfigByKeySchema,
  "infra.createConfig": infraConfigCreateSchema,
  "infra.listJobs": infraJobListSchema,
  "infra.createJob": infraJobCreateSchema,
  "infra.listFiles": infraFileListSchema,
  "infra.recordFile": infraFileRecordSchema,
  "infra.pageDataSourceConfigs": dataSourceConfigPageSchema,
  "infra.getConfig": infraResourceIdSchema,
  "infra.updateConfigItem": infraConfigItemUpdateSchema,
  "infra.deleteConfig": infraResourceIdSchema,
  "infra.getJob": infraResourceIdSchema,
  "infra.updateJob": infraJobUpdateSchema,
  "infra.deleteJob": infraResourceIdSchema,
  "infra.triggerJob": infraResourceIdSchema,
  "infra.updateJobStatus": infraResourceStatusSchema,
  "infra.getFile": infraResourceIdSchema,
  "infra.deleteFile": infraResourceIdSchema,
  "infra.listPages": infraPageListSchema,
  "infra.getPage": infraResourceIdSchema,
  "infra.getPageBySlug": getPageBySlugSchema,
  "infra.pageApiErrorLogs": apiErrorLogQuerySchema,
  "infra.getApiErrorLog": infraResourceIdSchema,
  "infra.processApiErrorLog": processApiErrorLogSchema,
  "infra.pageApiAccessLogs": infraPageQuerySchema,
  "infra.getApiAccessLog": infraResourceIdSchema,
  "infra.testDataSourceConnection": testDataSourceConnectionSchema,
  "infra.listCodegenTables": codegenTableListSchema,
  "infra.getCodegenTable": codegenTableIdSchema,
  "infra.updateCodegenTable": codegenTableUpdateSchema,
  "infra.deleteCodegenTable": codegenTableIdSchema,
  "infra.deleteCodegenTables": codegenTableIdsSchema,
  "infra.exportApiAccessLogs": infraPageQuerySchema,
  "infra.exportApiErrorLogs": apiErrorLogQuerySchema,
  "infra.runAuditLogRetention": auditLogRetentionSchema,
  "infra.listCodegenCandidates": codegenCandidateQuerySchema,
  "infra.importCodegenTables": codegenImportSchema,
  "infra.generateCodegenArchive": codegenTableIdSchema,
  "infra.listCodegenCatalog": emptyPayloadSchema,
} as const

export function registerActionSchemas() {
  for (const [action, schema] of Object.entries(INFRA_ACTION_SCHEMAS)) {
    registerActionSchema(action, schema)
  }
}
