"use client"

type Settings = { category?: string; identityStrategy?: string; list?: { pagination?: boolean; selection?: boolean; layout?: string }; form?: { layout?: string; theme?: string; horizontalScroll?: boolean } }
type Props = { settings: Settings; disabled: boolean; onChange: (settings: Settings) => void }

export function OnlineDefinitionSettingsEditor({ settings, disabled, onChange }: Props) {
  const list = settings.list ?? {}; const form = settings.form ?? {}; const patch = (next: Partial<Settings>) => onChange({ ...settings, ...next, list: next.list ? { ...list, ...next.list } : list, form: next.form ? { ...form, ...next.form } : form })
  return <section className="rounded-lg border p-4"><div className="mb-4"><h3 className="font-semibold">表单基础属性</h3><p className="mt-1 text-xs text-slate-500">配置保存到版本化 Interaction IR，只影响受控 Runtime 表现，不允许模板、样式、URL 或脚本。</p></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="text-xs">分类<input disabled={disabled} value={settings.category ?? "general"} maxLength={64} onChange={(event) => patch({ category: event.target.value })} className="mt-1 h-9 w-full rounded border px-2" /></label><label className="text-xs">主键策略<select disabled={disabled} value={settings.identityStrategy ?? "PLATFORM_UUID"} onChange={(event) => patch({ identityStrategy: event.target.value as Settings["identityStrategy"] })} className="mt-1 h-9 w-full rounded border px-2"><option value="PLATFORM_UUID">平台 UUID</option><option value="MANUAL">手工标识</option></select></label><label className="text-xs">列表布局<select disabled={disabled} value={list.layout ?? "TABLE"} onChange={(event) => patch({ list: { layout: event.target.value as NonNullable<Settings["list"]>["layout"] } })} className="mt-1 h-9 w-full rounded border px-2"><option value="TABLE">表格</option><option value="CARD">卡片</option></select></label><label className="text-xs">表单布局<select disabled={disabled} value={form.layout ?? "GRID"} onChange={(event) => patch({ form: { layout: event.target.value as NonNullable<Settings["form"]>["layout"] } })} className="mt-1 h-9 w-full rounded border px-2"><option value="GRID">栅格</option><option value="TABS">页签</option><option value="DRAWER">抽屉</option><option value="DIALOG">对话框</option></select></label><label className="text-xs">表单主题<select disabled={disabled} value={form.theme ?? "DEFAULT"} onChange={(event) => patch({ form: { theme: event.target.value as NonNullable<Settings["form"]>["theme"] } })} className="mt-1 h-9 w-full rounded border px-2"><option value="DEFAULT">默认</option><option value="COMPACT">紧凑</option></select></label><label className="mt-5 flex items-center gap-2 text-sm"><input disabled={disabled} checked={list.pagination !== false} onChange={(event) => patch({ list: { pagination: event.target.checked } })} type="checkbox" />服务端分页</label><label className="mt-5 flex items-center gap-2 text-sm"><input disabled={disabled} checked={list.selection === true} onChange={(event) => patch({ list: { selection: event.target.checked } })} type="checkbox" />显示行选择</label><label className="mt-5 flex items-center gap-2 text-sm"><input disabled={disabled} checked={form.horizontalScroll === true} onChange={(event) => patch({ form: { horizontalScroll: event.target.checked } })} type="checkbox" />表单横向滚动</label></div></section>
}
