export { AreaService as SystemAreaService } from "./area.service"
export { SystemAuthService } from "./auth.service"
export { SystemCaptchaService } from "./captcha.service"
export { SystemDeptService } from "./dept.service"
export { SystemDictService } from "./dict.service"
export { SystemIpAreaService } from "./ip-area.service"
export { SystemLoginLogService } from "./login-log.service"
export { SystemMailService } from "./mail.service"
export { SystemMenuService } from "./menu.service"
export { SystemNoticeService } from "./notice.service"
export { SystemNotifyMessageService } from "./notify-message.service"
export { SystemNotifyTemplateService } from "./notify-template.service"
export { SystemOauth2Service } from "./oauth2.service"
export { SystemOnlineUserService } from "./online-user.service"
export { SystemOperateLogService } from "./operate-log.service"
export { SystemPermissionService } from "./permission.service"
export { SystemPostService } from "./post.service"
export { SystemRoleService } from "./role.service"
export { SystemSmsService } from "./sms.service"
export { SystemSocialService } from "./social.service"
export { SystemTenantService } from "./tenant.service"
export { SystemTenantPackageService } from "./tenant-package.service"
export { SystemUserService } from "./user.service"
export { UserProfileService as SystemUserProfileService } from "./user-profile.service"
