// Auto-generated by Codegen Engine (App Router Page)
import { MesWmMaterialStockListPage } from "@/modules/mes/frontend/pages/mes-wm-material-stock-list.page"

export default function Page() {
  return <MesWmMaterialStockListPage />
}
