// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MpUserCreateDTO,
  MpUserPageQuery,
  MpUserUpdateDTO,
  MpUserVO,
} from "@/modules/mp/backend/types/mp-user.types"

const BASE_URL = "/api/v1/admin/mp/mp-user"

export const MpUserApi = {
  async page(params?: MpUserPageQuery) {
    return request.get<{ items: MpUserVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MpUserVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MpUserCreateDTO) {
    return request.post<MpUserVO>(BASE_URL, data)
  },

  async update(data: MpUserUpdateDTO) {
    return request.put<MpUserVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MpUserPageQuery) {
    return request.post<MpUserVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
