// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  MemberGroupCreateDTO,
  MemberGroupPageQuery,
  MemberGroupUpdateDTO,
  MemberGroupVO,
} from "@/modules/member/backend/types/member-group.types"

const BASE_URL = "/api/v1/admin/member/member-group"

export const MemberGroupApi = {
  async page(params?: MemberGroupPageQuery) {
    return request.get<{ items: MemberGroupVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<MemberGroupVO>(`${BASE_URL}/${id}`)
  },

  async create(data: MemberGroupCreateDTO) {
    return request.post<MemberGroupVO>(BASE_URL, data)
  },

  async update(data: MemberGroupUpdateDTO) {
    return request.put<MemberGroupVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: MemberGroupPageQuery) {
    return request.post<MemberGroupVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
