// Auto-generated by Codegen Engine (RPC Facade / Dual-Mode Binding)
import { serviceBus } from "@/modules/shared/backend/lib/service-bus"
import { WmsShipmentOrderDetailService } from "./wms-shipment-order-detail.service"
import type {
  WmsShipmentOrderDetailCreateDTO,
  WmsShipmentOrderDetailPageQuery,
  WmsShipmentOrderDetailUpdateDTO,
} from "../types/wms-shipment-order-detail.types"

export class WmsShipmentOrderDetailRpc {
  static async register() {
    serviceBus.registerHandler("ruoyi.cmd.wms.wmsShipmentOrderDetail.page", async (req) => {
      const query = req.data as WmsShipmentOrderDetailPageQuery
      return WmsShipmentOrderDetailService.page(query, req.actorId, req.tenantId)
    })

    bus.registerHandler("ruoyi.cmd.wms.wmsShipmentOrderDetail.get", async (req) => {
      const { id } = req.data as { id: string }
      return WmsShipmentOrderDetailService.get(id, req.actorId, req.tenantId)
    })

    bus.registerHandler("ruoyi.cmd.wms.wmsShipmentOrderDetail.create", async (req) => {
      const data = req.data as WmsShipmentOrderDetailCreateDTO
      return WmsShipmentOrderDetailService.create(data, req.actorId, req.tenantId)
    })

    bus.registerHandler("ruoyi.cmd.wms.wmsShipmentOrderDetail.update", async (req) => {
      const { id, ...rest } = req.data as WmsShipmentOrderDetailUpdateDTO
      return WmsShipmentOrderDetailService.update(id, rest as any, req.actorId, req.tenantId)
    })

    bus.registerHandler("ruoyi.cmd.wms.wmsShipmentOrderDetail.delete", async (req) => {
      const { id } = req.data as { id: string }
      return WmsShipmentOrderDetailService.delete(id, req.actorId, req.tenantId)
    })
  }
}

export const wmsShipmentOrderDetailRpc = WmsShipmentOrderDetailRpc
