// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  CrmReceivableCreateDTO,
  CrmReceivablePageQuery,
  CrmReceivableUpdateDTO,
  CrmReceivableVO,
} from "@/modules/crm/backend/types/crm-receivable.types"

const BASE_URL = "/api/v1/admin/crm/crm-receivable"

export const CrmReceivableApi = {
  async page(params?: CrmReceivablePageQuery) {
    return request.get<{ items: CrmReceivableVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<CrmReceivableVO>(`${BASE_URL}/${id}`)
  },

  async create(data: CrmReceivableCreateDTO) {
    return request.post<CrmReceivableVO>(BASE_URL, data)
  },

  async update(data: CrmReceivableUpdateDTO) {
    return request.put<CrmReceivableVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: CrmReceivablePageQuery) {
    return request.post<CrmReceivableVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
