// Auto-generated by Codegen Engine (App Router Page)
import { MesMdAutoCodeRecordListPage } from "@/modules/mes/frontend/pages/mes-md-auto-code-record-list.page"

export default function Page() {
  return <MesMdAutoCodeRecordListPage />
}
