/**
 * system 域的跨域 RPC 契约（**代码**，由 scripts/bootstrap-rpc-contracts.ts 从既有 catalog 反向生成）。
 *
 * 之后 `rpc-actions.json` 是**派生物** —— 加方法请改这里，再跑
 * `npx tsx scripts/generate-rpc-actions.ts --write`（门禁 `rpc:actions:check` 会拦漂移）。
 */
import { defineRpcContract } from "@/modules/shared/backend/lib/rpc-contract"

export const SYSTEM_RPC_CONTRACT = defineRpcContract("system", {
  ping: { schema: "ping" },
  getDictDataByType: { service: "SystemDictService", module: "dict.service", schema: "getDictDataByTypeSchema" },
  resolveTenantEntitlement: { service: "TenantEntitlementService", module: "tenant-entitlement.service", schema: "resolveTenantEntitlementSchema" },
  resolveTenantIdByCode: { service: "SystemTenantService", module: "tenant.service", schema: "resolveTenantIdByCodeSchema" },
  listUsers: { service: "SystemUserService", module: "user.service", target: "list", schema: "userListQuerySchema" },
  createUser: { service: "SystemUserService", module: "user.service", target: "create", schema: "createUserSchema" },
  listRoles: { service: "SystemRoleService", module: "role.service", target: "list", schema: "roleListQuerySchema" },
  createRole: { service: "SystemRoleService", module: "role.service", target: "create", schema: "createRoleSchema" },
  listMenus: { service: "SystemMenuService", module: "menu.service", target: "list", schema: "menuQuerySchema" },
  treeMenus: { service: "SystemMenuService", module: "menu.service", target: "tree", schema: "menuQuerySchema" },
  createMenu: { service: "SystemMenuService", module: "menu.service", target: "create", schema: "createMenuSchema" },
  listDepts: { service: "SystemDeptService", module: "dept.service", target: "list", schema: "deptQuerySchema" },
  treeDepts: { service: "SystemDeptService", module: "dept.service", target: "tree", schema: "deptQuerySchema" },
  createDept: { service: "SystemDeptService", module: "dept.service", target: "create", schema: "createDeptSchema" },
  listPosts: { service: "SystemPostService", module: "post.service", target: "list", schema: "postListQuerySchema" },
  createPost: { service: "SystemPostService", module: "post.service", target: "create", schema: "createPostSchema" },
  listDictTypes: { service: "SystemDictService", module: "dict.service", target: "listTypes", schema: "dictTypeListQuerySchema" },
  createDictType: { service: "SystemDictService", module: "dict.service", target: "createType", schema: "createDictTypeSchema" },
  listTenants: { service: "SystemTenantService", module: "tenant.service", target: "list", schema: "tenantListQuerySchema" },
  createTenant: { service: "SystemTenantService", module: "tenant.service", target: "create", schema: "createTenantWithAdminSchema" },
  getUser: { service: "SystemUserService", module: "user.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateUser: { service: "SystemUserService", module: "user.service", target: "update", schema: "updateUserSchema" },
  deleteUser: { service: "SystemUserService", module: "user.service", schema: "deleteUserSchema", fieldsRef: "resourceId" },
  resetUserPassword: { service: "SystemUserService", module: "user.service", target: "resetPassword", schema: "updateUserPasswordSchema" },
  updateUserStatus: { service: "SystemUserService", module: "user.service", schema: "resourceStatusSchema", fieldsRef: "resourceStatus" },
  getRole: { service: "SystemRoleService", module: "role.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateRole: { service: "SystemRoleService", module: "role.service", target: "update", schema: "updateRoleSchema" },
  deleteRole: { service: "SystemRoleService", module: "role.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateRoleStatus: { service: "SystemRoleService", module: "role.service", schema: "resourceStatusSchema", fieldsRef: "resourceStatus" },
  getMenu: { service: "SystemMenuService", module: "menu.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateMenu: { service: "SystemMenuService", module: "menu.service", target: "update", schema: "updateMenuSchema" },
  deleteMenu: { service: "SystemMenuService", module: "menu.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  getDept: { service: "SystemDeptService", module: "dept.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateDept: { service: "SystemDeptService", module: "dept.service", target: "update", schema: "updateDeptSchema" },
  deleteDept: { service: "SystemDeptService", module: "dept.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  getPost: { service: "SystemPostService", module: "post.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updatePost: { service: "SystemPostService", module: "post.service", target: "update", schema: "updatePostSchema" },
  deletePost: { service: "SystemPostService", module: "post.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  getDictType: { service: "SystemDictService", module: "dict.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateDictType: { service: "SystemDictService", module: "dict.service", target: "updateType", schema: "updateDictTypeSchema" },
  deleteDictType: { service: "SystemDictService", module: "dict.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  getTenant: { service: "SystemTenantService", module: "tenant.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateTenant: { service: "SystemTenantService", module: "tenant.service", target: "update", schema: "updateTenantSchema" },
  deleteTenant: { service: "SystemTenantService", module: "tenant.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateTenantStatus: { service: "SystemTenantService", module: "tenant.service", schema: "resourceStatusSchema", fieldsRef: "resourceStatus" },
  listDictData: { service: "SystemDictService", module: "dict.service", schema: "listDictDataSchema" },
  createDictData: { service: "SystemDictService", module: "dict.service", schema: "createDictDataSchema" },
  getDictData: { service: "SystemDictService", module: "dict.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateDictData: { service: "SystemDictService", module: "dict.service", schema: "updateDictDataSchema" },
  deleteDictData: { service: "SystemDictService", module: "dict.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  listTenantPackages: { service: "SystemTenantPackageService", module: "tenant-package.service", schema: "tenantPackageListSchema" },
  createTenantPackage: { service: "SystemTenantPackageService", module: "tenant-package.service", schema: "createTenantPackageSchema" },
  getTenantPackage: { service: "SystemTenantPackageService", module: "tenant-package.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateTenantPackage: { service: "SystemTenantPackageService", module: "tenant-package.service", schema: "updateTenantPackageSchema" },
  deleteTenantPackage: { service: "SystemTenantPackageService", module: "tenant-package.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  assignTenantPackage: { service: "SystemTenantService", module: "tenant.service", schema: "assignTenantPackageSchema" },
  getTenantSubscriptions: { service: "SystemTenantService", module: "tenant.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  getRoleMenus: { service: "SystemPermissionService", module: "permission.service", schema: "getRoleMenusSchema" },
  assignRoleMenu: { service: "SystemPermissionService", module: "permission.service", schema: "assignRoleMenuSchema" },
  assignUserRole: { service: "SystemPermissionService", module: "permission.service", schema: "assignUserRoleSchema" },
  pageLoginLogs: { service: "LoginLogService", module: "login-log.service", target: "page", schema: "loginLogQuerySchema", fieldsRef: "pageQuery" },
  getLoginLog: { service: "LoginLogService", module: "login-log.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  exportLoginLogs: { service: "LoginLogService", module: "login-log.service", schema: "loginLogQuerySchema", fieldsRef: "pageQuery" },
  pageOperateLogs: { service: "OperateLogService", module: "operate-log.service", target: "page", schema: "operateLogQuerySchema", fieldsRef: "pageQuery" },
  getOperateLog: { service: "OperateLogService", module: "operate-log.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  exportOperateLogs: { service: "OperateLogService", module: "operate-log.service", schema: "operateLogQuerySchema", fieldsRef: "pageQuery" },
  listOnlineUsers: { service: "SystemOnlineUserService", module: "online-user.service", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  forceLogoutOnlineUser: { service: "SystemOnlineUserService", module: "online-user.service", schema: "forceLogoutSchema" },
  pageNotices: { service: "NoticeService", module: "notice.service", target: "page", schema: "pageQuerySchema", fieldsRef: "pageQuery" },
  createNotice: { service: "NoticeService", module: "notice.service", schema: "createNoticeSchema" },
  getNotice: { service: "NoticeService", module: "notice.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateNotice: { service: "NoticeService", module: "notice.service", schema: "updateNoticeSchema" },
  deleteNotice: { service: "NoticeService", module: "notice.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  listOauth2Clients: { service: "SystemOauth2Service", module: "oauth2.service", target: "listClients", schema: "pageQuerySchema", fieldsRef: "pageQuery" },
  listOauth2Tokens: { service: "SystemOauth2Service", module: "oauth2.service", target: "listTokens", schema: "pageQuerySchema", fieldsRef: "pageQuery" },
  listSocialUsers: { service: "SystemSocialService", module: "social.service", target: "listUsers", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  createSocialUser: { service: "SystemSocialService", module: "social.service", schema: "createSocialUserSchema" },
  listMailAccounts: { service: "SystemMailService", module: "mail.service", target: "listAccounts", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  createMailAccount: { service: "SystemMailService", module: "mail.service", schema: "createMailAccountSchema" },
  listMailLogs: { service: "SystemMailService", module: "mail.service", target: "listLogs", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  listSmsChannels: { service: "SystemSmsService", module: "sms.service", target: "listChannels", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  createSmsChannel: { service: "SystemSmsService", module: "sms.service", schema: "createSmsChannelSchema" },
  listSmsLogs: { service: "SystemSmsService", module: "sms.service", target: "listLogs", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  pageNotifyMessages: { service: "NotifyMessageService", module: "notify-message.service", target: "page", schema: "pageQuerySchema", fieldsRef: "pageQuery" },
  createNotifyMessage: { service: "NotifyMessageService", module: "notify-message.service", target: "create", schema: "createNotifyMessageSchema" },
  pageNotifyTemplates: { service: "NotifyTemplateService", module: "notify-template.service", target: "page", schema: "pageQuerySchema", fieldsRef: "pageQuery" },
  createNotifyTemplate: { service: "NotifyTemplateService", module: "notify-template.service", target: "create", schema: "createNotifyTemplateSchema" },
  pageIpAreas: { service: "IpAreaService", module: "ip-area.service", target: "page", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  pageAreas: { service: "AreaService", module: "area.service", target: "page", schema: "pageQuerySchema", fieldsRef: "pageQuery" },
  createArea: { service: "AreaService", module: "area.service", schema: "createAreaSchema" },
  getArea: { service: "AreaService", module: "area.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateArea: { service: "AreaService", module: "area.service", schema: "updateAreaSchema" },
  deleteArea: { service: "AreaService", module: "area.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  login: { service: "SystemAuthService", module: "auth.service", schema: "loginSchema" },
  getPermissionInfoByUser: { service: "SystemAuthService", module: "auth.service", schema: "actorIdSchema" },
  refreshAccessToken: { service: "SystemAuthService", module: "auth.service", schema: "refreshTokenSchema" },
  logout: { service: "SystemAuthService", module: "auth.service", schema: "emptyPayloadSchema", fieldsRef: "ping" },
  generateCaptcha: { service: "SystemCaptchaService", module: "captcha.service", schema: "emptyPayloadSchema", fieldsRef: "ping" },
  verifyCaptcha: { service: "SystemCaptchaService", module: "captcha.service", schema: "captchaVerifySchema" },
  getUserProfile: { service: "UserProfileService", module: "user-profile.service", schema: "getUserProfileSchema" },
  updateUserProfile: { service: "UserProfileService", module: "user-profile.service", schema: "updateUserProfileSchema" },
  getSidebarNav: { service: "SystemMenuService", module: "menu.service", schema: "sidebarNavSchema" },
  openOauth2Token: { service: "SystemOauth2Service", module: "oauth2.service", target: "openToken", schema: "oauth2OpenTokenSchema" },
  getOauth2UserInfo: { service: "SystemOauth2Service", module: "oauth2.service", target: "getUserInfo", schema: "oauth2UserInfoSchema" },
  listMailTemplates: { service: "SystemMailTemplateService", module: "mail-template.service", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  createMailTemplate: { service: "SystemMailTemplateService", module: "mail-template.service", schema: "createMailTemplateSchema" },
  getMailTemplate: { service: "SystemMailTemplateService", module: "mail-template.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateMailTemplate: { service: "SystemMailTemplateService", module: "mail-template.service", schema: "updateMailTemplateSchema" },
  deleteMailTemplate: { service: "SystemMailTemplateService", module: "mail-template.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  listSmsTemplates: { service: "SystemSmsTemplateService", module: "sms-template.service", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  createSmsTemplate: { service: "SystemSmsTemplateService", module: "sms-template.service", schema: "createSmsTemplateSchema" },
  getSmsTemplate: { service: "SystemSmsTemplateService", module: "sms-template.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateSmsTemplate: { service: "SystemSmsTemplateService", module: "sms-template.service", schema: "updateSmsTemplateSchema" },
  deleteSmsTemplate: { service: "SystemSmsTemplateService", module: "sms-template.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  listSocialClients: { service: "SystemSocialClientService", module: "social-client.service", schema: "systemModulePageQuerySchema", fieldsRef: "pageQuery" },
  createSocialClient: { service: "SystemSocialClientService", module: "social-client.service", schema: "createSocialClientSchema" },
  getSocialClient: { service: "SystemSocialClientService", module: "social-client.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
  updateSocialClient: { service: "SystemSocialClientService", module: "social-client.service", schema: "updateSocialClientSchema" },
  deleteSocialClient: { service: "SystemSocialClientService", module: "social-client.service", schema: "resourceIdSchema", fieldsRef: "resourceId" },
})
