-- Initial PostgreSQL schema for ruoyi-all-next. Runtime access is through Kysely; Prisma owns schema and migration history.
CREATE SCHEMA IF NOT EXISTS "public";
CREATE TABLE "system_user" ("id" TEXT PRIMARY KEY, "username" VARCHAR(30) NOT NULL UNIQUE, "nickname" VARCHAR(30) NOT NULL, "password" VARCHAR(100) NOT NULL, "phone" VARCHAR(20), "email" VARCHAR(50), "avatar" VARCHAR(500), "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "dept_id" TEXT, "remark" VARCHAR(500), "login_ip" VARCHAR(50), "login_date" TIMESTAMP(3), "tenant_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_role" ("id" TEXT PRIMARY KEY, "name" VARCHAR(30) NOT NULL, "code" VARCHAR(100) NOT NULL UNIQUE, "sort" INTEGER NOT NULL DEFAULT 0, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "remark" VARCHAR(500), "data_scope" VARCHAR(20) NOT NULL DEFAULT 'ALL', "tenant_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_dept" ("id" TEXT PRIMARY KEY, "name" VARCHAR(50) NOT NULL, "parent_id" TEXT, "sort" INTEGER NOT NULL DEFAULT 0, "leader_id" TEXT, "phone" VARCHAR(20), "email" VARCHAR(50), "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "tenant_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_menu" ("id" TEXT PRIMARY KEY, "name" VARCHAR(50) NOT NULL, "permission" VARCHAR(100), "type" VARCHAR(10) NOT NULL, "parent_id" TEXT, "path" VARCHAR(200), "component" VARCHAR(200), "icon" VARCHAR(100), "sort" INTEGER NOT NULL DEFAULT 0, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "visible" BOOLEAN NOT NULL DEFAULT true, "keep_alive" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_post" ("id" TEXT PRIMARY KEY, "name" VARCHAR(50) NOT NULL, "code" VARCHAR(64) NOT NULL UNIQUE, "sort" INTEGER NOT NULL DEFAULT 0, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "remark" VARCHAR(500), "tenant_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_user_role" ("id" TEXT PRIMARY KEY, "user_id" TEXT NOT NULL, "role_id" TEXT NOT NULL, UNIQUE ("user_id", "role_id"));
CREATE TABLE "system_role_menu" ("id" TEXT PRIMARY KEY, "role_id" TEXT NOT NULL, "menu_id" TEXT NOT NULL, UNIQUE ("role_id", "menu_id"));
CREATE TABLE "system_user_post" ("id" TEXT PRIMARY KEY, "user_id" TEXT NOT NULL, "post_id" TEXT NOT NULL, UNIQUE ("user_id", "post_id"));
CREATE TABLE "system_dict_type" ("id" TEXT PRIMARY KEY, "name" VARCHAR(100) NOT NULL, "type" VARCHAR(100) NOT NULL UNIQUE, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "remark" VARCHAR(500), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_dict_data" ("id" TEXT PRIMARY KEY, "dict_type_id" TEXT NOT NULL, "label" VARCHAR(100) NOT NULL, "value" VARCHAR(100) NOT NULL, "sort" INTEGER NOT NULL DEFAULT 0, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "color_type" VARCHAR(20), "remark" VARCHAR(500), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_tenant" ("id" TEXT PRIMARY KEY, "name" VARCHAR(50) NOT NULL, "contact_name" VARCHAR(30), "contact_phone" VARCHAR(20), "domain" VARCHAR(100), "package_id" TEXT, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "expire_time" TIMESTAMP(3), "account_count" INTEGER NOT NULL DEFAULT 0, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_notice" ("id" TEXT PRIMARY KEY, "title" VARCHAR(100) NOT NULL, "content" TEXT NOT NULL, "type" VARCHAR(10) NOT NULL, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "system_login_log" ("id" TEXT PRIMARY KEY, "user_id" TEXT, "username" VARCHAR(50) NOT NULL, "user_ip" VARCHAR(50) NOT NULL, "user_agent" VARCHAR(500), "result" VARCHAR(10) NOT NULL, "remark" VARCHAR(500), "tenant_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "system_operate_log" ("id" TEXT PRIMARY KEY, "user_id" TEXT, "module" VARCHAR(50) NOT NULL, "name" VARCHAR(100) NOT NULL, "type" VARCHAR(20) NOT NULL, "request_method" VARCHAR(10) NOT NULL, "request_url" VARCHAR(500) NOT NULL, "content" TEXT, "result_code" INTEGER NOT NULL DEFAULT 0, "duration" INTEGER NOT NULL DEFAULT 0, "user_ip" VARCHAR(50), "tenant_id" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "infra_config" ("id" TEXT PRIMARY KEY, "category" VARCHAR(50) NOT NULL DEFAULT 'DEFAULT', "name" VARCHAR(100) NOT NULL, "config_key" VARCHAR(100) NOT NULL UNIQUE, "value" VARCHAR(500) NOT NULL, "visible" BOOLEAN NOT NULL DEFAULT true, "remark" VARCHAR(500), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "infra_job" ("id" TEXT PRIMARY KEY, "name" VARCHAR(100) NOT NULL, "handler_name" VARCHAR(200) NOT NULL, "handler_param" VARCHAR(500), "cron_expression" VARCHAR(50) NOT NULL, "retry_count" INTEGER NOT NULL DEFAULT 0, "retry_interval" INTEGER NOT NULL DEFAULT 0, "status" VARCHAR(10) NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "infra_job_log" ("id" TEXT PRIMARY KEY, "job_id" TEXT NOT NULL, "handler_name" VARCHAR(200) NOT NULL, "begin_time" TIMESTAMP(3) NOT NULL, "end_time" TIMESTAMP(3), "duration" INTEGER NOT NULL DEFAULT 0, "status" VARCHAR(10) NOT NULL, "result" TEXT, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "infra_api_access_log" ("id" TEXT PRIMARY KEY, "user_id" TEXT, "application_name" VARCHAR(50) NOT NULL, "request_method" VARCHAR(10) NOT NULL, "request_url" VARCHAR(500) NOT NULL, "request_params" TEXT, "response_body" TEXT, "result_code" INTEGER NOT NULL DEFAULT 0, "duration" INTEGER NOT NULL DEFAULT 0, "user_ip" VARCHAR(50), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "infra_api_error_log" ("id" TEXT PRIMARY KEY, "user_id" TEXT, "application_name" VARCHAR(50) NOT NULL, "request_method" VARCHAR(10) NOT NULL, "request_url" VARCHAR(500) NOT NULL, "request_params" TEXT, "exception_name" VARCHAR(200) NOT NULL, "exception_message" TEXT NOT NULL, "exception_stack" TEXT, "status" VARCHAR(20) NOT NULL DEFAULT 'UNPROCESSED', "user_ip" VARCHAR(50), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "infra_file_config" ("id" TEXT PRIMARY KEY, "name" VARCHAR(100) NOT NULL, "storage" VARCHAR(20) NOT NULL, "config" TEXT NOT NULL, "master" BOOLEAN NOT NULL DEFAULT false, "remark" VARCHAR(500), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL, "deleted" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "infra_file" ("id" TEXT PRIMARY KEY, "config_id" TEXT NOT NULL, "name" VARCHAR(200), "path" VARCHAR(500) NOT NULL, "url" VARCHAR(1024) NOT NULL, "type" VARCHAR(100), "size" INTEGER NOT NULL DEFAULT 0, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "system_user_tenant_id_idx" ON "system_user" ("tenant_id");
CREATE INDEX "system_user_dept_id_idx" ON "system_user" ("dept_id");
CREATE INDEX "system_user_status_idx" ON "system_user" ("status");
CREATE INDEX "system_role_tenant_id_idx" ON "system_role" ("tenant_id");
CREATE INDEX "system_menu_parent_id_idx" ON "system_menu" ("parent_id");
CREATE INDEX "system_dept_parent_id_idx" ON "system_dept" ("parent_id");
CREATE INDEX "system_dept_tenant_id_idx" ON "system_dept" ("tenant_id");
CREATE INDEX "system_post_tenant_id_idx" ON "system_post" ("tenant_id");
CREATE INDEX "system_dict_data_dict_type_id_idx" ON "system_dict_data" ("dict_type_id");
CREATE INDEX "system_login_log_user_id_idx" ON "system_login_log" ("user_id");
CREATE INDEX "system_login_log_created_at_idx" ON "system_login_log" ("created_at");
CREATE INDEX "system_operate_log_user_id_idx" ON "system_operate_log" ("user_id");
CREATE INDEX "system_operate_log_module_idx" ON "system_operate_log" ("module");
CREATE INDEX "system_operate_log_created_at_idx" ON "system_operate_log" ("created_at");
CREATE INDEX "infra_job_log_job_id_idx" ON "infra_job_log" ("job_id");
CREATE INDEX "infra_job_log_created_at_idx" ON "infra_job_log" ("created_at");
CREATE INDEX "infra_api_access_log_user_id_idx" ON "infra_api_access_log" ("user_id");
CREATE INDEX "infra_api_access_log_created_at_idx" ON "infra_api_access_log" ("created_at");
CREATE INDEX "infra_api_error_log_user_id_idx" ON "infra_api_error_log" ("user_id");
CREATE INDEX "infra_api_error_log_status_idx" ON "infra_api_error_log" ("status");
CREATE INDEX "infra_api_error_log_created_at_idx" ON "infra_api_error_log" ("created_at");
CREATE INDEX "infra_file_config_id_idx" ON "infra_file" ("config_id");
ALTER TABLE "system_user" ADD CONSTRAINT "system_user_dept_id_fkey" FOREIGN KEY ("dept_id") REFERENCES "system_dept" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "system_user_role" ADD CONSTRAINT "system_user_role_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "system_user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "system_user_role" ADD CONSTRAINT "system_user_role_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "system_role" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "system_menu" ADD CONSTRAINT "system_menu_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "system_menu" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "system_role_menu" ADD CONSTRAINT "system_role_menu_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "system_role" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "system_role_menu" ADD CONSTRAINT "system_role_menu_menu_id_fkey" FOREIGN KEY ("menu_id") REFERENCES "system_menu" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "system_dept" ADD CONSTRAINT "system_dept_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "system_dept" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "system_user_post" ADD CONSTRAINT "system_user_post_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "system_user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "system_user_post" ADD CONSTRAINT "system_user_post_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "system_post" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "system_dict_data" ADD CONSTRAINT "system_dict_data_dict_type_id_fkey" FOREIGN KEY ("dict_type_id") REFERENCES "system_dict_type" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "infra_job_log" ADD CONSTRAINT "infra_job_log_job_id_fkey" FOREIGN KEY ("job_id") REFERENCES "infra_job" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE TABLE "admin" ("id" TEXT PRIMARY KEY, "username" VARCHAR(100) NOT NULL UNIQUE, "phone" VARCHAR(20) UNIQUE, "password" VARCHAR(255) NOT NULL, "salt" VARCHAR(100), "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "setting" ("key" VARCHAR(200) PRIMARY KEY, "value" JSONB NOT NULL, "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE TABLE "approval_task" ("id" TEXT PRIMARY KEY, "biz_type" VARCHAR(100) NOT NULL, "title" VARCHAR(500), "applicant_name" VARCHAR(100), "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING', "reviewed_at" TIMESTAMP(3), "review_remark" VARCHAR(1000), "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMP(3) NOT NULL);
CREATE INDEX "approval_task_biz_type_idx" ON "approval_task" ("biz_type");
CREATE INDEX "approval_task_status_idx" ON "approval_task" ("status");
CREATE INDEX "approval_task_created_at_idx" ON "approval_task" ("created_at");
