// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { BargainActivityService } from "../bargain-activity.service"

describe("BargainActivityService", () => {
  it("should create and query BargainActivity（源框架导入）", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await BargainActivityService.create({
        name: "测试BargainActivity（源框架导入）",
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await BargainActivityService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await BargainActivityService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await BargainActivityService.update(created.id, {
        id: created.id,
        name: "更新BargainActivity（源框架导入）",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await BargainActivityService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
