// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { DeliveryPickUpStoreService } from "../delivery-pick-up-store.service"

describe("DeliveryPickUpStoreService", () => {
  it("should create and query 自提门店", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await DeliveryPickUpStoreService.create({
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted: true,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await DeliveryPickUpStoreService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await DeliveryPickUpStoreService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await DeliveryPickUpStoreService.update(created.id, {
        id: created.id,
          name: "测试更新自提门店",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await DeliveryPickUpStoreService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
