// Auto-generated by Codegen Engine (Service Unit Test)
import { describe, it, expect } from "vitest"
import { runWithTenantContext } from "@/modules/shared/backend/lib/biz-tenant"
import { ProductSkuService } from "../product-sku.service"

describe("ProductSkuService", () => {
  it("should create and query ProductSku（源框架导入）", async () => {
    await runWithTenantContext({ tenantId: "1" }, async () => {
      const created = await ProductSkuService.create({
        spu_id: 1,
      } as any)
      expect(created).toBeDefined()
      expect(created.id).toBeDefined()
  
      const list = await ProductSkuService.page({ page: 1, pageSize: 10 })
      expect(list.items.length).toBeGreaterThan(0)
  
      const fetched = await ProductSkuService.get(created.id)
      expect(fetched).toBeDefined()
      expect(fetched?.id).toBe(created.id)
  
      const updated = await ProductSkuService.update(created.id, {
        id: created.id,
        spu_id: "更新ProductSku（源框架导入）",
      } as any)
      expect(updated).toBeDefined()
  
      const deleted = await ProductSkuService.delete(created.id)
      expect(deleted).toBe(true)
    })
  })
})
