// Auto-generated by Codegen Engine (App Router Page)
import { WmsReceiptOrderListPage } from "@/modules/wms/frontend/pages/wms-receipt-order-list.page"

export default function Page() {
  return <WmsReceiptOrderListPage />
}
