// Auto-generated by Codegen Engine
import { z } from "zod"



export const mesCalHolidayPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mesCalHolidayCreateSchema = z.object({
  day: z.string().trim().optional(),
  type: z.coerce.number().finite().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mesCalHolidayUpdateSchema = mesCalHolidayCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MesCalHolidayPageQueryInput = z.infer<typeof mesCalHolidayPageQuerySchema>
export type MesCalHolidayCreateInput = z.infer<typeof mesCalHolidayCreateSchema>
export type MesCalHolidayUpdateInput = z.infer<typeof mesCalHolidayUpdateSchema>
