// Auto-generated by Codegen Engine
import { z } from "zod"



export const mesProWorkOrderPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mesProWorkOrderCreateSchema = z.object({
  code: z.string().trim().optional(),
  name: z.string().trim().optional(),
  type: z.coerce.number().finite().optional(),
  order_source_type: z.coerce.number().finite().optional(),
  order_source_code: z.string().trim().optional(),
  product_id: z.coerce.number().finite().optional(),
  quantity: z.coerce.number().finite().optional(),
  quantity_produced: z.coerce.number().finite().optional(),
  quantity_changed: z.coerce.number().finite().optional(),
  quantity_scheduled: z.coerce.number().finite().optional(),
  client_id: z.coerce.number().finite().optional(),
  vendor_id: z.coerce.number().finite().optional(),
  batch_code: z.string().trim().optional(),
  request_date: z.string().trim().optional(),
  parent_id: z.coerce.number().finite().optional(),
  finish_date: z.string().trim().optional(),
  cancel_date: z.string().trim().optional(),
  status: z.coerce.number().finite().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mesProWorkOrderUpdateSchema = mesProWorkOrderCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MesProWorkOrderPageQueryInput = z.infer<typeof mesProWorkOrderPageQuerySchema>
export type MesProWorkOrderCreateInput = z.infer<typeof mesProWorkOrderCreateSchema>
export type MesProWorkOrderUpdateInput = z.infer<typeof mesProWorkOrderUpdateSchema>
