// Auto-generated by Codegen Engine
import { z } from "zod"



export const mesWmOutsourceIssueLinePageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mesWmOutsourceIssueLineCreateSchema = z.object({
  issue_id: z.coerce.number().finite().optional(),
  material_stock_id: z.coerce.number().finite().optional(),
  item_id: z.coerce.number().finite().optional(),
  quantity: z.coerce.number().finite().optional(),
  batch_id: z.coerce.number().finite().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mesWmOutsourceIssueLineUpdateSchema = mesWmOutsourceIssueLineCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MesWmOutsourceIssueLinePageQueryInput = z.infer<typeof mesWmOutsourceIssueLinePageQuerySchema>
export type MesWmOutsourceIssueLineCreateInput = z.infer<typeof mesWmOutsourceIssueLineCreateSchema>
export type MesWmOutsourceIssueLineUpdateInput = z.infer<typeof mesWmOutsourceIssueLineUpdateSchema>
