// Auto-generated by Codegen Engine
import { z } from "zod"



export const mesWmTransferLinePageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mesWmTransferLineCreateSchema = z.object({
  transfer_id: z.coerce.number().finite().optional(),
  material_stock_id: z.coerce.number().finite().optional(),
  item_id: z.coerce.number().finite().optional(),
  quantity: z.coerce.number().finite().optional(),
  batch_id: z.coerce.number().finite().optional(),
  from_warehouse_id: z.coerce.number().finite().optional(),
  from_location_id: z.coerce.number().finite().optional(),
  from_area_id: z.coerce.number().finite().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mesWmTransferLineUpdateSchema = mesWmTransferLineCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MesWmTransferLinePageQueryInput = z.infer<typeof mesWmTransferLinePageQuerySchema>
export type MesWmTransferLineCreateInput = z.infer<typeof mesWmTransferLineCreateSchema>
export type MesWmTransferLineUpdateInput = z.infer<typeof mesWmTransferLineUpdateSchema>
