// Auto-generated by Codegen Engine
import { z } from "zod"



export const mesQcIpqcLinePageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mesQcIpqcLineCreateSchema = z.object({
  ipqc_id: z.coerce.number().finite().optional(),
  indicator_id: z.coerce.number().finite().optional(),
  tool: z.string().trim().optional(),
  check_method: z.string().trim().optional(),
  standard_value: z.coerce.number().finite().optional(),
  unit_measure_id: z.coerce.number().finite().optional(),
  max_threshold: z.coerce.number().finite().optional(),
  min_threshold: z.coerce.number().finite().optional(),
  critical_quantity: z.coerce.number().finite().optional(),
  major_quantity: z.coerce.number().finite().optional(),
  minor_quantity: z.coerce.number().finite().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mesQcIpqcLineUpdateSchema = mesQcIpqcLineCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MesQcIpqcLinePageQueryInput = z.infer<typeof mesQcIpqcLinePageQuerySchema>
export type MesQcIpqcLineCreateInput = z.infer<typeof mesQcIpqcLineCreateSchema>
export type MesQcIpqcLineUpdateInput = z.infer<typeof mesQcIpqcLineUpdateSchema>
