// Auto-generated by Codegen Engine
import { z } from "zod"



export const mesWmProductSalesLinePageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mesWmProductSalesLineCreateSchema = z.object({
  sales_id: z.coerce.number().finite().optional(),
  notice_line_id: z.coerce.number().finite().optional(),
  item_id: z.coerce.number().finite().optional(),
  quantity: z.coerce.number().finite().optional(),
  batch_id: z.coerce.number().finite().optional(),
  batch_code: z.string().trim().optional(),
  material_stock_id: z.coerce.number().finite().optional(),
  oqc_check_flag: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),
  oqc_id: z.coerce.number().finite().optional(),
  quality_status: z.coerce.number().finite().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mesWmProductSalesLineUpdateSchema = mesWmProductSalesLineCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MesWmProductSalesLinePageQueryInput = z.infer<typeof mesWmProductSalesLinePageQuerySchema>
export type MesWmProductSalesLineCreateInput = z.infer<typeof mesWmProductSalesLineCreateSchema>
export type MesWmProductSalesLineUpdateInput = z.infer<typeof mesWmProductSalesLineUpdateSchema>
