// Auto-generated by Codegen Engine
import { z } from "zod"



export const mesDvMachineryPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const mesDvMachineryCreateSchema = z.object({
  code: z.string().trim().optional(),
  name: z.string().trim().optional(),
  brand: z.string().trim().optional(),
  specification: z.string().trim().optional(),
  machinery_type_id: z.coerce.number().finite().optional(),
  workshop_id: z.coerce.number().finite().optional(),
  status: z.coerce.number().finite().optional(),
  last_mainten_time: z.string().trim().optional(),
  last_check_time: z.string().trim().optional(),
  remark: z.string().trim().optional(),

}).strict()

export const mesDvMachineryUpdateSchema = mesDvMachineryCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type MesDvMachineryPageQueryInput = z.infer<typeof mesDvMachineryPageQuerySchema>
export type MesDvMachineryCreateInput = z.infer<typeof mesDvMachineryCreateSchema>
export type MesDvMachineryUpdateInput = z.infer<typeof mesDvMachineryUpdateSchema>
