// Auto-generated by Codegen Engine (Frontend API Client)
import { request } from "@/modules/shared/frontend/lib/request"
import type {
  AigwPartnerLeadCreateDTO,
  AigwPartnerLeadPageQuery,
  AigwPartnerLeadUpdateDTO,
  AigwPartnerLeadVO,
} from "@/modules/aigw/backend/types/aigw-partner-lead.types"

const BASE_URL = "/api/v1/admin/aigw/aigw-partner-lead"

export const AigwPartnerLeadApi = {
  async page(params?: AigwPartnerLeadPageQuery) {
    return request.get<{ items: AigwPartnerLeadVO[]; total: number }>(BASE_URL, { params })
  },

  async get(id: string) {
    return request.get<AigwPartnerLeadVO>(`${BASE_URL}/${id}`)
  },

  async create(data: AigwPartnerLeadCreateDTO) {
    return request.post<AigwPartnerLeadVO>(BASE_URL, data)
  },

  async update(data: AigwPartnerLeadUpdateDTO) {
    return request.put<AigwPartnerLeadVO>(BASE_URL, data)
  },

  async delete(id: string) {
    return request.delete<void>(`${BASE_URL}?id=${id}`)
  },

  async export(params?: AigwPartnerLeadPageQuery) {
    return request.post<AigwPartnerLeadVO[]>(`${BASE_URL}/export`, params)
  },

  async getImportTemplate() {
    return request.get<{ columns: string[]; sampleRows: Record<string, unknown>[] }>(`${BASE_URL}/import-template`)
  },

  async import(file: File) {
    const formData = new FormData()
    formData.append("file", file)
    return request.post<{ importedCount: number }>(`${BASE_URL}/import`, formData)
  },
}
