// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  imChannelMaterialCreateSchema,
  imChannelMaterialPageQuerySchema,
  imChannelMaterialUpdateSchema,
} from "../backend/validators/im-channel-material.validator"

export const imChannelMaterialActionSchemas = {
  "ruoyi.cmd.im.imChannelMaterial.page": imChannelMaterialPageQuerySchema,
  "ruoyi.cmd.im.imChannelMaterial.get": z.object({ id: z.string() }),
  "ruoyi.cmd.im.imChannelMaterial.create": imChannelMaterialCreateSchema,
  "ruoyi.cmd.im.imChannelMaterial.update": imChannelMaterialUpdateSchema,
  "ruoyi.cmd.im.imChannelMaterial.delete": z.object({ id: z.string() }),
  "im.pageImChannelMaterial": imChannelMaterialPageQuerySchema,
  "im.getImChannelMaterial": z.object({ id: z.string() }),
  "im.createImChannelMaterial": imChannelMaterialCreateSchema,
  "im.updateImChannelMaterial": imChannelMaterialUpdateSchema,
  "im.deleteImChannelMaterial": z.object({ id: z.string() }),
} as const

export const IM_CHANNEL_MATERIAL_ACTION_SCHEMAS = imChannelMaterialActionSchemas

export function registerActionSchemas() {
  return imChannelMaterialActionSchemas
}
