// Auto-generated by Codegen Engine (Contract Actions)
import { z } from "zod"
import {
  imRtcParticipantCreateSchema,
  imRtcParticipantPageQuerySchema,
  imRtcParticipantUpdateSchema,
} from "../backend/validators/im-rtc-participant.validator"

export const imRtcParticipantActionSchemas = {
  "ruoyi.cmd.im.imRtcParticipant.page": imRtcParticipantPageQuerySchema,
  "ruoyi.cmd.im.imRtcParticipant.get": z.object({ id: z.string() }),
  "ruoyi.cmd.im.imRtcParticipant.create": imRtcParticipantCreateSchema,
  "ruoyi.cmd.im.imRtcParticipant.update": imRtcParticipantUpdateSchema,
  "ruoyi.cmd.im.imRtcParticipant.delete": z.object({ id: z.string() }),
  "im.pageImRtcParticipant": imRtcParticipantPageQuerySchema,
  "im.getImRtcParticipant": z.object({ id: z.string() }),
  "im.createImRtcParticipant": imRtcParticipantCreateSchema,
  "im.updateImRtcParticipant": imRtcParticipantUpdateSchema,
  "im.deleteImRtcParticipant": z.object({ id: z.string() }),
} as const

export const IM_RTC_PARTICIPANT_ACTION_SCHEMAS = imRtcParticipantActionSchemas

export function registerActionSchemas() {
  return imRtcParticipantActionSchemas
}
