// Auto-generated by Codegen Engine
import { z } from "zod"



export const iotAlertRecordPageQuerySchema = z.object({
  page: z.coerce.number().int().min(1).default(1),
  pageSize: z.coerce.number().int().min(1).max(100).default(20),

}).strict()

export const iotAlertRecordCreateSchema = z.object({
  config_id: z.coerce.number().finite().optional(),
  config_name: z.string().trim().optional(),
  config_level: z.coerce.number().finite().optional(),
  scene_rule_id: z.coerce.number().finite().optional(),
  product_id: z.coerce.number().finite().optional(),
  device_id: z.coerce.number().finite().optional(),
  device_message: z.string().trim().optional(),
  process_status: z.preprocess((value) => value === "true" ? true : value === "false" ? false : value, z.boolean()).optional(),
  process_remark: z.string().trim().optional(),

}).strict()

export const iotAlertRecordUpdateSchema = iotAlertRecordCreateSchema.partial().extend({
  id: z.string().min(1, "id 不能为空"),
}).strict()

export type IotAlertRecordPageQueryInput = z.infer<typeof iotAlertRecordPageQuerySchema>
export type IotAlertRecordCreateInput = z.infer<typeof iotAlertRecordCreateSchema>
export type IotAlertRecordUpdateInput = z.infer<typeof iotAlertRecordUpdateSchema>
