import { z } from "zod"
import { registerActionSchema } from "@/modules/shared/backend/lib/broker-validator"
import {
  getDictDataByTypeSchema,
  resolveTenantEntitlementSchema,
  userListQuerySchema,
  createUserSchema,
  roleListQuerySchema,
  createRoleSchema,
  menuQuerySchema,
  createMenuSchema,
  deptQuerySchema,
  createDeptSchema,
  postListQuerySchema,
  createPostSchema,
  dictTypeListQuerySchema,
  createDictTypeSchema,
  tenantListQuerySchema,
  createTenantWithAdminSchema,
  resourceIdSchema,
  updateUserSchema,
  deleteUserSchema,
  updateUserPasswordSchema,
  resourceStatusSchema,
  updateRoleSchema,
  updateMenuSchema,
  updateDeptSchema,
  updatePostSchema,
  updateDictTypeSchema,
  updateTenantSchema,
  listDictDataSchema,
  createDictDataSchema,
  updateDictDataSchema,
  tenantPackageListSchema,
  createTenantPackageSchema,
  updateTenantPackageSchema,
  assignTenantPackageSchema,
  getRoleMenusSchema,
  assignRoleMenuSchema,
  assignUserRoleSchema,
  loginLogQuerySchema,
  operateLogQuerySchema,
  systemModulePageQuerySchema,
  forceLogoutSchema,
  pageQuerySchema,
  createNoticeSchema,
  updateNoticeSchema,
  createSocialUserSchema,
  createMailAccountSchema,
  createSmsChannelSchema,
  createNotifyMessageSchema,
  createNotifyTemplateSchema,
  createAreaSchema,
  updateAreaSchema,
  loginSchema,
  actorIdSchema,
  refreshTokenSchema,
  emptyPayloadSchema,
  captchaVerifySchema,
  getUserProfileSchema,
  updateUserProfileSchema,
  sidebarNavSchema,
  oauth2OpenTokenSchema,
  oauth2UserInfoSchema,
  createMailTemplateSchema,
  updateMailTemplateSchema,
  createSmsTemplateSchema,
  updateSmsTemplateSchema,
  createSocialClientSchema,
  updateSocialClientSchema,
} from "../backend/validators"

export const systemPingSchema = z.object({
  n: z.number().optional(),
})

export const SYSTEM_ACTION_SCHEMAS = {
  "system.ping": systemPingSchema,
  "system.getDictDataByType": getDictDataByTypeSchema,
  "system.resolveTenantEntitlement": resolveTenantEntitlementSchema,
  "system.listUsers": userListQuerySchema,
  "system.createUser": createUserSchema,
  "system.listRoles": roleListQuerySchema,
  "system.createRole": createRoleSchema,
  "system.listMenus": menuQuerySchema,
  "system.treeMenus": menuQuerySchema,
  "system.createMenu": createMenuSchema,
  "system.listDepts": deptQuerySchema,
  "system.treeDepts": deptQuerySchema,
  "system.createDept": createDeptSchema,
  "system.listPosts": postListQuerySchema,
  "system.createPost": createPostSchema,
  "system.listDictTypes": dictTypeListQuerySchema,
  "system.createDictType": createDictTypeSchema,
  "system.listTenants": tenantListQuerySchema,
  "system.createTenant": createTenantWithAdminSchema,
  "system.getUser": resourceIdSchema,
  "system.updateUser": updateUserSchema,
  "system.deleteUser": deleteUserSchema,
  "system.resetUserPassword": updateUserPasswordSchema,
  "system.updateUserStatus": resourceStatusSchema,
  "system.getRole": resourceIdSchema,
  "system.updateRole": updateRoleSchema,
  "system.deleteRole": resourceIdSchema,
  "system.updateRoleStatus": resourceStatusSchema,
  "system.getMenu": resourceIdSchema,
  "system.updateMenu": updateMenuSchema,
  "system.deleteMenu": resourceIdSchema,
  "system.getDept": resourceIdSchema,
  "system.updateDept": updateDeptSchema,
  "system.deleteDept": resourceIdSchema,
  "system.getPost": resourceIdSchema,
  "system.updatePost": updatePostSchema,
  "system.deletePost": resourceIdSchema,
  "system.getDictType": resourceIdSchema,
  "system.updateDictType": updateDictTypeSchema,
  "system.deleteDictType": resourceIdSchema,
  "system.getTenant": resourceIdSchema,
  "system.updateTenant": updateTenantSchema,
  "system.deleteTenant": resourceIdSchema,
  "system.updateTenantStatus": resourceStatusSchema,
  "system.listDictData": listDictDataSchema,
  "system.createDictData": createDictDataSchema,
  "system.getDictData": resourceIdSchema,
  "system.updateDictData": updateDictDataSchema,
  "system.deleteDictData": resourceIdSchema,
  "system.listTenantPackages": tenantPackageListSchema,
  "system.createTenantPackage": createTenantPackageSchema,
  "system.getTenantPackage": resourceIdSchema,
  "system.updateTenantPackage": updateTenantPackageSchema,
  "system.deleteTenantPackage": resourceIdSchema,
  "system.assignTenantPackage": assignTenantPackageSchema,
  "system.getTenantSubscriptions": resourceIdSchema,
  "system.getRoleMenus": getRoleMenusSchema,
  "system.assignRoleMenu": assignRoleMenuSchema,
  "system.assignUserRole": assignUserRoleSchema,
  "system.pageLoginLogs": loginLogQuerySchema,
  "system.getLoginLog": resourceIdSchema,
  "system.exportLoginLogs": loginLogQuerySchema,
  "system.pageOperateLogs": operateLogQuerySchema,
  "system.getOperateLog": resourceIdSchema,
  "system.exportOperateLogs": operateLogQuerySchema,
  "system.listOnlineUsers": systemModulePageQuerySchema,
  "system.forceLogoutOnlineUser": forceLogoutSchema,
  "system.pageNotices": pageQuerySchema,
  "system.createNotice": createNoticeSchema,
  "system.getNotice": resourceIdSchema,
  "system.updateNotice": updateNoticeSchema,
  "system.deleteNotice": resourceIdSchema,
  "system.listOauth2Clients": pageQuerySchema,
  "system.listOauth2Tokens": pageQuerySchema,
  "system.listSocialUsers": systemModulePageQuerySchema,
  "system.createSocialUser": createSocialUserSchema,
  "system.listMailAccounts": systemModulePageQuerySchema,
  "system.createMailAccount": createMailAccountSchema,
  "system.listMailLogs": systemModulePageQuerySchema,
  "system.listSmsChannels": systemModulePageQuerySchema,
  "system.createSmsChannel": createSmsChannelSchema,
  "system.listSmsLogs": systemModulePageQuerySchema,
  "system.pageNotifyMessages": pageQuerySchema,
  "system.createNotifyMessage": createNotifyMessageSchema,
  "system.pageNotifyTemplates": pageQuerySchema,
  "system.createNotifyTemplate": createNotifyTemplateSchema,
  "system.pageIpAreas": systemModulePageQuerySchema,
  "system.pageAreas": pageQuerySchema,
  "system.createArea": createAreaSchema,
  "system.getArea": resourceIdSchema,
  "system.updateArea": updateAreaSchema,
  "system.deleteArea": resourceIdSchema,
  "system.login": loginSchema,
  "system.getPermissionInfoByUser": actorIdSchema,
  "system.refreshAccessToken": refreshTokenSchema,
  "system.logout": emptyPayloadSchema,
  "system.generateCaptcha": emptyPayloadSchema,
  "system.verifyCaptcha": captchaVerifySchema,
  "system.getUserProfile": getUserProfileSchema,
  "system.updateUserProfile": updateUserProfileSchema,
  "system.getSidebarNav": sidebarNavSchema,
  "system.openOauth2Token": oauth2OpenTokenSchema,
  "system.getOauth2UserInfo": oauth2UserInfoSchema,
  "system.listMailTemplates": systemModulePageQuerySchema,
  "system.createMailTemplate": createMailTemplateSchema,
  "system.getMailTemplate": resourceIdSchema,
  "system.updateMailTemplate": updateMailTemplateSchema,
  "system.deleteMailTemplate": resourceIdSchema,
  "system.listSmsTemplates": systemModulePageQuerySchema,
  "system.createSmsTemplate": createSmsTemplateSchema,
  "system.getSmsTemplate": resourceIdSchema,
  "system.updateSmsTemplate": updateSmsTemplateSchema,
  "system.deleteSmsTemplate": resourceIdSchema,
  "system.listSocialClients": systemModulePageQuerySchema,
  "system.createSocialClient": createSocialClientSchema,
  "system.getSocialClient": resourceIdSchema,
  "system.updateSocialClient": updateSocialClientSchema,
  "system.deleteSocialClient": resourceIdSchema,
} as const

export function registerActionSchemas() {
  for (const [action, schema] of Object.entries(SYSTEM_ACTION_SCHEMAS)) {
    registerActionSchema(action, schema)
  }
}
