"use client"

import { useCallback, useEffect, useState } from "react"
import { API, request } from "@/modules/shared/frontend/lib/request"

type Row = { id: string; traceId: string | null; errorCode: string | null; exceptionName: string; exceptionMessage: string; requestUrl: string; status: "UNPROCESSED" | "PROCESSED"; processedAt: string | null; processedBy: string | null; processNote: string | null; rootCause: string | null; exceptionStack: string | null; createdAt: string }
type Page = { items: Row[]; total: number; page: number; pageSize: number }
async function download(url: string) { const token = localStorage.getItem("ruoyi_token"); const response = await fetch(url, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error("导出失败"); const link = document.createElement("a"); link.href = URL.createObjectURL(await response.blob()); link.download = "api-error-logs.csv"; link.click(); URL.revokeObjectURL(link.href) }

export default function InfraApiErrorLogsModulePage() {
  const [data, setData] = useState<Page>(); const [keyword, setKeyword] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Row>(); const [error, setError] = useState("")
  const load = useCallback(async () => { const res = await request.get<Page>(API.API_ERROR_LOGS, { page, pageSize: 20, keyword: keyword || undefined, status: status || undefined }); if (res.success && res.data) setData(res.data); else setError(res.message || res.error || "加载失败") }, [page, keyword, status])
  useEffect(() => { void load() }, [load])
  const process = async (row: Row) => { const processNote = window.prompt("处理说明（可选）") ?? undefined; const res = await request.patch(`${API.API_ERROR_LOGS}/${row.id}`, { processNote }); if (res.success) { setSelected(undefined); void load() } else setError(res.message || res.error || "标记失败") }
  return <div className="space-y-4"><section className="rounded-lg border bg-white p-4"><h1 className="text-lg font-semibold">API 错误日志</h1><p className="text-xs text-slate-500">异常详情仅向授权管理员展示；使用 Trace ID 关联访问日志与服务端日志。</p></section><section className="flex flex-wrap gap-2 rounded-lg border bg-white p-4"><input className="h-9 w-72 rounded border px-3 text-sm" value={keyword} onChange={e => setKeyword(e.target.value)} placeholder="Trace ID、错误码、路径或异常"/><select className="h-9 rounded border px-2 text-sm" value={status} onChange={e => { setStatus(e.target.value); setPage(1) }}><option value="">全部状态</option><option value="UNPROCESSED">待处理</option><option value="PROCESSED">已处理</option></select><button className="h-9 rounded bg-slate-900 px-4 text-sm text-white" onClick={() => { setPage(1); void load() }}>查询</button><button className="h-9 rounded border px-4 text-sm" onClick={() => void download(`${API.API_ERROR_LOGS}/export?keyword=${encodeURIComponent(keyword)}&status=${status}`).catch(e => setError(e.message))}>导出 CSV</button>{data && <span className="ml-auto self-center text-xs text-slate-500">共 {data.total} 条</span>}</section>{error && <p className="text-sm text-red-600">{error}</p>}<section className="overflow-x-auto rounded-lg border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">错误</th><th>Trace ID</th><th>路径</th><th>状态</th><th>时间</th><th/></tr></thead><tbody>{data?.items.map(row => <tr key={row.id} className="border-t"><td className="p-3"><b>{row.errorCode || row.exceptionName}</b><br/><span className="text-xs text-slate-500">{row.exceptionMessage}</span></td><td className="font-mono text-xs">{row.traceId || "—"}</td><td>{row.requestUrl}</td><td>{row.status === "PROCESSED" ? "已处理" : "待处理"}</td><td>{new Date(row.createdAt).toLocaleString()}</td><td className="space-x-2"><button className="text-blue-600" onClick={() => setSelected(row)}>详情</button>{row.status === "UNPROCESSED" && <button className="text-emerald-600" onClick={() => void process(row)}>标记已处理</button>}</td></tr>)}</tbody></table>{!data?.items.length && <p className="p-10 text-center text-sm text-slate-400">暂无错误日志</p>}<div className="flex justify-between border-t p-3 text-sm"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><span>{page}</span><button disabled={!data || page * data.pageSize >= data.total} onClick={() => setPage(page + 1)}>下一页</button></div></section>{selected && <section className="rounded-lg border bg-white p-4"><div className="flex justify-between"><h2 className="font-medium">错误详情</h2><button onClick={() => setSelected(undefined)}>关闭</button></div><pre className="mt-3 max-h-96 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(selected, null, 2)}</pre></section>}</div>
}
