"use client"

import { useCallback, useEffect, useState } from "react"
import { API, request } from "@/modules/shared/frontend/lib/request"

type Row = { id: string; traceId: string | null; requestMethod: string; requestUrl: string; resultCode: number; duration: number; userId: string | null; userIp: string | null; operation: string | null; createdAt: string }
type Page = { items: Row[]; total: number; page: number; pageSize: number }

async function download(url: string) { const token = localStorage.getItem("ruoyi_token"); const response = await fetch(url, { headers: token ? { Authorization: `Bearer ${token}` } : {} }); if (!response.ok) throw new Error("导出失败"); const link = document.createElement("a"); link.href = URL.createObjectURL(await response.blob()); link.download = "api-access-logs.csv"; link.click(); URL.revokeObjectURL(link.href) }

export default function ApiAccessLogPage() {
  const [data, setData] = useState<Page>(); const [keyword, setKeyword] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Row>(); const [error, setError] = useState("")
  const load = useCallback(async () => { const res = await request.get<Page>(API.API_ACCESS_LOGS, { page, pageSize: 20, keyword: keyword || undefined }); if (res.success && res.data) setData(res.data); else setError(res.message || res.error || "加载失败") }, [page, keyword])
  useEffect(() => { void load() }, [load])
  return <div className="space-y-4"><section className="rounded-lg border bg-white p-4"><h1 className="text-lg font-semibold">API 访问日志</h1><p className="text-xs text-slate-500">按 Trace ID、路径或方法检索；请求参数已脱敏。</p></section><section className="flex flex-wrap gap-2 rounded-lg border bg-white p-4"><input className="h-9 w-80 rounded border px-3 text-sm" value={keyword} onChange={e => setKeyword(e.target.value)} onKeyDown={e => e.key === "Enter" && (setPage(1), void load())} placeholder="Trace ID、路径或请求方法"/><button className="h-9 rounded bg-slate-900 px-4 text-sm text-white" onClick={() => { setPage(1); void load() }}>查询</button><button className="h-9 rounded border px-4 text-sm" onClick={() => void download(`${API.API_ACCESS_LOGS}/export?keyword=${encodeURIComponent(keyword)}`).catch(e => setError(e.message))}>导出 CSV</button>{data && <span className="ml-auto self-center text-xs text-slate-500">共 {data.total} 条</span>}</section>{error && <p className="text-sm text-red-600">{error}</p>}<section className="overflow-x-auto rounded-lg border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Trace ID</th><th>请求</th><th>状态</th><th>耗时</th><th>用户/IP</th><th>时间</th><th/></tr></thead><tbody>{data?.items.map(row => <tr key={row.id} className="border-t"><td className="p-3 font-mono text-xs">{row.traceId || "—"}</td><td>{row.requestMethod} {row.requestUrl}</td><td>{row.resultCode}</td><td>{row.duration}ms</td><td>{row.userId || "匿名"}<br/><span className="text-xs text-slate-400">{row.userIp || "—"}</span></td><td>{new Date(row.createdAt).toLocaleString()}</td><td><button className="text-blue-600" onClick={() => setSelected(row)}>详情</button></td></tr>)}</tbody></table>{!data?.items.length && <p className="p-10 text-center text-sm text-slate-400">暂无日志</p>}<div className="flex justify-between border-t p-3 text-sm"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><span>{page}</span><button disabled={!data || page * data.pageSize >= data.total} onClick={() => setPage(page + 1)}>下一页</button></div></section>{selected && <section className="rounded-lg border bg-white p-4"><div className="flex justify-between"><h2 className="font-medium">访问详情</h2><button onClick={() => setSelected(undefined)}>关闭</button></div><pre className="mt-3 max-h-80 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(selected, null, 2)}</pre></section>}</div>
}
